### ISSUE TITLE
Invalid example in Readme

### ISSUE THREAD

**Issue by mueller-ma** [AppIntro/AppIntro#1003]
## 🐛 Describe the bug
From the current Readme:

```kotlin
addSlide(AppIntroFragment.createInstance(
    title = "The title of your slide",
    description = "A description that will be shown on the bottom",
    imageDrawable = R.drawable.the_central_icon,
    backgroundDrawable = R.drawable.the_background_image,
    titleColor = ContextCompat(context, R.color.yellow),
    descriptionColor = ContextCompat(context, R.color.red),
    backgroundColor = ContextCompat(context, R.color.blue),
    titleTypefaceFontRes = R.font.opensans_regular,
    descriptionTypefaceFontRes = R.font.opensans_regular,
))
```

According to https://developer.android.com/reference/kotlin/androidx/core/content/ContextCompat?hl=en#ContextCompat() there's no constructor of `ContextCompat` that takes arguments. Did you mean `ContextCompat.getColor()` here?

**Comment by cortinico** [comment]
Yup you're right. Don't you mind sending a PR to fix it? :)

**Comment by mueller-ma** [comment]
Ok, but then there's another issue: `ContextCompat.getColor()` returns `@ColorInt`, but parameter `titleColorRes` of `AppIntroFragment.createInstance()` is a `@ColorRes`.

- https://github.com/AppIntro/AppIntro/blob/main/appintro/src/main/java/com/github/appintro/AppIntroFragment.kt#L96
- https://developer.android.com/reference/kotlin/androidx/core/content/ContextCompat?hl=en#getColor(android.content.Context,int)

This might explain why version 6.2.0 crashes for me: https://github.com/openhab/openhab-android/pull/2816

**Comment by paolorotolo** [comment]
You can directly pass the color resource, you don't have to use `ContextCompat`:
```
        addSlide(AppIntroFragment.createInstance(
                "Welcome!",
                "Description.",
                backgroundColorRes = R.color.appintro_background_color
        ))
```

I see from your crash that you're using color attrs from your theme, this answer may help you: https://stackoverflow.com/a/51561533/3808158
