### ISSUE TITLE
Integrating with Android Java

### ISSUE THREAD

**Issue by SoftCareTech** [AppIntro/AppIntro#1006]
Unable to add the dependency successfully. I worked with  it using kotlin with error but now giving me errors as I want to integrate it to my java base Android App I got  errors:

## Syn give this error/warnings:
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.AppIntro:AppIntro:6.2.0.
Show Details
Affected Modules: app

##Build apk give these error 
Unknown host 'jcenter.bintray.com'. You may need to adjust the proxy settings in Gradle.
Learn about configuring HTTP proxies in Gradle

##build.gradle--App
grade version is 7.0.4 
    compileSdkVersion 31
    buildToolsVersion "30.0.3" 
        minSdkVersion 19
        targetSdkVersion 31 

implementation 'com.github.AppIntro:AppIntro:6.2.0'

##build.gradle--Project
```
buildscript {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
} 
```

**Comment by cortinico** [comment]
You should remove jcenter() from your setup as I believe it's causing confusion for your Gradle instance

```diff
buildscript {
    repositories {
        google()
-       jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
} 
```

**Comment by SoftCareTech** [comment]
With jcenter()
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 22s

upgrading Gradle to 8.0
Unknown host 'This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server (jcenter.bintray.com)'. You may need to adjust the proxy settings in Gradle.
Enable Gradle 'offline mode' and sync project
Learn about configuring HTTP proxies in Gradle

**Comment by cortinico** [comment]
You have `jcenter()` in any other .gradle file in your setup:

> Unknown host 'This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server (jcenter.bintray.com)'.

**Comment by SoftCareTech** [comment]
Removing the jcenter cause error here are dependencies I use in my project 

 implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'com.google.code.gson:gson:2.8.8'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    androidTestImplementation 'androidx.test:runner:1.4.0'
    androidTestImplementation 'androidx.test:rules:1.4.1-alpha04'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.4.0'



Using this  
implementation 'com.heinrichreimersoftware:material-intro:2.0.0'
cause no error but both are using  maven { url "https://jitpack.io" } 
 but it have it own issues 


My suggestion 
Most I use kotlin Id with it?  My App is purely java.
Implementing it with kotlin App was a single click sth

**Comment by cortinico** [comment]
> Most I use kotlin Id with it? My App is purely java.
> Implementing it with kotlin App was a single click sth

Java/Kotlin is not an issue. The two languages are fully interchangeable.
If you're using Java, you can still use AppIntro (we have have examples for it).

Your build is broken because it can't find some libraries.

Please share a minimal reproducer as I can't help you further.

**Comment by SoftCareTech** [comment]
Thanks for the help/time 
Putting `maven { url "https://jitpack.io" }`  above dependencies resolve my errors. I also change `jcenter()` to   `mavenCentral()`
I go through my kotlin project to see the differences between it and the java project as mission earlier there is no difference. 
 
I am really grateful @cortinico  

Sample below 

 `
repositories {
    maven { url "https://jitpack.io" }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'com.google.code.gson:gson:2.8.8'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    androidTestImplementation 'androidx.test:runner:1.4.0'
    androidTestImplementation 'androidx.test:rules:1.4.1-alpha04'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.4.0'
    implementation 'com.heinrichreimersoftware:material-intro:2.0.0'
    implementation 'com.github.AppIntro:AppIntro:6.2.0'
}`
