### ISSUE TITLE
Version 4.2.3 is not working

### ISSUE THREAD

**Issue by renyuneyun** [AppIntro/AppIntro#1008]
## 🐛 Describe the bug
My app [has AppIntro as a dependency](https://github.com/renyuneyun/Easer/blob/v0.8.2.2/app/build.gradle#L76). It used to work without issues. But a recent build fails, saying:
```
Could not find com.github.AppIntro:AppIntro:4.2.3.
```

I did not update the AppIntro version in the recent release.

Replacing 4.2.3 with other versions (e.g. 6.2.0, 5.0.0, 4.2.2) can make the build work without issues.

Interestingly, using `com.github.AppIntro:appintro:4.2.3` (lower-case letters) works.

I presume this is because of some errors of JitPack. For example, they incorrectly removed / lost some versions. (I found https://github.com/jitpack/jitpack.io/issues/3908 which is different from this issue but seems to imply their service is somewhat unreliable. Not complaining as they did not charge nor unrealistically promise anything and keeps responding.)

Note: cleaning the cache first is needed, otherwise the previously cached version will be used, and the error won't appear. I noticed this error because the app is on f-droid, and its building environment always performs clean build.

(I will update the dependency to a newer version afterwards. But because the app is already tagged/released, I would hope to stick with the existing configuration.)

## ⚠️ Current behavior
Error while building.
Check [here](https://monitor.f-droid.org/builds/log/ryey.easer.beta/128001#site-footer) for the full log. (This is automated by f-droid official building, so its content will change after the issue is solved.)

## ✅ Expected behavior
No errors.

**Comment by cortinico** [comment]
Not sure what's going on but this is not an issue of AppIntro, but of JitPack instead.
As you said, this gives a 404:
https://jitpack.io/com/github/AppIntro/AppIntro/4.2.3/AppIntro-4.2.3.aar

while this works:
https://jitpack.io/com/github/AppIntro/appintro/4.2.3/appintro-4.2.3.aar

I'm not sure what is actionable here on our end 🤔

**Comment by renyuneyun** [comment]
@cortinico Maybe report this to jitpack (as the maintainer), and hope they would respond somehow...? Guess this is a part of a bigger bug which not only affects AppIntro.


From my position, the easiest thing is to update the dependency for my app, and ignore this failed build 😂

**Comment by renyuneyun** [comment]
@cortinico Is there a way to manually trigger a rebuild of the library on JitPack?
Maybe report this to JitPack (as the maintainer), and hope they would respond somehow...? Guess this is a part of a bigger bug which not only affects AppIntro.

From my position, the easiest thing is to update the dependency for my app, and ignore this failed build 😂

**Comment by cortinico** [comment]
> @cortinico Is there a way to manually trigger a rebuild of the library on JitPack?

Not that I'm aware of. Given that this is a old version of AppIntro, we're not currently supporting it. I invite you to report this to JitPack directly if this is crucial for your setup or update to a newer version of AppIntro 👍
