### ISSUE TITLE
Not working  with cutout:0.1.2 Library

### ISSUE THREAD

**Issue by kkpareek1991** [AppIntro/AppIntro#1015]
getting below error when use with library 'com.github.gabrielbb:cutout:0.1.2'

Giving below error: 

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.localapp/com.localapp.SplashIntroNew}: android.view.InflateException: Binary XML file line #48 in com.localmarketplace:layout/appintro_intro_layout: Binary XML file line #48: You must supply a layout_width attribute.

 Caused by: android.view.InflateException: Binary XML file line #48 in com.localapp/appintro_intro_layout: Binary XML file line #48: You must supply a layout_width attribute.
     Caused by: java.lang.UnsupportedOperationException: Binary XML file line #48: You must supply a layout_width attribute.
 

After removing above library app working fine.  unable to identify the issue kindly suggest solution

**Comment by cortinico** [comment]
Could you create a small reproducer? I can look into it afterwards

**Comment by cortinico** [comment]
Hey,
I'm closing this issue as it appears to be stale.
Feel free to re-open it or create a new issue if the problem persists.
Thanks
