### ISSUE TITLE
Move to ViewPager2

### ISSUE THREAD

**Issue by cortinico** [AppIntro/AppIntro#1047]
## ⚠️ Current problem
Our library builds on top of `FragmentPagerAdapter`. This class is deprecated:
https://developer.android.com/reference/androidx/fragment/app/FragmentPagerAdapter

## 💡 Describe the solution you'd like
We should move to ViewPager2 and eventually use `FragmentStateAdapter`:
https://developer.android.com/reference/androidx/viewpager2/adapter/FragmentStateAdapter

@paolorotolo has started to look into this. We'll be happy to collaborate or accept PRs that help us investigate this change.

Please note that this change is most likely non-trivial and will probably require a breaking change.

**Comment by Akshay-21** [comment]
Hey Hi @cortinico could you assign me this issue under hacktoberfest 2022 and help me in starting contribution.

**Comment by cortinico** [comment]
@Akshay-21 I can definitely assign you this issue, but please note that this is not the best for first time contributors as it can be quite complicated.

**Comment by paolorotolo** [comment]
Hey @Akshay-21! As @cortinico said, we've started working on a migration to ViewPager2 [here](https://github.com/AppIntro/AppIntro/tree/viewpager2). It's not a trivial contribution if you're approaching the project for the first time :)
