### ISSUE TITLE
Light theme not working properly

### ISSUE THREAD

**Issue by Adlemex** [AppIntro/AppIntro#1061]
## 🐛 Describe the bug
When the white theme is enabled on the device, the entire bottom bar does not change color and blends into the background

## ⚠️ Current behavior
Light theme blends text into background

## ✅ Expected behavior
Text should be black in light theme and white in dark theme

## 💣 Steps to reproduce
Enable light theme

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/87426336/204159616-f12d547d-7a2a-4b83-b13e-1b801968e412.png)

## 📑 Your Code
`override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        showStatusBar(true)

        // Make sure you don't call setContentView!
        isColorTransitionsEnabled = true
        mySharedPreferences = getSharedPreferences("intro", Context.MODE_PRIVATE)
        // Call addSlide passing your Fragments.
        // You can use AppIntroFragment to use a pre-built fragment
        setTransformer(
            AppIntroPageTransformerType.Zoom)
        addSlide(
            AppIntroFragment.newInstance(
                title = "Помощник в бинарном коде",
                imageDrawable = R.drawable.icon,
                titleColor = resources.getColor(R.color.text, application.theme),
                descriptionColor = resources.getColor(R.color.text, application.theme),
                description = "Данное приложение поможет вам научиться работать с двоичными системами "
        ))
        addSlide(AppIntroFragment.newInstance(
            title = "Калькулятор",
            description = "Вводите нужные вам числа в калькулятор. Он переводит их в выбранную систему и показывает вам весь процесс.\n",
            titleColor = resources.getColor(R.color.text, application.theme),
            descriptionColor = resources.getColor(R.color.text, application.theme),
            imageDrawable = R.drawable.ic_baseline_published_with_changes_500,
        ))
        addSlide(AppIntroFragment.newInstance(
                title = "Таблицы истинности",
                imageDrawable = R.drawable.ic_baseline_table_view_500,
            descriptionColor = resources.getColor(R.color.text, application.theme),
                description = "Та же эта программа может строить таблицы истинности, логические схемы.",
            titleColor = resources.getColor(R.color.text, application.theme)
        ))
    }`

## 📱 Tech info
 - AppIntro Version: 6.1.0
 - Device: Xiaomi redmi 9T
 - Android OS Version: 12L

**Comment by cortinico** [comment]
That can easily be achieved by invoking:

```
setDoneTextAppearance
setSkipTextAppearance
```

and passing a `textAppearance` that uses your `R.color.text` for the Text Color.
