### ISSUE TITLE
Do not translate by default to all supported languages to match the app interface

### ISSUE THREAD

**Issue by wal0x** [AppIntro/AppIntro#1065]
## ⚠️ Is your feature request related to a problem? Please describe
It's great that AppIntro supports many languages. But I find it a bit weird if an application does not support a specific language, so all texts are in the falbback language except AppIntros strings. 
For example, if my app does not support Arabic and fallback to english. It's a bit confusing and weird to have only "Skip" and "Done" in the intro slides in Arabic and everything else is written in English.

## 💡 Describe the solution you'd like
Maybe a way to authorize only some languages support in AppIntro and not the others even if they are available.

## 🤚 Do you want to develop this feature yourself?
- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
That's already doable out of the box. You can use the `resConfig` configuration key in your `build.gradle` to strip away configuration you don't support. So for example you can specify you support only english so all the other languages also from AppIntro will be stripped away.
