### ISSUE TITLE
Icon Overlapping !!!

### ISSUE THREAD

**Issue by heihitesh** [AppIntro/AppIntro#1097]
## 🐛 Describe the bug
First Page its Okay : I see a Curved Arrow, But when I swipe to Right I see that the Back Button is overlapping the Previous Button 

## ⚠️ Current behavior
Buttons are overlapping to the previous button

## ✅ Expected behavior
It should not consider the previous button 

## 💣 Steps to reproduce
Just use this code below, and a real device You will be able to reproduce it 

## 📷 Screenshots

Note : ss1 First Screenshot is the First Page and ss2 is the Second Screenshot of the Second Page, When we swipe to right.
You can see that in the second page the back button (left Side) icon is overlapping 

![ss1](https://github.com/AppIntro/AppIntro/assets/13065741/1bbf0573-3518-47f1-bc30-3c4747fb62d2)
![ss2](https://github.com/AppIntro/AppIntro/assets/13065741/5ffe4476-657c-4795-946a-50dd1943cd30)

## 📑 Your Code
`import com.github.appintro.AppIntro2;
import com.github.appintro.AppIntroFragment;

public class AppIntroWizardNew extends AppIntro2 {

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addSlide(AppIntroFragment.createInstance("Welcome!\nReady to Take Rent ?",
                "Be Easy On YourSelf\nLet this App Do All the Work",
                R.drawable.app_logo, //Main Centre Image
                R.color.white, // Back Ground Color
                R.color.purple_900, // Heading Color
                R.color.black //Description color
                )
        );

        addSlide(AppFeatures.newInstance("Welcome!",
                "This is a demo example in java of AppIntro library, with a custom background on each slide!"));

        addSlide(AppIntroPolicyFragment.newInstance("Welcome!",
                "This is a demo example in java of AppIntro library, with a custom background on each slide!"));

        // Show/hide status bar
        showStatusBar(true);

        //Speed up or down scrolling
        setScrollDurationFactor(2);

        //Prevent the back button from exiting the slides
        setSystemBackButtonLocked(true);

        //Activate wizard mode (Some aesthetic changes)
        setWizardMode(true);

        //Show/hide skip button
        setSkipButtonEnabled(true);

        //Enable/disable page indicators
        setIndicatorEnabled(true);

        //Dhow/hide ALL buttons
        setButtonsEnabled(true);
    }
}`

## 📱 Tech info
 - AppIntro Version: com.github.AppIntro:AppIntro:6.2.0
 - Device:  Samsung S20FE ( Android 13 ) 
 - compileSdk 34

**Comment by heihitesh** [comment]
![ss3](https://github.com/AppIntro/AppIntro/assets/13065741/8d37b4c6-69e4-494e-87cd-2380911aa07a)
The Problem

**Comment by cortinico** [comment]
This happens as you enabled **both** Wizard Mode and you enabled the Skip Button. So they draw on top of each other:

```
    //Activate wizard mode (Some aesthetic changes)
    setWizardMode(true);

    //Show/hide skip button
    setSkipButtonEnabled(true);
```
