### ISSUE TITLE
Error when using Parallax Effect

### ISSUE THREAD

**Issue by KruemelopmentDev** [AppIntro/AppIntro#1102]
## 🐛 Describe the bug
When using the Parallax Transformer (Java) the app crashes immediately. It works with the Fade effect for example. Its because I am using custom slide Fragments and layouts I guess.

## 📷 Screenshots
![image](https://github.com/AppIntro/AppIntro/assets/26228417/f666f2df-8a8b-4289-a39f-83d02b61aef3)

## 📑 Your Code
setTransformer(new AppIntroPageTransformerType.Parallax());
in the Activities onCreate after adding the slides, also tried it before the slides

## 📱 Tech info
 - AppIntro Version:  6.1.0 
 - Device: Pixel 5 Api 31 emulated
 - Android OS Version: Android 12

**Comment by cortinico** [comment]
> Its because I am using custom slide Fragments and layouts I guess.

This is happening as you're providing a custom layout **without** the right IDs:

https://github.com/AppIntro/AppIntro/blob/66834f2d0423730db0f896fac7e23f099062a49a/appintro/src/main/java/com/github/appintro/internal/viewpager/ViewPagerTransformer.kt#L55C1-L59

Your layout should have a `.title` `.image` and a `.description` views.

Still AppIntro shouldn't crash in those scenarios, so I'll send over a fix for this problem.
