### ISSUE TITLE
Spannable, HTML text does not style

### ISSUE THREAD

**Issue by StainlessStlRat** [AppIntro/AppIntro#1125]
## 🐛 Describe the bug
All textView's can be set with Spannable text, or text from HtmlCompat that allows styling the text. This does not work with the default AppIntro fragment

## ⚠️ Current behavior
Text styling does not work

## ✅ Expected behavior
Text styling should work like it does for all TextViews

## 💣 Steps to reproduce
```
val longDescription = SpannableStringBuilder()
        longDescription.append("First Part Not Bold ")
        val start = longDescription.length
        longDescription.append("BOLD")
        longDescription.setSpan(
            ForegroundColorSpan(-0x33ab00),
            start,
            longDescription.length,
            Spannable.SPAN_EXCLUSIVE_EXCLUSIVE
        )
        longDescription.setSpan(
            StyleSpan(Typeface.BOLD),
            start,
            longDescription.length,
            Spannable.SPAN_EXCLUSIVE_EXCLUSIVE
        )
        longDescription.append(" rest not bold")
```

Now set that as "description" and you will see no styling

## 📱 Tech info
Latest version

**Comment by cortinico** [comment]
Can you share a screenshot @StainlessStlRat ?

**Comment by StainlessStlRat** [comment]
If you set that builder on any TextView via setText you will see the word BOLD in bold and colored while the rest of the text remains in the default style. If you pass this string to AppIntro itll just show plain text

**Comment by StainlessStlRat** [comment]
@cortinico 
In AppIntro (whether I use my custom fragment or not)
![Screenshot_20230813_214750](https://github.com/AppIntro/AppIntro/assets/16851186/802484ab-0e9e-4a3a-bbdf-22793e424c6f)

In a random TextView in my app
![Screenshot_20230813_214734](https://github.com/AppIntro/AppIntro/assets/16851186/c2dfd74c-6e41-4005-9d76-13b2f0185fc4)

**Comment by paolorotolo** [comment]
Thanks for reporting this! It happens because internally title and description are passed around as `String` and not `CharSequence` which `SpannableString` implements.

**Comment by paolorotolo** [comment]
@StainlessStlRat the issue has been fixed and will be available in next release. If you want to try it now, you can use our [SNAPSHOT builds](https://jitpack.io/#AppIntro/appintro/-SNAPSHOT).
