### ISSUE TITLE
App crash with POST_NOTIFICATIONS permission on Android 13

### ISSUE THREAD

**Issue by dzungpv** [AppIntro/AppIntro#1132]
## 🐛 Describe the bug

Recently I release an update with latest AppIntro with POST_NOTIFICATIONS permission and receive some user report app crash, this permission only available on Android 13 and later. I could not re produce the bug with my test device.

## ✅ Expected behavior

App should run normally without crash

## 💣 Steps to reproduce

When use from slide 3 to the next slide app will crash.

## 📑 Your Code

Code introduce the bug:
```
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            askForPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS}, 3);
        }
```

## 📱 Tech info
 - AppIntro Version: 6.3.1
 - Device: Samsung Galaxy S20 5G, Samsung Galaxy S21 5G 
 - Android OS Version: 13.0

**Comment by paolorotolo** [comment]
Hi @dzungpv, thanks for the report.
Unfortunately, I'm unable to reproduce this issue, are you able to upload a repro project?

Could you also provide more details about the crash (ex. stacktraces) please?

**Comment by dzungpv** [comment]
> Hi @dzungpv, thanks for the report. Unfortunately, I'm unable to reproduce this issue, are you able to upload a repro project?
> 
> Could you also provide more details about the crash (ex. stacktraces) please?

The project could not be public, seem that the Post Notification is require and when user decline the permission, the permission popup not appear again by design of Android, so AppIntro stuck at the 3 page, User annoy tap the screen and  it loop back cause out of memory, so it crash.

**Comment by paolorotolo** [comment]
I see, in this case you can use [onUserDeniedPermission()](https://github.com/AppIntro/AppIntro#permission-) to be notified in case permission is declined and react accordingly.

Eventually, you could also implement a [Slide Policy](https://github.com/AppIntro/AppIntro#slide-policy) if the permission is not mandatory and unlock the intro for the user.

**Comment by vernazza** [comment]
I'm having the same problem. Shouldn't the parameter "required" already manage this situation?
If the user denies the permission and the required parameter is false, the user should go to the next slide.
