### ISSUE TITLE
Half Screen

### ISSUE THREAD

**Issue by nsmith1024** [AppIntro/AppIntro#1138]
## ⚠️ Is your feature request related to a problem? Please describe

I have a split screen set up where at the bottom i have a map, at the top i want the horizontal swipe thing that you have.

Is it possible to use your component like this?

## 💡 Describe the solution you'd like

I have a split screen set up where at the bottom i have a map, at the top i want the horizontal swipe thing that you have.

Is it possible to use your component like this?

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [ X] No

**Comment by paolorotolo** [comment]
Hi! At the moment we support full activities only.
Could be a nice feature request to add an AppIntro fragment/view, if someone is interested :)
