### ISSUE TITLE
Request for alignment

### ISSUE THREAD

**Issue by joh9911** [AppIntro/AppIntro#1193]
## ⚠️ Is your feature request related to a problem? Please describe

Whenever I add the \n to a sentence, the description is always centered. 
Could you implement a feature that allows us to modify the alignment of the description?
## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [ x] No

**Comment by cortinico** [comment]
> Could you implement a feature that allows us to modify the alignment of the description?

You can provide your own layout
https://github.com/AppIntro/AppIntro#appintrocustomlayoutfragment

So there is no need for another property to change the alignment
