### ISSUE TITLE
Add My App Requests -- that's you, come in here~

### ISSUE THREAD

**Issue by avluis** [AppIntro/AppIntro#325]
### Would you like your app added to our application list?

Then reply with the following _[note the format]_:

_App Name_: Sample App
_Link_: https://play.google.com/store/apps/details?id=paolorotolo.github.com.appintroexample
## 

Replace the above url with **_your_** application link!!
Your Google Play listing must be publicly accessible -- please note in your comment if it is not!
## 

For those that want to know if I got your request; you'll find this 👍 when I see it, and then this 🎉 when it has been added by me~

**Please refrain from using 👍 or 🎉 on your own posts for this issue.**

**Comment by Andrew-Quebe** [comment]
Nice idea 👍

**Comment by mveroukis** [comment]
App name: Ampwifi
Link: https://play.google.com/store/apps/details?id=com.blitterhead.ampwifi

And I plan to use it on my next app too. :-)

**Comment by ranveeraggarwal** [comment]
*App Name:* AaiKya: Leave Tracker
*Link:* https://play.google.com/store/apps/details?id=com.ranveeraggarwal.letrack

Thanks for the amazing library 😄

**Comment by maravilhosinga** [comment]
App name: Angopapo
Link: https://play.google.com/store/apps/details?id=com.msingapro.angopapofb

**Comment by halilozercan** [comment]
_App name_: Hugetwit
_Link_: https://play.google.com/store/apps/details?id=com.halilibo.hugetwit

**Comment by dhruvil007** [comment]
App Name: Wake Me Up (Mumbai Railway)
Link: https://play.google.com/store/apps/details?id=com.catacomblabs.wakemeup

**Comment by anburocky3** [comment]
App Name: SelfMote (Wireless Remote App)
Link: https://play.google.com/store/apps/details?id=com.dmicse.selfmote.free

App Name: Boo Music Player 
Link: https://play.google.com/store/apps/details?id=cdn.BooPlayer

**Comment by peeveen** [comment]
App Name: BeatPrompter
Link: https://play.google.com/store/apps/details?id=com.stevenfrew.beatprompter

**Comment by biniamHaddish** [comment]
App Name: SwifDicty
Link: [https://play.google.com/store/apps/details?id=com.biniam.Haddish.swifDicty&hl=en](url)

**Comment by beatbrot** [comment]
App Name: Open GApps
Link: [https://play.google.com/store/apps/details?id=org.opengapps.app](url)

**Comment by fbarrosodev** [comment]
App Name: Snap Swipe Drawer
Link: play.google.com/store/apps/details?id=com.fb.iwidget

**Comment by coderearth42** [comment]
App Name: Geek Dictionary
Link: https://play.google.com/store/apps/details?id=in.coderearth.geekdictionary
Thank you so much for the awesome library 👍

**Comment by wendyliga** [comment]
app name : Deaf communicator

link : https://play.google.com/store/apps/details?id=com.wendyliga.deafcommunicator

thank you for your great library

**Comment by anthorlop** [comment]
App Name: Memowords
Link: https://play.google.com/store/apps/details?id=com.vocabulary.trainer.memory.words.languagestest.lite
Thank you

**Comment by ritdaw** [comment]
App Name: Project Pix
Link: https://play.google.com/store/apps/details?id=com.ritapps.projectpix

Awesome library!

**Comment by passiondroid** [comment]
App Name: New Movies
Link: https://play.google.com/store/apps/details?id=com.app.nmot

Nice Library

**Comment by peterhav** [comment]
App Name: Attendance Tracker Cloud
Link: [https://play.google.com/store/apps/details?id=com.petermanapps.atcloud]

**Comment by jackstern** [comment]
**App Name:** VidToast
**Link:** [https://play.google.com/store/apps/details?id=com.vidtoast](https://play.google.com/store/apps/details?id=com.vidtoast)

Thanks for the superb library. 👍🏻

**Comment by avluis** [comment]
@jackstern The 👍 are for our use sir -- at least on this issue.
It allows us to track what has been seen and added to the readme.
Using them here will only cause delay and confusion so please refrain for using them on your own posts.

**Comment by rausNT** [comment]
App Name: voice navigator "IGH"
Link: https://play.google.com/store/apps/details?id=com.raus.i_m_going_home_v2.lite
Thanks for the superb library

**Comment by AlxDroidDev** [comment]
App Name: **Camera Gear**
Link: https://play.google.com/store/apps/details?id=com.alxdroiddev.cameragear

Credits to the library have been given in the app.
Thanks for the easy-to-use library and keep up the great work.

**Comment by qijaz221** [comment]
App Name: Alpha Music Player
Link: https://play.google.com/store/apps/details?id=qijaz221.github.io.musicplayer

**Comment by federicoiosue** [comment]
App Name: Omni Notes
Link: https://play.google.com/store/apps/details?id=it.feio.android.omninotes

**Comment by aknkaplanoglu** [comment]
App Name: Griff - World News
Link: https://play.google.com/store/apps/details?id=tech.ozak.newsworld

**Comment by JaxonWright** [comment]
App Name: Pixbar
Link: https://play.google.com/store/apps/details?id=com.dunrite.pixbar

**Comment by valokafor** [comment]
App Name: Pronto Invoice
Link: https://play.google.com/store/apps/details?id=com.okasonsoftware.prontoinvoice

**Comment by valokafor** [comment]
App Name: Pronto Note
Link: https://play.google.com/store/apps/details?id=com.okason.prontonote

**Comment by mnarasimhan02** [comment]
App Name: WeSport
Link: https://play.google.com/store/apps/details?id=com.my.game.wesport

**Comment by Carnivora1** [comment]
App Name: Jelly Blocks and Diamonds
Link: https://play.google.com/store/apps/details?id=jon.brinkmann.blocks&hl

**Comment by mladenbabic** [comment]
App name: Delta Watch Face
Link: https://play.google.com/store/apps/details?id=com.watch.richface.delta&hl=en

**Comment by chnt-gomez** [comment]
App name: Go Sales
https://play.google.com/store/apps/details?id=com.go.kachin

**Comment by minas1** [comment]
App name: Movie Pal
Link: https://play.google.com/store/apps/details?id=greenbits.moviepal

**Comment by sadragro** [comment]
App name: **IEC**
Link: **https://play.google.com/store/apps/details?id=com.sme.mabna**

**Comment by artschie1337** [comment]
App Name: Asthma Plus
Link: https://play.google.com/store/apps/details?id=de.qurasoft.amsspiroapp

**Comment by maayyaannkk** [comment]
App Name: RadioDrive
Link: https://play.google.com/store/apps/details?id=in.mayanknagwanshi.radio

**Comment by nellorocca** [comment]
App Name: DSLR Tools
Link: https://play.google.com/store/apps/details?id=com.gmail.nellorocca.dslrtools

**Comment by albertogiunta** [comment]
App Name: 🇮🇹 Orario Treni Trenitalia
Link: [https://play.google.com/store/apps/details?id=com.jaus.albertogiunta.justintrain_oraritreni](https://play.google.com/store/apps/details?id=com.jaus.albertogiunta.justintrain_oraritreni)

**Comment by Randalg** [comment]
App Name - Find Me
Link:https://play.google.com/store/apps/details?id=com.martingyupchanov.findme

**Comment by mveroukis** [comment]
App Name: Virbeya
Link: [https://play.google.com/store/apps/details?id=com.imaginet.virbeya](https://play.google.com/store/apps/details?id=com.imaginet.virbeya)

**Comment by siddhantvinchurkar** [comment]
App Name: Marv
Link: https://play.google.com/store/apps/details?id=com.marv

**Comment by brarcher** [comment]
App Name: Rental Calc
Link: https://play.google.com/store/apps/details?id=protect.rentalcalc

Thanks for developing this library!

**Comment by GGLabCenter** [comment]
App Name: Health
Link: https://play.google.com/store/apps/details?id=gglab.health

**Comment by volnoor** [comment]
App Name: Base Calculator
Link: https://play.google.com/store/apps/details?id=com.volnoor.basecalculator

Thanks.

**Comment by Caggegi** [comment]
App Name: HistorymApp
Link: https://play.google.com/store/apps/details?id=it.zpgroupsnc.historymapp&hl=it

Thanks.

**Comment by RUSSCITY** [comment]
Hm... the last added app was about one Year before (8 Nov 2016)... but let's try ^^

AllTracker
https://play.google.com/store/apps/details?id=city.russ.alltrackerfamily

Btw. nice Lib, thanks for it.

**Comment by avluis** [comment]
@RUSSCITY Hey there -- I'm actually tracking this list, but I am looking for a better way to present these apps on the repo.

Any suggestions would be lovely 😻

**Comment by dream09** [comment]
Heart Trace
https://play.google.com/store/apps/details?id=com.magic09.magicheartraterecorder

Great library, thanks!

**Comment by AlxDroidDev** [comment]
@avluis A suggestion I have is to move all these apps to a Wiki page. 

Possibly they can be categorized, using the same categories of the Play Store. In this case, each developer, when announcing their app here, would also explicit the category in which they publish their app on the Play Store, so you don't have to go through the app to find out what it does. So we'd list our apps on this issue like this:

App Name: xxxxxx
Category:    zzzzzz
Play Store link:    wwwwwwwwwwwww

The Wiki page would be:

**Category Z**

and then a 2 column table with Name and Play Store link of the apps in that category.

**Comment by avluis** [comment]
@AlxDroidDev Great minds think alike ❤️
That is an idea I'm gonna be working on in a few days (need to migrate the apps here and on the readme) as time permits.

The greater plan is to present these apps on Github Pages eventually~

**Comment by AlxDroidDev** [comment]
@avluis thanks, buddy! Let me know if you need help.

**Comment by abicelis** [comment]
App Name: Chef Buddy
Link: https://play.google.com/store/apps/details?id=ve.com.abicelis.chefbuddy

Awesome library. Keep up the great work.

**Comment by pranjal-joshi** [comment]
App Name: MeetApp
Link: [https://play.google.com/store/apps/details?id=com.cyberfox.meetapp](url)

**Comment by marwendoukh** [comment]
App Name: Classroom chat
Link: https://play.google.com/store/apps/details?id=com.classroomchat.marwen.classroomchat

**Comment by enoler** [comment]
App Name: World Traveller
Link: https://play.google.com/store/apps/details?id=worldtraveller.enoler.es.worldtraveller

**Comment by IvanMazzoli** [comment]
App Name: Tipsy for Gardaland
Link: https://play.google.com/store/apps/details?id=com.MonkeyLab.MyGardaland&hl=it

Thank you Paolo and all you others guys maintaining this library!
Sidenote to Paolo: hope to see you at Codemotion at Milan in November!

**Comment by nicolabeghin** [comment]
App Name: WazzapMigrator
Link: https://play.google.com/store/apps/details?id=com.nbeghin.whatsappmigrator

Great library, thanks a lot!

**Comment by avluis** [comment]
_Moved_: https://github.com/apl-devs/AppIntro/issues/496
@djuelg

Hey there,

today I will release my note app Neuronizer to production on Google play.
As I decided to use your library it would be nice to be listed in the app section.
Here are the links:
https://github.com/djuelg/Neuronizer
https://play.google.com/store/apps/details?id=de.djuelg.neuronizer

Greets,
djuelg

**Comment by avluis** [comment]
@all -- Looking for PRs for the wiki to feature your apps -- if you have the time, please send them my way!

**Comment by PEDRO33** [comment]
App Name: Programmers
Link: https://play.google.com/store/apps/details?id=com.pedromassango.programmers

Your library is very good, please stay it alive.

**Comment by cdecron** [comment]
App Name: Zwyx
Link: https://play.google.com/store/apps/details?id=com.gm.zwyx

Thanks for your library!

**Comment by pedromassango** [comment]
App Name: Sample App
Link: https://play.google.com/store/apps/details?id=com.pedromassango.programmers

**Comment by nisd93** [comment]
App Name: Quick Synonyms
Link: https://play.google.com/store/apps/details?id=com.nisdapps.myfirstapp

**Comment by pedromassango** [comment]
It is not my app

2017-11-27 8:39 GMT+01:00 Nisarg <notifications@github.com>:

**Comment by markus-woerz** [comment]
App Name: QRbot: QR code reader and barcode reader
Link: https://play.google.com/store/apps/details?id=net.qrbot

**Comment by markus-woerz** [comment]
App Name: QR & Barcode Scanner
Link: https://play.google.com/store/apps/details?id=com.teacapps.barcodescanner

**Comment by saideepbollam** [comment]
App Name: Play-Code
Link: https://play.google.com/store/apps/details?id=www.play_code.xyz.myapplication

Thank you for the library!

**Comment by Mendes11** [comment]
App Name: Price My Print
Link: https://play.google.com/store/apps/details?id=br.com.cozinheirodelivery.pricemyprint

**Comment by abicelis** [comment]
I got one!

App Name: Chef Buddy
Link: https://play.google.com/store/apps/details?id=ve.com.abicelis.chefbuddy

Awesome work!

**Comment by stevebaros** [comment]
App Name : Emoji Dictionary
Link : https://play.google.com/store/apps/details?id=com.hamsoftug.emojiDictionary

**Comment by V1rex** [comment]
App Name : eHope
Link : https://github.com/V1rex/eHope
Thanks for the library :+1: :+1:

**Comment by minas1** [comment]
App name: Movie Pal
Link: https://play.google.com/store/apps/details?id=greenbits.moviepal

**Comment by AlexJuca** [comment]
App Name: Kamba
Link: https://play.google.com/store/apps/details?id=com.usekamba.kamba.kamba

**Comment by mueller-ma** [comment]
App Name: openHAB
Link: https://play.google.com/store/apps/details?id=org.openhab.habdroid

**Comment by Hugsoft** [comment]
App name: iGestures
Link: https://play.google.com/store/apps/details?id=in.hugsoft.igesture

And I plan to use it on my another applications too. :-)

**Comment by Hugsoft** [comment]
App name: Swipe Volume Controller
Link: https://play.google.com/store/apps/details?id=in.hugsoft.swipevolumecontroller

Thanks

**Comment by hitanshu-dhawan** [comment]
App Name: PopCorn
Link: https://play.google.com/store/apps/details?id=com.hitanshudhawan.popcorn

**Comment by nicolabeghin** [comment]
App Name: WazzapMigrator
Link: https://play.google.com/store/apps/details?id=com.nbeghin.whatsappmigrator

Great library, thanks a lot!

**Comment by aamirki** [comment]
App Name: Mappium Map Maker
Link: https://play.google.com/store/apps/details?id=com.aamirki.mappium

Thanks for the great library!

**Comment by drishit96** [comment]
App Name: Pollscape - Poll in real-time
Link: https://play.google.com/store/apps/details?id=com.app.pollscape.release

Thanks for the awesome library!

**Comment by francescogatto** [comment]
App Name: TabuDroid
Link: https://play.google.com/store/apps/details?id=net.francescogatto.tabudroid

Thanks a lot for your work!

**Comment by Merthan** [comment]
App Name: The Launcher
Link: https://play.google.com/store/apps/details?id=com.gmail.ME2Development.TheLauncher

Thank you so much!

**Comment by venkatselva8** [comment]
App Name: JobHub (search software jobs)
Link: https://play.google.com/store/apps/details?id=com.venkyapps.githubjobs

Thanks for the great library. Keep up the good work.

**Comment by julenuem** [comment]
App Name: Cleanse
Link: https://play.google.com/store/apps/details?id=com.cleanseproject.cleanse

Thank you!

**Comment by federicoiosue** [comment]
App Name: Omni Notes
Link: https://play.google.com/store/apps/details?id=it.feio.android.omninotes

Ottimo Paolo

**Comment by KaiserFrederick** [comment]
App Name: Hitos
Link: https://play.google.com/store/apps/details?id=com.ministeriopalmoni.hitos

Thanks a lot for this work, it is great!!!

**Comment by AnuthaDev** [comment]
Hey @cortinico Could you please pin this issue, so that it is visible more prominently then being restricted to the second page of issues

**Comment by cortinico** [comment]
Hey @AnuthaDev 
I was actually thinking about deprecating the section in the README as it gets pretty long. Moreover I'll try to convince people to open PR to maybe a separate Markdown file or to a section in the Wiki.

**Comment by MohammadSommakia** [comment]
App Name: Hitos
Link: https://play.google.com/store/apps/details?id=net.healthintouch.hit&hl=en

Thanks a lot for this work, it is great!!!

**Comment by nageamol** [comment]
App Name : Backup and Restore - App, Contacts, Sms , Calllogs
https://play.google.com/store/apps/details?id=com.primol.appbackup
Thanks for this awesome lib.

**Comment by gcantoni** [comment]
App Name: My Wall - Wallpaper Saver & Blur
Link: https://play.google.com/store/apps/details?id=it.folgore95.mywall

Thank you!

**Comment by JagadishaIncture** [comment]
App Name :  LoverBoy TARUN
link: https://play.google.com/store/apps/details?id=com.tarun.jagadish.loverboytarun&hl=fa

Thankyou

**Comment by pratikbutani** [comment]
App Name: Best Quotes & Status 2019 (99000+ Collection)
Link: https://play.google.com/store/apps/details?id=com.swastik.quotesandstatus&hl=en_IN

Thanks for this awesome library.

**Comment by YoSSeF-M** [comment]
App Name : Tasked
Link : https://play.google.com/store/apps/details?id=com.yquery.to_doproject

**Comment by nickstamp93** [comment]
App Name : PA Keno - Pennsylvania Keno Lottery Results
Link : [https://play.google.com/store/apps/details?id=com.nickstamp.paKeno&hl=en](https://play.google.com/store/apps/details?id=com.nickstamp.paKeno&hl=en)

Thanks for this excellent library

**Comment by void0629** [comment]
App Name: Got a plan?
Link: https://play.google.com/store/apps/details?id=com.racoondog.gotaplan

**Comment by bitmold** [comment]
App Name: Orbot 
Link: https://play.google.com/store/apps/details?id=org.torproject.android

**Comment by cortinico** [comment]
Closing here given that now we have a sticky issue asking participants to directly open a PR for the README: #784

If your Application is not listed in the README, feel free to open a Pull Request. We will get it merged ASAP.
