### ISSUE TITLE
R.id.back not resolved in AppIntroBase.java

### ISSUE THREAD

**Issue by KohlsAdrian** [AppIntro/AppIntro#400]
java.lang.NoSuchFieldError: com.github.paolorotolo.appintro.R$id.back
                                                     at com.github.paolorotolo.appintro.AppIntroBase.onCreate(AppIntroBase.java:86)

![image](https://cloud.githubusercontent.com/assets/6604704/22065630/4bd86932-dd70-11e6-92f0-acd763504efa.png)

AppIntro Version 4.10

My devices: Nexus 5X 7.1.1 and Galaxy Tab E 4.4.4

The project compile, only crashes in runtime

And the error happend before my own code, happens at super.onCreate class method
![image](https://cloud.githubusercontent.com/assets/6604704/22065732/b0adae9e-dd70-11e6-8ba0-2b652a374a9f.png)

EDIT1:
My gradle
![image](https://cloud.githubusercontent.com/assets/6604704/22065790/eb7d5fe2-dd70-11e6-8744-1240d96a3a1e.png)

**Comment by Andrew-Quebe** [comment]
Hmm...strange. Let me mess around a bit and I'll get back to you. Thanks for the detailed issue.

**Comment by KohlsAdrian** [comment]
I think is something with the layouts that doesn't have the ids declaration on XML, or you might removed and let the code there, because the 4 layouts that came in gradle download dind't had those declarations in layout. I  think that must be a easy solution, if I download the zip from release, they work, but directly from gradle must be something missing

**Comment by Anutha02** [comment]
@paolorotolo This issue is not there anymore. Can be closed for inactivity
