### ISSUE TITLE
Policy how to be added to where

### ISSUE THREAD

**Issue by dipnaze32** [AppIntro/AppIntro#425]
public final class MySlide extends Fragment implements ISlidePolicy {
    @Override
    public boolean isPolicyRespected() {
        return // If user should be allowed to leave this slide
    }

    @Override
    public void onUserIllegallyRequestedNextPage() {
        // User illegally requested next slide
    }
}

May I know where is this attached to to do policy

**Comment by Anutha02** [comment]
@cortinico Should be closed as unclear

**Comment by AnuthaDev** [comment]
@cortinico Please close this issue.
