### ISSUE TITLE
Error adding a slide

### ISSUE THREAD

**Issue by forerser** [AppIntro/AppIntro#447]
I've problem adding a slide in IntroActivity

![image](https://user-images.githubusercontent.com/29029407/27015935-c62549d8-4ee7-11e7-8311-94b37beba6ef.png)

**Comment by avluis** [comment]
If you are using our `SampleSlide` class, then you need to make certain that you are extending `Fragment` from the v4 library.
Your code snippet above is not showing enough code to be able to make certain of that (you aren't showing your imports nor the `SampleSlide` code).

**Comment by Anutha02** [comment]
@paolorotolo This issue can be closed for inactivity

**Comment by cortinico** [comment]
Wow also funny to see the old Eclipse interface there xD
