### ISSUE TITLE
How could I access to the different items (for example an ImageView) inside of the slides?

### ISSUE THREAD

**Issue by jkydevelopment** [AppIntro/AppIntro#453]
I tried with 
getPager().findViewById(R.id.myImage); 
or 
getSlides().get(i).getView().findViewById(R.id.myImage); 

I am not able to find the way to access them, and I need to implement different items dynamically.
Thanks in advance and congratulations for your work! :)

**Comment by avluis** [comment]
If you need to modify a layout dynamically, may I suggest creating your own slides and then referencing your IDs. This would be a cleaner solution (IMO).

As for how to target the library IDs, I haven't tried before so this will be a shot in the dark -- have you tried getting an instance of the fragment and moving from there?

**Comment by jkydevelopment** [comment]
I tried but I didn't know how to do it correctly... It's not so easy as could seems, at least for me. Could you please help me with this?
Thank you!!

**Comment by raphasle** [comment]
I was able to perform programmatically a "next click" by calling
((ViewGroup) getSlides().get(5).getView().getParent().getParent()).findViewById(R.id.next).performClick();
However, this looks awful and is most likely not the right way to do this, but maybe it helps you.

**Comment by cortinico** [comment]
I don't know if this is still relevant, but you should be able to create a custom Fragment similar to the `AppIntroCustomLayoutFragment` and access the view hierarchy over there:
https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/java/com/github/appintro/AppIntroCustomLayoutFragment.kt
