### ISSUE TITLE
Change Drawable and text position

### ISSUE THREAD

**Issue by deka91** [AppIntro/AppIntro#470]
I'm using the AppIntro in the landscape mode and want the text on the left side and the Drawable on the right. So there will be more space for longer texts.

So is it possible to change the drawable and text position?

**Comment by avluis** [comment]
There are no built-in methods to manipulate slide widgets (other than what Android provides).

You could get a hold of each element and set their position from code, but for this I would recommend making use of custom slides that implement `AppIntro` along with the relative xml layout for fine grained control (let's say you want text to be centered on a smartphone while they offset on tablet devices).

Here is the [`SampleSlide`](https://github.com/apl-devs/AppIntro/blob/master/example/src/main/java/com/amqtech/opensource/appintroexample/util/SampleSlide.java) (can be used as-is) for use in the [`addSlide`](https://github.com/apl-devs/AppIntro/blob/master/example/src/main/java/com/amqtech/opensource/appintroexample/ui/mainTabs/intro/CustomLayoutIntro.java#L21) method.
For the layout itself, [this](https://github.com/apl-devs/AppIntro/blob/master/example/src/main/res/layout/intro_custom_layout1.xml) shows you just that.

Now -- if you don't wish to implement the above (if only one of your slides needs to be tweaked at runtime) then;

* Figure out which slide needs to be manipulated and save a static reference to it:
`private static final int IMPORT_SLIDE = 4;`
* Make use of a conditional in the `onSlideChanged` method to figure out if we are on our slide:
`if (pager.getCurrentItem() == IMPORT_SLIDE) {...}`
* Reference your widgets as per usual (check the library xml files if you are using built-in slides):
`TextView defaultTv = (TextView) findViewById(R.id.some_textview);`

Once you have your reference, `defaultTv` in the example above, you can manipulate that as usual.

**Comment by deka91** [comment]
Thank you for your reply!
I tried it within onSlideChanged but I don't understand how do get the id of the TextView. I'm using the built-in slides and therefore I'm not setting any layout with my own TextViews.

**Comment by Anutha02** [comment]
@paolorotolo Fixed by #647 Now we have a separate landscape layout
