### ISSUE TITLE
How to auto scroll the appIntro and stop when the user touch it ?

### ISSUE THREAD

**Issue by EssenKh** [AppIntro/AppIntro#474]
Please can't find auto scrolling first. Then how can i stop auto scrolling whenthe user touch a slide.
Best Regards

**Comment by yeshuinfrrd** [comment]
The resourceId of the next arrow is _next_. It is a ImageButton. Find it by id in your tutorial activity and use it for auto scrolling.

**Comment by moelle89** [comment]
U can use this for gotToNextSlide - it will behave just like if u click on the next button:

    private void next() {
        pager = findViewById(R.id.view_pager);
        pager.goToNextSlide();
    }

**Comment by cortinico** [comment]
Closing as this got solved.
Moreover you probably want to use another widget for your usecase like this one: https://github.com/yarolegovich/DiscreteScrollView ?
