### ISSUE TITLE
Make your sample app available worldwide

### ISSUE THREAD

**Issue by LouisCAD** [AppIntro/AppIntro#484]
Please, no more geolock. Your sample app on Google Play should be available in all countries that can access Google Play.

**Comment by hnilsen** [comment]
Agreed. Must be a glitch.

**Comment by andreynovikov** [comment]
Same for Russia

**Comment by Anutha02** [comment]
@cortinico Can you add this to the Triage pls

**Comment by cortinico** [comment]
Closing as the sample app has been reworked and is not on Play Store at the moment.
