### ISSUE TITLE
Dynamically changing the next slide

### ISSUE THREAD

**Issue by abhinavkh** [AppIntro/AppIntro#502]
**AppIntro Version**: 4.2.2

**Issue details / Repro steps / Use case background**: Feature support / request

Is there a way for me to modify the layout of the next slide according to the data entered in the previous slide?

Enter email (Slide 1) ---- (email does not exist in Database) -----> Slide 2 (layout 1)
                                |----- (email exists in Database)--------------> Slide 2 (layout 2)

**Comment by Anutha02** [comment]
You should use custom fragments for this
