### ISSUE TITLE
Do not show position dot if there is only one slide

### ISSUE THREAD

**Issue by andreynovikov** [AppIntro/AppIntro#504]
I'm constructing slide queue dynamically based on various conditions. It may be a situation when there is only one slide available to user. In that case a dot (position indicator) is superfluous. I propose to make it not visible in that case.

**Comment by SunshineNumber1** [comment]
have you resovel this question? i have the same situation for fix;

**Comment by SunshineNumber1** [comment]
try this:
setIndicatorColor(Color.parseColor("#00000000"),Color.parseColor("#00000000"));

**Comment by cortinico** [comment]
Closed by #876
