### ISSUE TITLE
Bug in isPolicyRespected (?)

### ISSUE THREAD

**Issue by mundoramos** [AppIntro/AppIntro#505]
**AppIntro Version**: 4.1.0

**Device/Android Version**: Nexus 5X

**Issue details / Repro steps / Use case background**: 
I'm using the slides to make a SignUp, so I have a couple of EditText that I don't want the user to skip them, so I use a validation on the isPolicyRespected(), the problem is that everytime I make a click on the view that validation shows up (even not trying to pass to the next/previous slide), so even it's just for selecting an EditText to fill up my validation is already displaying, is it normal that isPolicyRespected launches everytime even just onClick (?), thanks!

**Your Code**: 
`
@Override
    public boolean isPolicyRespected() {`
        `if (validationSucceeded){`
`            validationSucceeded = false;`
`            return true;`
`        } else {`
`            validation();          //This shows the errors in Toasts`
`        }`
`        return validationSucceeded;
    }`

**Comment by cortinico** [comment]
I'm closing this as it's stale and `isPolicyRespected` has been completely revamped recently. Feel free to reopen or post a new issue if you still have problems.
