### ISSUE TITLE
Extend Fragment instead Activity

### ISSUE THREAD

**Issue by albo1337** [AppIntro/AppIntro#510]
Hey,
first thank you very much for your great library. I want to use your library but I'm working in a project with a single Activity and I don't want to change my architecture. Is there a way to extend support.Fragment instead of Activity?

Would be great if this will work.

Best regards,
Albo

**Comment by Anutha02** [comment]
There aren't any plans regarding this. Also the intro part is best left separated in its own activity.

**Comment by AnuthaDev** [comment]
@cortinico I think this issue should be closed.
