### ISSUE TITLE
Adding tag or id to fragment

### ISSUE THREAD

**Issue by buelersandra** [AppIntro/AppIntro#513]
I added a custom fragment among other slides. when  
`@Override
    public void onSlideChanged(
@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
if(newFragment is....)
{
 // Do something when the slide changes.
}
        } `
is called i want to check if the custom fragment is the one.

**Comment by Anutha02** [comment]
You can do this using the instanceof operator to check if the old fragment or the new fragment is the instance of your fragment.

**Comment by Anutha02** [comment]
@paolorotolo Can be closed

**Comment by paolorotolo** [comment]
Thanks.
