### ISSUE TITLE
status bar shows default color 

### ISSUE THREAD

**Issue by ghost** [AppIntro/AppIntro#530]
I'm using a constraint layout to design my layout as follows 

    <?xml version="1.0" encoding="utf-8"?>
    <android.support.constraint.ConstraintLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/constraint_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/intro_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="24dp"
        android:textColor="@android:color/white"
        android:textSize="28sp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <ImageView
        android:id="@+id/intro_image"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:padding="30dp"
        app:layout_constraintBottom_toTopOf="@+id/intro_desc"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/intro_title"
        />

    <TextView
        android:id="@+id/intro_desc"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:gravity="center_horizontal"
        android:padding="10dp"
        android:textColor="@android:color/white"
        android:textSize="16sp"
        app:layout_constraintBottom_toTopOf="@+id/guideline"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

    <android.support.constraint.Guideline
        android:id="@+id/guideline"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="60dp"
        android:orientation="horizontal"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintGuide_end="52dp" />

    </android.support.constraint.ConstraintLayout>

And my IntroFragment page is as follows : 

    @BindView(R.id.intro_title)
    TextView title;

    @BindView(R.id.intro_desc)
    TextView description;

    @BindView(R.id.intro_image)
    ImageView image;

    @BindView(R.id.constraint_layout)
    ConstraintLayout background;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.layout_intro_slide, container, false);
        ButterKnife.bind(this, view);
        return view;
    }

My issue is that the status bar has `colorPrimaryDark` value even if my OS version is Nougat?

**Comment by hamsoft-uganda** [comment]
Any solution to this?? How did you solve it??

**Comment by Shouheng88** [comment]
I used to use AppIntro in my project, you may refer to my project: [MarkNote](https://github.com/Shouheng88/MarkNote). 
I add one activity which extends AppIntro2 and added some customed fragments. 
You use the dependence below:
`'com.github.paolorotolo:appintro:1.3.0'`
which seems to be the older version of thie project.

**Comment by SaathwikS** [comment]
Thank u

**Comment by Anutha02** [comment]
@cortinico This issue is invalid .To change the statusbar color we can just define it in our theme file . And after #647 we can also extend AppIntroStyle and override the color values easily.

**Comment by cortinico** [comment]
Yup right @Anutha02
