### ISSUE TITLE
Skip to last slide

### ISSUE THREAD

**Issue by uzuki-P** [AppIntro/AppIntro#531]
**AppIntro Version**:4.2.3

**Device/Android Version**:Redmi 4 Prime (markw)

How to skip to last slide or any other slide?

**Comment by agueroveraalvaro** [comment]
Solved! : On the onSkipPressed method you can do : 

`while (getPager().getCurrentItem()!=sliderCount)
            pager.goToNextSlide();`

**Comment by cortinico** [comment]
Unfortunately we don't have a public method for that @uzuki-P 
You can still progress the viewPager manually:

```java
AppIntroViewPager pager = findViewById(R.id.view_pager);
pager.setCurrentItem(...);
```
