### ISSUE TITLE
Special permission: Overlay

### ISSUE THREAD

**Issue by WuerfelDev** [AppIntro/AppIntro#536]
**AppIntro Version**: 4.2.3

**Device/Android Version**: All,probably. I'm on Nougat

**Issue details / Repro steps / Use case background**: There is a special way to allow overlays. Even that there is `SYSTEM_ALERT_WINDOW` this does not produce a dialog. To let the user set this permission I'd love to see a fix for this. Here's how to let the user enable it: https://stackoverflow.com/a/34061521/4346956

**Your Code**: `askForPermissions(new String[]{Manifest.permission.SYSTEM_ALERT_WINDOW}, 2);`

**Stack trace / LogCat**: Nothing

**Comment by AnuthaDev** [comment]
@cortinico I think it is out of scope for this library. It can be achieved by using custom fragments, so I think this issue should be closed.
