### ISSUE TITLE
setColorDoneText() is missing?

### ISSUE THREAD

**Issue by anta40** [AppIntro/AppIntro#539]
AppIntro version: 4.2.3

I found these methods:
```
setColorDoneText();
setNextArrowColor();
```

Yes, the work correctly. But I cannot found.. hmm... `setColorSkipText()`.
For the sake of completeness, I think it would be nice to have that method available as well :)

**Comment by TomTasche** [comment]
I think it's just named inconsistently, take a look at setColorSkipButton

**Comment by cortinico** [comment]
> I think it's just named inconsistently, take a look at setColorSkipButton

Yup we should probably fix this as is bad. Since I'm going to touch those files with the Kotlin migration, I could probably unify the naming a bit.

**Comment by Anutha02** [comment]
@cortinico This issue has been fixed. Should be closed
