### ISSUE TITLE
Readme Sample is partially deprecated

### ISSUE THREAD

**Issue by cortinico** [AppIntro/AppIntro#545]
I was trying the library and I noticed that the first example in the `README.md` file contains deprecated code.

I'm talking about this section:

```java
public class IntroActivity extends AppIntro {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

[...]

        // Instead of fragments, you can also use our default slide
        // Just set a title, description, background and image. AppIntro will do the rest.
        addSlide(AppIntroFragment.newInstance(title, description, image, backgroundColor));
```

The `AppIntroFragment.newInstance` method is deprecated [here](https://github.com/apl-devs/AppIntro/blob/master/library/src/main/java/com/github/paolorotolo/appintro/AppIntroFragment.java#L14)
Maybe that should be replaced with the `newInstance(SliderPage sliderPage)` variant?

**Comment by AmiroEmad** [comment]
I have same issue what should I do to be able to use the library ??

**Comment by AmiroEmad** [comment]
Thank you . Your issue helped me . I went and checked the code and found the solution to my problem . Thank you so much . @cortinico

**Comment by cortinico** [comment]
You're welcome :)

**Comment by cortinico** [comment]
Closing as this is going in 6.0.0
