### ISSUE TITLE
Bug in isRtl method.

### ISSUE THREAD

**Issue by isabsent** [AppIntro/AppIntro#547]
You have to use this definition for **RTL**:

    public static boolean isRtl() {//https://stackoverflow.com/a/37101995/753575
        Locale locale = Locale.getDefault();
        final int directionality = Character.getDirectionality(locale.getDisplayName().charAt(0));
        return directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT ||
                directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC;
    }
instead of your because `android:supportsRtl="true"` in the manifest does not mean user's device runs in **RTL** mode. It only means you are supporting **RTL** in your app.

**Comment by Anutha02** [comment]
@cortinico Our library correctly detects RTL. This issue is invalid. Please close

**Comment by AnuthaDev** [comment]
@cortinico Please close this
