### ISSUE TITLE
unable merge dex

### ISSUE THREAD

**Issue by xiaochao** [AppIntro/AppIntro#552]
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    compile 'uk.co.chrisjenx:calligraphy:2.3.0'
    compile 'com.ashokvarma.android:bottom-navigation-bar:2.0.4'
    compile "com.android.support:support-core-utils:26.0.0"
    compile "com.android.support:recyclerview-v7:26.1.0"
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'cn.bingoogolapple:bga-qrcode-zxing:1.2.5'
    compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-11'
    compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-alpha-11'
    compile 'com.thefinestartist:finestwebview:1.2.7'
    compile files('libs/GetuiSDK2.12.4.0.jar')
    implementation 'com.github.apl-devs:appintro:v4.2.3'
}

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by cortinico** [comment]
hey @xiaochao 

Can you try to enable multidex in your app?
```
android {
      defaultConfig {
        ...
        multiDexEnabled true
      }
}
```

Also please:
* Try to disable/enable instant run
* Try to clean the project and rebuild

**Comment by Anutha02** [comment]
@cortinico Can be closed for inactivity
