### ISSUE TITLE
Rewrite Sample app

### ISSUE THREAD

**Issue by paolorotolo** [AppIntro/AppIntro#563]
It would be nice to rewrite the [sample app](https://play.google.com/store/apps/details?id=com.amqtech.opensource.appintroexample) with updated examples and maybe in kotlin.

I'm opening this issue to track the progress.

**Comment by cortinico** [comment]
I'm adding the `good first issue` as this is a simple task where new contributors could start to work on.

**Comment by cortinico** [comment]
Should we close this @paolorotolo and slowly add other samples to the app as soon as we receive quetsions?

**Comment by paolorotolo** [comment]
Sure!
