### ISSUE TITLE
Animations is too fast

### ISSUE THREAD

**Issue by mrb0098** [AppIntro/AppIntro#567]
**AppIntro Version**:
4.2.3

**Device/Android Version**:
Galaxy Note 3 & Android Emulator API 27

**Issue details / Repro steps / Use case background**: 
when i use this lib animations or use [this link](https://github.com/daimajia/AndroidViewAnimations) animations duration too fast

**Your Code**: 
 protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SharedPreferences prefs = getSharedPreferences("prefs", MODE_PRIVATE);
        Boolean firstuse = prefs.getBoolean("first" , true);
        if (!firstuse)
        {
            Intent intent = new Intent(this, MainActivity.class); // Call the AppIntro java class
            startActivity(intent);
        }
        else
        {
            //
            addSlide(new FragmentStartOne());
            addSlide(new FragmentStartTwo());
            //
            showStatusBar(true);
            //
            showSkipButton(false);
            setProgressButtonEnabled(true);
            //
            setSlideOverAnimation();
        }

    }

**Comment by cortinico** [comment]
@mrb0098 Can you be a bit more specific? Which animations are too fast?

**Comment by mrb0098** [comment]
@cortinico 
`setSlideOverAnimation();`
and
shake animation ([i used from this lib](https://github.com/daimajia/AndroidViewAnimations))
it is a surprise that i used some animations in another activity and they run so fast!!!
(Note : i checked animation scale setting in developer options in my phone and other apps run correct)

**Comment by Javinator9889** [comment]
Hi @mrb0098 

Have you tried changing the *ScrollDurationFactor*? Please, refer to this for more information at `AppIntroBase` (and classes that inherit from it)
```java
/**
* Sets the scroll duration factor - by default it is 1. This factor will multiply duration
* @param factor the new factor that will be applied to the scroll - default: 1
*/
protected void setScrollDurationFactor(int factor) {
        pager.setScrollDurationFactor(factor);
}
```

**Comment by Anutha02** [comment]
This problem has been answered. @paolorotolo please close
