### ISSUE TITLE
i find two bugs (may be)

### ISSUE THREAD

**Issue by mrb0098** [AppIntro/AppIntro#571]
**AppIntro Version**:
4.2.3

**Device/Android Version**:
Galaxy Note 3 & Android Emulator API 27

**Issue details / Repro steps / Use case background**: 
1.
when AppIntro activity started i rotate my phone (use landscape mode) and AppIntro activity is finished and Main Activity Started !!!
2.
in phones that have persian language (rtl mode) AppIntro screen is not work correct

**Comment by cortinico** [comment]
Hey @mrb0098 
Maybe is better if you open to separate issues?

BTW:

Issue 1: I wasn't able to reproduce.
Issue 2: Can you provide a screenshot?

**Comment by Anutha02** [comment]
This issue is invalid can be closed @paolorotolo

**Comment by paolorotolo** [comment]
RTL should be fixed with latest changes. Please feel free to reopen if you still have issues.
