### ISSUE TITLE
make status bar transparent

### ISSUE THREAD

**Issue by mianaliasjad** [AppIntro/AppIntro#575]
status bar by default showing black color I did everything 

<style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor">@android:color/transparent</item>

    </style>

and programmatically 
 if (android.os.Build.VERSION.SDK_INT >= 19) {
            getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
        }

but status bar color is showing black

**Comment by kilicpl** [comment]
Hi mianaliasjad .You can easily hide status bar in your activity by putting
         getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, 
         WindowManager.LayoutParams.FLAG_FULLSCREEN);

in your onCreate() of your activity, right after  super.onCreate(savedInstanceState).
But it totally hides statusbar, maybe that can be useful for you. cheers

**Comment by mianaliasjad** [comment]
@kilicpl  i don't want to hide the status bar i want to make its color transparent to hide status bar there is a method in this lib but i want to make it transparent

**Comment by yaminy** [comment]
hi . you can use this code on your onCreate 
getWindow().setFlags(
                WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
                WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS
        );

**Comment by TomTasche** [comment]
I fixed this by using a custom theme and setting the color. Doesn't work well on old devices though. See here for more: https://blog.tomtasche.at/2018/11/designing-good-on-boarding-experience.html

**Comment by JavaCafe01** [comment]
If you want to get rid of the status bar just use `showStatusBar(false);`

**Comment by Anutha02** [comment]
Fixed by #647 . If you want to set any color, just extend AppIntroStyle
