### ISSUE TITLE
bottom navigation view overlapping with fragment view

### ISSUE THREAD

**Issue by mianaliasjad** [AppIntro/AppIntro#576]
if i have some ui components in fragment at the bottom its overlapping with bottom navigation how to prevent that or i have to put static margin from the bottom?

**Comment by alirezat66** [comment]
@mianaliasjad did you find any solution to solve this problem or not? why anyone dont reply your question? I have same problem.

**Comment by cortinico** [comment]
Can you provide a screen shot @alirezat66 ?

**Comment by mianaliasjad** [comment]
@alirezat66 i did not find any solution. So i did bot used this library instead i created my own with ViewPager.

**Comment by alirezat66** [comment]
yes of course , i send u two scree from my design and my output 
<img width="302" alt="screen shot 2019-02-22 at 8 58 01 pm" src="https://user-images.githubusercontent.com/6933305/53259673-e5f51b80-36e4-11e9-948a-735c3de024f9.png">
<img width="386" alt="screen shot 2019-02-22 at 8 58 19 pm" src="https://user-images.githubusercontent.com/6933305/53259685-eee5ed00-36e4-11e9-84b9-3852763ce762.png">

**Comment by alirezat66** [comment]
I found your problem , your container in your  view  :

**Comment by alirezat66** [comment]
https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/res/layout/appintro_intro_layout.xml 
in <com.github.paolorotolo.appintro.AppIntroViewPager
line 9 u shoud set above: "@id/bottom"

**Comment by alirezat66** [comment]
@cortinico

**Comment by cortinico** [comment]
Fix is forthcoming #641 :)
