### ISSUE TITLE
Screen does not fit

### ISSUE THREAD

**Issue by mstburak** [AppIntro/AppIntro#578]
I used this library in my application. But there is an important bug. In some devices, next buttons and progress do not seems. Here is the example:
![ss](https://user-images.githubusercontent.com/25405224/46004283-27908480-c0bb-11e8-9043-54f0c526bef5.png)

**Comment by Anutha02** [comment]
@cortinico This should Be Fixed By #647

**Comment by paolorotolo** [comment]
#647 has been merged, I'm closing this.
