### ISSUE TITLE
New naming in Jitpack breaks version checks

### ISSUE THREAD

**Issue by frmz** [AppIntro/AppIntro#621]
New naming in Jitpack uses a leading "v", this breaks "ben manes" gradle version plugin, realted issue is the following: https://github.com/ben-manes/gradle-versions-plugin/issues/277

Plugin now shows:

```
 - com.github.paolorotolo:appintro [v4.2.3 -> 4.1.0]
     https://github.com/PaoloRotolo/AppIntro
```

So it thinks that 4.2.3 is a lower release than 4.1.0
Is it possible to go back to old naming?

**Comment by cortinico** [comment]
I think we should be fine with pushing new tags that copy the old one.
From my point of view we should be fine pushing those tags:

```
5.1.0 -> v5.1.0 (09d0dbe
5.0.1 -> v5.0.1  (72eb95d)
5.0.0 -> v5.0.0 (cb7ae27)
4.2.3 -> v4.2.3 (2ddeba7)
```

And from the upcoming version on let's use only the name without a `v`

**Comment by cortinico** [comment]
Hey @frmz 
I've just pushed this tags to AppIntro:

```
5.1.0 -> v5.1.0 (09d0dbe
5.0.1 -> v5.0.1  (72eb95d)
5.0.0 -> v5.0.0 (cb7ae27)
4.2.3 -> v4.2.3 (2ddeba7)
```

I'm going to update the README to point developers to use the version without the `v`.
Previous tags are kept for backward compatibility.

**Comment by paolorotolo** [comment]
Fix merged in master
