### ISSUE TITLE
Add a back arrow button ?

### ISSUE THREAD

**Issue by ajonno** [AppIntro/AppIntro#622]
**AppIntro Version**:  4.2.3

hi there, thanks for the great lib. Is it possible to optionally add a "back" arrow button, so the user can move backwards by tapping on it (as opposed to using the Android back button) ?

**Comment by Anutha02** [comment]
@cortinico, Actually we can easily achieve this by setting wizard mode to true. So this isn't an issue.

**Comment by cortinico** [comment]
@Anutha02 Correct.

So @ajonno you can achieve this behavior by setting `wizardMode` to true.
Example:

```
public class DefaultIntro extends AppIntro {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setWizardMode(true);

        // Setup appIntro here...
```
