### ISSUE TITLE
Change navigation bar and status bar colour

### ISSUE THREAD

**Issue by Anutha02** [AppIntro/AppIntro#640]
**AppIntro Version**:5.1.0

**Issue details / Repro steps / Use case background**: Is there a way to change the navigation and status bar colour (custom colour for each slide) or making them transparent/translucent?If yes, please guide me on how to do it, If not would it be possible to implement it?

**Comment by cortinico** [comment]
Hey @Anutha02 
You can change the color of the navigation/status bar directly from your theme. 
You can find an example here: https://stackoverflow.com/questions/27839105/android-lollipop-change-navigation-bar-color

Like if you add this:
```
<item name="android:navigationBarColor">#E91E63</item>
```
to your theme you will have something like:
![Imgur](https://i.imgur.com/oaWU3OW.png)

**Comment by Anutha02** [comment]
Alright. Thanks.
