### ISSUE TITLE
[Suggestion] Flatten Layout hierarchy by using constraintlayout

### ISSUE THREAD

**Issue by Anutha02** [AppIntro/AppIntro#643]
**Issue details / Repro steps / Use case background**: Do you think it would be better if we use constraintlayout in appintro_intro_layout 1 and 2? That way we might gain some performance. But then we would have a dependency on constraintlayout... If you agree I will submit a PR with the required changes, so let me know what you think.

**Comment by cortinico** [comment]
That's a good idea :)

> That way we might gain some performance

I think that the performance gain/impact here is really minimal.
I'd rather point out that this will cleanup the code a bit and modernize the layout generally.

> But then we would have a dependency on constraintlayout

Not a major problem as ConstraintLayout starts to be widely used, so we won't impact the user of the library so much.

**Comment by Anutha02** [comment]
Okay, I am on it.

**Comment by Anutha02** [comment]
Hey @cortinico @paolorotolo I am also rewriting the sample app, so should I change it from com.amqtech.appintroexample to com.github.paolorotolo.appintroexample or not?

**Comment by Anutha02** [comment]
I am done with layout2. Will be submitting PR tonight by 9pm (Indian Time)

**Comment by Anutha02** [comment]
Done by PR #647

**Comment by paolorotolo** [comment]
Thanks for the PR, about example app package name, I think it would be better to adopt a new package name like ```com.github.appIntro.example``` to keep consistency with the current library url.
@cortinico what do you think?

**Comment by Anutha02** [comment]
Yeah com.github.appIntro.example would be great.

**Comment by cortinico** [comment]
Let's go for `com.github.appintro.example` :) (no uppercase)

**Comment by Anutha02** [comment]
Done
