### ISSUE TITLE
[Enhancement] Crossfade Next/Finish Button

### ISSUE THREAD

**Issue by Anutha02** [AppIntro/AppIntro#644]
**Issue details / Repro steps / Use case background**: When the user navigates to the last slide, the next button abruptly changes to the finish button. It would be great if we can implement a fading animation(alpha depending upon pageOffset) between the two views. I tried doing so, but there is a blinking effect in my implementation and not a smooth fade... Do you think this can be implemented?

**Comment by cortinico** [comment]
@Anutha02 Do you mean for `layout2`?

I'd argue the icon should be an `AnimatedVectorDrawable` and change from arrow to tick eventually.

**Comment by Anutha02** [comment]
@cortinico yes for layouts, but the next and finish buttons are separate and I believe animatedvectordrawable only works for one button....:-|

**Comment by paolorotolo** [comment]
+1 for the morphing animation on the button :+1:

**Comment by Anutha02** [comment]
I tried implementing it. But in the implementation I saw for reference, the next/finish button were the same and only the drawable changed at the last slide, but here along with the drawable, the background circle also changes colour and that leads to a blinking effect while transforming. I will look further into it today.
