### ISSUE TITLE
Overscroll viewpager

### ISSUE THREAD

**Issue by Anutha02** [AppIntro/AppIntro#648]
**Device:** Xiaomi Redmi Note 5 pro

**Issue details / Repro steps / Use case background**: So in MIUI, the new activity opens from right side and moves to the left which happens to be the same way the next page of viewpager appears. Now while pressing skip/finish button the activity ends and goes from left to right. This gives an effect that instead of going forward we are going backwards.So we need to implement a transition that exits the viewpager from right to left on click.

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by cortinico** [comment]
@Anutha02 Can you record a video? I don't have a MIUI so I can't really reproduce :|

**Comment by Anutha02** [comment]
@cortinico Sorry, didn't see your comment

**Comment by Anutha02** [comment]
Anyways, don't worry, I am working on it :)
