### ISSUE TITLE
How to use imageURL

### ISSUE THREAD

**Issue by nazeerahamed23** [AppIntro/AppIntro#649]
How to use image URL instead of image drawable?

**Comment by Anutha02** [comment]
Do you mean for the background of the activity?

**Comment by nazeerahamed23** [comment]
yes

**Comment by Anutha02** [comment]
It is currently work in progress. Might be available in next release

**Comment by cortinico** [comment]
Just to clarify @nazeerahamed23 
@Anutha02 is working on a feature to allow you to set a image as background via resId/Drawable (see #647)

There is no image URL download feature.
