### ISSUE TITLE
Add a new fragment layout?

### ISSUE THREAD

**Issue by Anutha02** [AppIntro/AppIntro#658]
**AppIntro Version**: Upcoming

**Issue details / Repro steps / Use case background**: There are a few people asking for a layout in which the title is below the image and just above the description, so I was thinking of adding it. To get this, we can create a class AppIntro2Fragment and a new fragment layout. So let me know if this is acceptable...😄

**Comment by Anutha02** [comment]
@cortinico what do you think?

**Comment by cortinico** [comment]
Yeah sounds good to me 👍
