### ISSUE TITLE
What is wizard mode?

### ISSUE THREAD

**Issue by Anutha02** [AppIntro/AppIntro#659]
**Issue details / Repro steps / Use case background**: I have seen mentions of a wizard mode throughout the code, but never really understood what it is. It is listed in the to-do for the sample App Rewrite, and I couldn't find it in the readme, so could anyone explain please.

**Comment by cortinico** [comment]
Hey @Anutha02 

IIRC the wizard mode should be the `template` feature that is here:
https://github.com/AppIntro/AppIntro/tree/master/template

I think we can probably remove it as Android Studio evolved so much and last commit on that was 2 years ago. Moreover I don't think developers are really using it.

@paolorotolo thoughts on this?
