### ISSUE TITLE
Change behaviour when closing AppIntro

### ISSUE THREAD

**Issue by Anutha02** [AppIntro/AppIntro#664]
**AppIntro Version**: Upcoming

**Issue details / Repro steps / Use case background**: If a user presses the skip button or presses the back button (on navigation bar) AppIntro closes without any info. This can be a problem for apps that implement login screens in the Intro or request permissions. I propose that we implement something, so that users can use onActivity result to check if the user cancelled the intro midway or finished it successfully. So, tell me if this is correct/you want any other modifications, then I will submit a PR

**Comment by Anutha02** [comment]
@cortinico @paolorotolo please respond

**Comment by paolorotolo** [comment]
I think we can just let the activity close and do nothing. Developers can implement custom logic in overriding onSkipPressed or activity lifecycle methods.

**Comment by cortinico** [comment]
Agree. At the end of the story `AppIntro` runs into an activity. Developers can implement all the custom logic they want.
