### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [AppIntro/AppIntro#668]
Hello! I find this project very interesting and I'd love to contribute to it by designing a logo. Let me know if you'd want that too and if you have anything specifically imagined for your logo, if not I'll just implement my own ideas :) looking forward to hearing from you!

**Comment by AnuthaDev** [comment]
That would be great! I would love to see your ideas(maybe you could try using logos of other intro libraries for inspiration)

**Comment by newfinal100** [comment]
![first variations-01](https://user-images.githubusercontent.com/49202520/56098794-a4bf0200-5f04-11e9-900e-8cf87a542507.jpg)
![second variation-01](https://user-images.githubusercontent.com/49202520/56098798-ae486a00-5f04-11e9-9784-9e791a4dee89.jpg)
![third variation-01](https://user-images.githubusercontent.com/49202520/56098800-b7393b80-5f04-11e9-85dd-d88102d8ac0e.jpg)

Okay so here are three variations I created, I hope you'll like them and let me know what you think, which one you like the most and if you'd want me to make any changes! I personally think the second one is the best but you'll decide :)

**Comment by AnuthaDev** [comment]
Thanks for your hard work. I also like the second one, especially the idea of a face, but the purpose of the icon is to reflect the use case of the library/atleast match its name. (For example the logo of the leakcanary library is that of a canary).

**Comment by newfinal100** [comment]
![Fourth Variation-01](https://user-images.githubusercontent.com/49202520/56125237-ca85ee80-5f78-11e9-9461-8196821367e1.jpg)

I'm glad you liked the second one :) And you're right, I was focused too much on the face I didn't give any thought to the library part. What about this?

**Comment by AnuthaDev** [comment]
The one on the top right seems good, but I think we should merge the centre card with the face. I will share a rough sketch showing what I mean soon...

**Comment by newfinal100** [comment]
Do you mean you'd like the face to be on the center or? If you could upload a rough sketch that would be great :)

**Comment by ibrha** [comment]
i want add my own background how . ? i see just colorbackground

**Comment by newfinal100** [comment]
Could you please give me some more information on what do you mean by that?

**Comment by AnuthaDev** [comment]
@newfinal100 Sorry for the delay, i didn't get much time in last few days. Just wait a minute

**Comment by AnuthaDev** [comment]
Pardon my bad drawing and disproportionate elements, but I mean something like this:

https://drive.google.com/file/d/1U201LVaz2cp8DSM33goIsgx3ZBttb0Uj/view?usp=drivesdk

**Comment by newfinal100** [comment]
No problem that's okay :) I didn't understand the comment from ibrha about the color background so I wanted to know what's exactly meant by that :))

![5th variation-01](https://user-images.githubusercontent.com/49202520/56396885-5af65480-6241-11e9-97c6-bc55feebbc49.jpg)
So do you like some of these two versions more?

**Comment by AnuthaDev** [comment]
@newfinal100 don't worry, he was at the wrong place presumably. 

I think we should get rid of the antennae. Also please make the corner radius of the top equal to that of the bottom of the centre card. As for the colors, use red for the left, golden yellow for the centre and green for the right. Also, I think the 2nd design is better, so work only on it pls😄

**Comment by AnuthaDev** [comment]
@newfinal100 also, please take a look here

https://material.io/design/iconography/#

**Comment by paolorotolo** [comment]
Hey @newfinal100, thanks for your contributions!
I'm not a designer, but I think the proposed logo fail to represent in a clear and immediate way what AppIntro truly is. We might want to suggest the idea of an horizontal scrolling page with some slides with images and less text.

**Comment by cortinico** [comment]
I was thinking about something like a waving droid (like for the "intro").

![ic_launcher](https://user-images.githubusercontent.com/3001957/57197921-a0916d80-6f21-11e9-95fc-30ca895e075e.png)

Another Idea I had was to have like a curtains (again for the "intro" metaphore):

![ic_launcher](https://user-images.githubusercontent.com/3001957/57197948-ed754400-6f21-11e9-8116-869905c9a6c9.png)

**Comment by paolorotolo** [comment]
I really like the Android one!

**Comment by AnuthaDev** [comment]
I think a carousel icon would be better

**Comment by cortinico** [comment]
> I think a carousel icon would be better

Do you have a mock/prototype?

**Comment by cortinico** [comment]
If you can get it would be cool, so we can have all the proposal on the
desk :)

**Comment by AnuthaDev** [comment]
@cortinico Sure

**Comment by AnuthaDev** [comment]
@cortinico @paolorotolo What do you think of this? I still need to figure out the finer details like color, shadow, size etc. This is the first prototype 😅

![IMG_20190525_172346](https://user-images.githubusercontent.com/36439704/58368984-277aaa00-7f12-11e9-9219-4a11e678ee5b.jpg)

**Comment by paolorotolo** [comment]
Nice indeed, I really like it! Would you be able to replace the generic face with an Android, similar to what @cortinico did?

**Comment by AnuthaDev** [comment]
@paolorotolo It's a prototype, so I can do whatever you want me to. So, yeah, I will replace it with droid.

**Comment by AnuthaDev** [comment]
@cortinico @paolorotolo  How about this?
![Screenshot_20190526-104006_Chrome](https://user-images.githubusercontent.com/36439704/58377645-f1393b00-7fa2-11e9-92dd-2fb716bbef0d.png)

**Comment by cortinico** [comment]
Hey @AnuthaDev Can we use the Droid graphic I used in my icon? Maybe we can put the droid just on top of the white line in the center?

**Comment by AnuthaDev** [comment]
@cortinico Sure

**Comment by AnuthaDev** [comment]
@cortinico @paolorotolo I guess this is good enough:

![final](https://user-images.githubusercontent.com/36439704/58705821-ea109380-83cd-11e9-82c3-8735aaf3794e.png)

**Comment by cortinico** [comment]
Looks good to me :D I would move the Droid down and left attached to the line.
Moreover do you have a Sketch/SVG file to share so that we can play around as well?

**Comment by paolorotolo** [comment]
Not bad at all, well done!

**Comment by AnuthaDev** [comment]
@cortinico I have an illustrator file, so I can share it and also an svg if you want. Only a few finishing touches are left and then it will be ready.

**Comment by cortinico** [comment]
Looking forward :)

**Comment by AnuthaDev** [comment]
Hey @cortinico @paolorotolo I guess this is final:

![newfinal100](https://user-images.githubusercontent.com/36439704/58902698-40106e80-8721-11e9-8219-6a2b1a78e00b.png)

**Comment by AnuthaDev** [comment]
If you like it, tell me, I will give a high res version of the icon and will also give the background and foreground xmls for making an adaptive icon

**Comment by cortinico** [comment]
Generally looks good :) But I'd rather do a couple of tweaks to the frame. 
If you could provide the high-res version would be great.

**Comment by AnuthaDev** [comment]
@cortinico Could you please tell me what tweaks you want to the frame, or,  if you want it, I can give you the illustrator file to edit yourself.

**Comment by cortinico** [comment]
Here the changes I would apply.

* Color -> Use one of the two whites you already have in the icon.
* Corners -> Be consistent with the outer frame
* Placing -> Align the frame with the big white line.

That's a sketch to give you an idea:

![Screenshot 2019-06-05 at 12 51 19](https://user-images.githubusercontent.com/3001957/58951386-476f6080-8791-11e9-9e37-4449a9172c1f.png)

**Comment by AnuthaDev** [comment]
@cortinico Alright, will do the adjustments asap

**Comment by cortinico** [comment]
@AnuthaDev Any updates here?

**Comment by AnuthaDev** [comment]
Hey @cortinico , Sorry for being this late, i got too busy. Anyways, how about this:
![nf](https://user-images.githubusercontent.com/36439704/65241023-352aef80-db00-11e9-9034-f31479ec5b1d.png)

**Comment by cortinico** [comment]
Looks good to me :) Can I ask you to submit a PR with the sources (like ideally `svg`, `ai` or whatever format you used).

**Comment by AnuthaDev** [comment]
@cortinico I have a better option, I send you the file and you submit the PR😅

**Comment by AnuthaDev** [comment]
I have the illustrator(ai) file. Should I email it to you?

**Comment by cortinico** [comment]
Yes please :) You can find my mail on my GitHub profile.

**Comment by paolorotolo** [comment]
Great work!

**Comment by AnuthaDev** [comment]
Hey @cortinico I have emailed the file to you. So, take a look at it😄

**Comment by AnuthaDev** [comment]
@cortinico Have you received the logo?🤔

**Comment by paolorotolo** [comment]
@AnuthaDev can you send me the files as well? Nicola is busy at the moment, so I can make the pr instead. Email to paolo@rotolo.dev

**Comment by AnuthaDev** [comment]
@paolorotolo Done

**Comment by paolorotolo** [comment]
Got it, thanks!

**Comment by paolorotolo** [comment]
@AnuthaDev as I don't have Adobe Illustrator, can you save the .ai file with "Create PDF Compatible File" option checked? You may also export in a more open vector format like .svg.

**Comment by cortinico** [comment]
Hey @AnuthaDev 
Sorry but as @paolorotolo said, I was really busy with other projects and I ended up missing some mails. I also don't have Illustrator and apparently I'm facing the same issue @paolorotolo is having. You should save the .ai file with "Create PDF Compatible File". Please mail us the updated file if possible.

**Comment by AnuthaDev** [comment]
Hey @cortinico I have mailed you the files. Please take a look.

**Comment by cortinico** [comment]
>  I have mailed you the files. Please take a look.

Thanks, I'll check it and include it in the repo.

**Comment by cortinico** [comment]
Closing as the Logo got approved and will be published with 6.0.0 🎉
