### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by lucalves** [AppIntro/AppIntro#672]
Good afternoon sirs,

I applied Intro to an application I'm developing, but I came across the following difficulty:

When I flip the application from horizontal to vertical or vice versa, the same goes back to the Introduction screen.

Does anyone have a solution for when turning the screen, does it remain on the current screen?

**Comment by cortinico** [comment]
Hey @lucalves 
Which version of the library are you using?

**Comment by lucalves** [comment]
I'm using the version 4.2.3. @cortinico

**Comment by cortinico** [comment]
Hey @lucalves 
Just tested on the latest version `6.0.0-alpha1`. I wasn't able to reproduce the bug you reported.
Have you considered updating to the latest version to check if the bug is still there?

**Comment by lucalves** [comment]
To test this version I would need to migrate the application to android X first, shall I?

I'm going to take the test and report it here in the Issue.
@cortinico

**Comment by cortinico** [comment]
> To test this version I would need to migrate the application to android X
first, shall I?

Ideally yes. Please note that all the bugfixes and the new features will
happen on the version of AppIntro that is AndroidX capable (5.+).

If your app is too big, you can still try to use Jetifier Reverse Mode (see
here https://ncorti.com/blog/jetifier-reverse).
Although I anyway recommend you consider migrating to AndroidX as soon as
possible.

**Comment by AnuthaDev** [comment]
@lucalves So, did you try updating to androidx?

**Comment by lucalves** [comment]
Yes, in the version that @cortinico reported, after migrating to Android X, worked perfectly. Thank you guys!

**Comment by cortinico** [comment]
You're welcome :)
