### ISSUE TITLE
Alternate method to request permissions without blocking swipe

### ISSUE THREAD

**Issue by AnuthaDev** [AppIntro/AppIntro#679]
**Issue details / Repro steps / Use case background**: I have an idea of a different method to request permissions without blocking swipe as the approach used in #678 has lots of room for improvement. I am working on it and would like to know what you think. :
Suppose the slide X contains permissions. As soon as the user swipes left from slide x-1, the swipe to next slide is disabled(swipe to previous still works). The user swipes left on the slide X, and the permission dialog opens. If the user accepts, the slide changes, if he doesn't and the permission is optional, the slide changes, but if the permission is required, the swipe is still disabled and the app may show an alertdialog/snack bar to tell user that the permission is compulsory. The user cannot cross the intro until they grant the permission.

I am still working on it. My new implementation would be a modified version of my approach in #676 , but with less code and more robustness.

Tell me if you think this flow is fine or it needs any modifications.

**Comment by cortinico** [comment]
> if he doesn't and the permission is optional, the slide changes, but if the permission is required, the swipe is still disabled and the app may show an alertdialog/snack bar to tell user that the permission is compulsory

I'm concerned in introducing the concept of optional/compulsory permissions.
The scope of the library is creating a simple/nice intro for your Android App.

Dealing with permissions is a "plus" that we provide to the library users to simplify their life.
I don't think we have to solve all the problems of any intro flow. 
So far we haven't received many issues related to optional/compulsory permissions, so I'm wondering also how many users are actually using this feature.

If you have a simple implementation that can improve the current status, is definitely worth to look at it. But we also have a lot of other more impactful tasks to do.

**Comment by AnuthaDev** [comment]
@cortinico Having it as a feature won't do any harm. I know that we don't have to solve all the intro problems, but if we provide a "plus" , we better provide a good one😁

**Comment by cortinico** [comment]
> Having it as a feature won't do any harm

I generally don't agree on this. We're trying to keep the feature set of the library as smaller as possible.
This will make the library generally easier to maintain, easier to understand and easier to use. 

Anyway please send your implementation and we can discuss on the PR if it makes sense to be included or not 👍
