### ISSUE TITLE
Get an awesome kotlin badge

### ISSUE THREAD

**Issue by AnuthaDev** [AppIntro/AppIntro#685]
**Issue details / Repro steps / Use case background**: Since this project is almost 100% kotlin now, it would be great if we add an awesome kotlin badge on top of our readme.

More info here: https://github.com/KotlinBy/awesome-kotlin

**Comment by AnuthaDev** [comment]
Hey @cortinico You made some progress?

**Comment by cortinico** [comment]
Not really 😅 https://github.com/KotlinBy/awesome-kotlin/pull/459
