### ISSUE TITLE
Can't even implement the AppIntro

### ISSUE THREAD

**Issue by Diaj3** [AppIntro/AppIntro#690]
**The erros that I have don't allow me to even run the program**:

**I tried to use the code they give us in the AppIntro and even tried some variations from some youtube tutorials but all give me errors
**: 

```
package com.example.biscates;

import android.content.Intent;
import android.graphics.Color;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Toast;

import com.github.paolorotolo.appintro.AppIntro;
import com.github.paolorotolo.appintro.AppIntroFragment;

public class AppIntroActivity extends AppIntro {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addSlide(AppIntroFragment.newInstance("Hey", "description", R.drawable.testingImage4, Color.BLUE));
        // Note here that we DO NOT use setContentView();

        // Add your slide fragments here.
        // AppIntro will automatically generate the dots indicator and buttons.

        // Instead of fragments, you can also use our default slide.
        // Just create a `SliderPage` and provide title, description, background and image.
        // AppIntro will do the rest.
        SliderPage sliderPage = new SliderPage();
        sliderPage.setTitle(title);
        sliderPage.setDescription(description);
        sliderPage.setImageDrawable(image);
        sliderPage.setBgColor(backgroundColor);
        addSlide(AppIntroFragment.newInstance(sliderPage));

        // OPTIONAL METHODS
        // Override bar/separator color.
        setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

        // Hide Skip/Done button.
        showSkipButton(false);
        setProgressButtonEnabled(false);

        // Turn vibration on and set intensity.
        // NOTE: you will probably need to ask VIBRATE permission in Manifest.
        setVibrate(true);
        setVibrateIntensity(30);
    }

    @Override
    public void onDonePressed(Fragment currentFragment){
        super.onDonePressed(currentFragment);
        Intent intent = new Intent(getApplicationContext().MainActivity.class);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        Toast.makeText(MainActivity.this, "App Intro Ended", Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        // Do something when users tap on Done button.
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        // Do something when the slide changes.
    }
}
```

**Stack trace / LogCat**:
```ruby
code in the screenshots
```

![1](https://user-images.githubusercontent.com/43539237/58382729-a977db00-7fc5-11e9-84c4-f2433f4d68bb.png)
![2](https://user-images.githubusercontent.com/43539237/58382730-a977db00-7fc5-11e9-86ff-23f0ae24e04c.png)
![3](https://user-images.githubusercontent.com/43539237/58382731-a977db00-7fc5-11e9-86c8-02c7434b0b77.png)

**Comment by cortinico** [comment]
Hey @Diaj3 which version of AppIntro are you using?
Is you application using AndroidX or the old support library?

**Comment by Diaj3** [comment]
old support library

**Comment by cortinico** [comment]
which version of AppIntro are you using?

**Comment by Diaj3** [comment]
the previous one "implementation 'com.github.AppIntro:AppIntro:4.2.3'"

**Comment by cortinico** [comment]
So your code has multiple problems that the IDE is already telling you:

# onDonePressed
![img](https://user-images.githubusercontent.com/43539237/58382731-a977db00-7fc5-11e9-86c8-02c7434b0b77.png)

You have the `onDonePressed` function defined twice in you code. You must remove one of the two functions.

# onSkipPressed
![img](https://user-images.githubusercontent.com/43539237/58382730-a977db00-7fc5-11e9-86ff-23f0ae24e04c.png)

You're referencing `MainActivity.this` while your activity is called `AppIntroActivity`. So you should change your `onSkipPressed` code to:

```
    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        Toast.makeText(AppIntroActivity.this, "App Intro Ended", Toast.LENGTH_SHORT).show();
    }
```

# SliderPage

![img](https://user-images.githubusercontent.com/43539237/58382729-a977db00-7fc5-11e9-84c4-f2433f4d68bb.png)

The code is failing since you're not importing the `SliderPage` class. Please make sure that you have those 3 lines on the top of your activity (you have only two at the moment).
```
import com.github.paolorotolo.appintro.AppIntro;
import com.github.paolorotolo.appintro.AppIntroFragment;
import com.github.paolorotolo.appintro.model.SliderPage;
```

**Comment by Diaj3** [comment]
Thank you so much, one more thing, from tutorials I've seen them use both this ways on the functions, which is better to use and what do they really do differently?

![image](https://user-images.githubusercontent.com/43539237/58383179-6f113c80-7fcb-11e9-9916-b22edcad5d6c.png)

**Comment by cortinico** [comment]
So the first `onDonePressed` is ideally what you want to have. It will start the `MainActivity`, so your user will proceed to that screen of your app.

The second `onDonePressed` is showing just a message "App Intro Ended" to the user and that's it. So the user can't really exit from the flow.

**Comment by Diaj3** [comment]
Thanks for eveything, the AppIntro is now looking great thanks to you :D
