### ISSUE TITLE
[Feature Request]: Support Single Activity pattern

### ISSUE THREAD

**Issue by kaushalyap** [AppIntro/AppIntro#704]
As I tried it seems to be it only worked inside activity, new navigation architecture component promotes [single activity](https://www.youtube.com/watch?v=2k8x8V77CrU) concept. So please  support appintro to be used inside a fragment.

**Comment by cortinico** [comment]
Duplicate of #510 

Ideally you should have an Activity for AppIntro and another activity for the your navigation controlled flow.

**Comment by kaushalyap** [comment]
@cortinico I closed it, but IMHO I do not think its a good solution to use another activity just to use AppIntro.  I think you are suggesting this because, it may be hard to do it in fragment level.
