### ISSUE TITLE
Activity closes when next button is clicked

### ISSUE THREAD

**Issue by AlanInsam** [AppIntro/AppIntro#707]
**5.1.0**:

**fails on OnePlus 6**:

**When I click "next" in my first slide, the activity gets destroyed even if the done button  is on the next slide, I use slidePage as in the examples (not fragments...) the code is the same as in the wiki, do i have to change something on done pressed?**: 

**@Override
    public void onDonePressed(Fragment currentFragment) {
            super.onDonePressed(currentFragment);
        // Do something when users tap on Done button.
    }**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by cortinico** [comment]
@AlanInsam 
Can I ask you to paste the whole code of your AppIntro Activity?

**Comment by AlanInsam** [comment]
@cortinico it turned out that setVibration destoryed the activity on next tapped.
