### ISSUE TITLE
Button colors

### ISSUE THREAD

**Issue by zionnite** [AppIntro/AppIntro#710]
Hello pals!
how do i change the buttons color and as well as the dot indicator!

i don't really know how to do it.
thanks for your support

**Comment by cortinico** [comment]
Hi @zionnite 

> how do i change the buttons color

You can use the `setNextArrowColor`, `setNextArrowColor` and `setColorSkipButton`

> and as well as the dot indicator!

You can use the `setIndicatorColor(Int, Int)` method on your `AppIntro` subclass.
Please note that you need to have your indicator initialized before calling that method. For example the following code will work:

```kotlin
public class MyIntro extends AppIntro {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setIndicatorController(new DotIndicatorController(this));
        setIndicatorColor(Color.RED, Color.BLUE);

		...
    }
}
```

**Comment by Canoir** [comment]
what about back arrow color?
