### ISSUE TITLE
Change image and text sizes

### ISSUE THREAD

**Issue by ofirkapzan** [AppIntro/AppIntro#718]
Can i change image sizdes ?
if not, can i change the text design? (added bold or change the text style?)

thanks --> ofir.kapzan@gmail,com

**Comment by cortinico** [comment]
@ofirkapzan You can use a Custom Layout slide and customize the UI as you wish providing your own layout files.
An example is shown here:
https://github.com/AppIntro/AppIntro/blob/master/example/src/main/java/com/amqtech/opensource/appintroexample/ui/mainTabs/intro/CustomLayoutIntro.java

**Comment by lakecountypassage** [comment]
This class removed?
