### ISSUE TITLE
Fatal Exception: Resources$NotFoundException

### ISSUE THREAD

**Issue by Wiktorl4z** [AppIntro/AppIntro#719]
My class 

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val sliderPage1 = SliderPage()
        sliderPage1.titleTypefaceFontRes = R.font.mystery_quest
        sliderPage1.description = resources.getString(R.string.description1)
        sliderPage1.descTypefaceFontRes = R.font.mystery_quest
        sliderPage1.imageDrawable = R.drawable.tibiamonsters_logo
        sliderPage1.bgColor = Color.parseColor("#000000")
        addSlide(AppIntroFragment.newInstance(sliderPage1))

        val sliderPage2 = SliderPage()
        sliderPage2.titleTypefaceFontRes = R.font.mystery_quest
        sliderPage2.description = resources.getString(R.string.description2)
        sliderPage2.descTypefaceFontRes = R.font.mystery_quest
        sliderPage2.imageDrawable = R.drawable.tibiadragon
        sliderPage2.bgColor = Color.parseColor("#000000")
        addSlide(AppIntroFragment.newInstance(sliderPage2))

        val sliderPage3 = SliderPage()
        sliderPage3.titleTypefaceFontRes = R.font.mystery_quest
        sliderPage3.title = resources.getString(R.string.monsters_categories)
        sliderPage3.description = resources.getString(R.string.description3)
        sliderPage3.descTypefaceFontRes = R.font.mystery_quest
        random(sliderPage3)
        sliderPage3.bgColor = Color.parseColor("#000000")
        addSlide(AppIntroFragment.newInstance(sliderPage3))

        isSkipButtonEnabled = false
        isVibrateOn = true
        setFadeAnimation()
        vibrateDuration = 60
    }

    override fun onDonePressed(currentFragment: androidx.fragment.app.Fragment?) {
        super.onDonePressed(currentFragment)
        val intent = Intent(this, HomeActivity::class.java)
        intent.flags = Intent.FLAG_ACTIVITY_SINGLE_TOP
        startActivity(intent)
        finish()
    }

    private fun random(slider: SliderPage) {
        val random = (0..5).random()
        when (random) {
            0 -> slider.imageDrawable = R.drawable.poi_bosses_fixed
            1 -> slider.imageDrawable = R.drawable.roshamuul
            2 -> slider.imageDrawable = R.drawable.dream_court
            3 -> slider.imageDrawable = R.drawable.library
            4 -> slider.imageDrawable = R.drawable.weak_bosses
            5 -> slider.imageDrawable = R.drawable.issavi
        }
    }

**implementation 'com.github.AppIntro:appintro:6.0.0-alpha3'**:

**Galaxy On7 Pro / Android 6.0.1**:

**Stack trace / LogCat**:
```
Fatal Exception: android.content.res.Resources$NotFoundException
Font resource ID #0x7f090005 could not be retrieved.
androidx.core.content.res.ResourcesCompat.getDrawable (ResourcesCompat.java)
androidx.core.content.res.ResourcesCompat.getDrawable (ResourcesCompat.java)
com.github.paolorotolo.appintro.internal.TypefaceContainer.applyTo (TypefaceContainer.java)
com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView (AppIntroBaseFragment.java)
androidx.fragment.app.Fragment.performCreateView (Fragment.java)
androidx.fragment.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
androidx.fragment.app.FragmentManagerImpl.dispatchPrimaryNavigationFragmentChanged (FragmentManagerImpl.java)
androidx.fragment.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java)
androidx.fragment.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
androidx.fragment.app.FragmentManagerImpl.allocBackStackIndex (FragmentManagerImpl.java)
androidx.fragment.app.FragmentManagerImpl.completeShowHideFragment (FragmentManagerImpl.java)
androidx.fragment.app.FragmentManagerImpl.allocBackStackIndex (FragmentManagerImpl.java)
androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java)
androidx.fragment.app.FragmentPagerAdapter.finishUpdate (FragmentPagerAdapter.java)
androidx.viewpager.widget.ViewPager.populate (ViewPager.java)
androidx.viewpager.widget.ViewPager.populate (ViewPager.java)
androidx.viewpager.widget.ViewPager.onMeasure (ViewPager.java)
android.view.View.measure (View.java:20236)
androidx.constraintlayout.widget.ConstraintLayout.onMeasure (ConstraintLayout.java)
android.view.View.measure (View.java:20236)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6333)
android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
androidx.appcompat.widget.ContentFrameLayout.onMeasure (ContentFrameLayout.java)
android.view.View.measure (View.java:20236)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6333)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1464)
android.widget.LinearLayout.measureVertical (LinearLayout.java:747)
android.widget.LinearLayout.onMeasure (LinearLayout.java:629)
android.view.View.measure (View.java:20236)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6333)
android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
android.view.View.measure (View.java:20236)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6333)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1464)
android.widget.LinearLayout.measureVertical (LinearLayout.java:747)
android.widget.LinearLayout.onMeasure (LinearLayout.java:629)
android.view.View.measure (View.java:20236)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6333)
android.widget.FrameLayout.onMeasure (FrameLayout.java:194)
com.android.internal.policy.PhoneWindow$DecorView.onMeasure (PhoneWindow.java:3140)
android.view.View.measure (View.java:20236)
android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:2704)
android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:1656)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1948)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1544)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7607)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:911)
android.view.Choreographer.doCallbacks (Choreographer.java:686)
android.view.Choreographer.doFrame (Choreographer.java:622)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:897)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7331)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

Unfortunately still got same problem like it was in version 5.1.0
Would you like to help me how can I fix it OR can you fix it?

**Comment by cortinico** [comment]
Hi @Wiktorl4z 
Looks like the crash is caused by your app missing one of the resource.
Are you sure you have all of those resources inside your `res` folders:

```
R.drawable.poi_bosses_fixed
R.drawable.roshamuul
R.drawable.dream_court
R.drawable.library
R.drawable.weak_bosses
R.drawable.issavi
```

Please verify.
If this is the case, please share a project where we can reproduce the crash.

**Comment by Wiktorl4z** [comment]
Hi @cortinico 
All resources are in res folder. 
But one image had only one size for all devices (xhdpi density). I have changed it.
Other images are in 100% fine. Do you think it might be the case?

I think you missed two lines above stack trace. They say something with font is not correct.
I have edited these two lines which were above and added them to stack trace. 
It might be more readable now.

my font xml
```
<?xml version="1.0" encoding="utf-8"?>
<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
        app:fontProviderAuthority="com.google.android.gms.fonts"
        app:fontProviderPackage="com.google.android.gms"
        app:fontProviderQuery="Mystery Quest"
        app:fontProviderCerts="@array/com_google_android_gms_fonts_certs">
</font-family>
```

**Comment by Wiktorl4z** [comment]
Hi @cortinico I think you can close the ticket. I am not having this problem in crashlytics from that time. 
So I guess everything is fine! 👍
