### ISSUE TITLE
Release 6.0.0 stable

### ISSUE THREAD

**Issue by carstenhag** [AppIntro/AppIntro#722]
Currently using 6.0.0-alpha3 since months, I'm wondering what's missing for the stable version of 6.0.0. Any clue?

**Comment by AnuthaDev** [comment]
PR #686 is a blocker, as well as a few more code fixes and a parallax feature are needed for the stable release.

**Comment by cortinico** [comment]
Hey @carstenhag 
Thanks for raising this point. I can say that I have to take responsibility for the delay and apologize for it. I took two months off and I've generally been quite busy (@paolorotolo probably as well).

The release of 6.0.0 stable is definitely on the roadmap and will happen within the end of January.

I also have to apologize given that we haven't done a great job in sharing roadmaps and keeping the community posted on what's going on with AppIntro. Hopefully we will be able to do a better job.

Please find #725 with a list of blockers for the 6.0.0 release. Feel free to comment there if you have any feedbacks and thanks for sharing your point of view again.
