### ISSUE TITLE
Change AppIntro library package name

### ISSUE THREAD

**Issue by paolorotolo** [AppIntro/AppIntro#745]
Since next version of AppIntro will introduce other breaking changes, we can take advantage of this changing the old library package name.

@cortinico does `com.github.appintro` works for you? Together with `com.github.appintro.example` for our example app.

**Comment by AnuthaDev** [comment]
It works for me that's for sure😁

**Comment by cortinico** [comment]
> @cortinico does com.github.appintro works for you? Together with com.github.appintro.example for our example app.

Works for me. I was checking if we could have problem with Sonatype given that we don't own the "com.github" part. Apparently this is not a problem as a lot of other developers are doing the same: https://issues.sonatype.org/browse/OSSRH-49838?jql=text%20~%20%22com.github%22

Then let's go for that. @paolorotolo do you want to do this change?

**Comment by paolorotolo** [comment]
Sure thing.
