### ISSUE TITLE
Getting "error: package com.github.appintro does not exist"

### ISSUE THREAD

**Issue by Nimzr** [AppIntro/AppIntro#751]
**AppIntro Version**: 5.0.1

**Device/Android Version**:Pixel 3 xl/ Android 10 (not related to device)

**Issue details / Repro steps / Use case background**:  Getting an error "error: package com.github.appintro does not exist" I'm very junior so this could be something obvious I'm missing. 
I have this in my build.grade:
`    implementation  'com.github.AppIntro:AppIntro:5.1.0'`

**Your Code**:   IntroActivity Java

`package com.example.android.pubgapitest;

import android.graphics.Color;
import android.os.Bundle;

import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.github.appintro.AppIntroCustomLayoutSlide;
import com.github.paolorotolo.appintro.AppIntro;

public class IntroActivity extends AppIntro {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Note here that we DO NOT use setContentView();

        // Add your slide fragments here.
        // AppIntro will automatically generate the dots indicator and buttons.
        addSlide(AppIntroCustomLayoutSlide.newInstance(R.layout.user_name_slide));
        addSlide(AppIntroCustomLayoutSlide.newInstance(R.layout.user_platform_slide));
        addSlide(AppIntroCustomLayoutSlide.newInstance(R.layout.confirm_pref_slide));

        // Instead of fragments, you can also use our default slide.
        // Just create a `SliderPage` and provide title, description, background and image.
        // AppIntro will do the rest.
//        SliderPage sliderPage = new SliderPage();
//        sliderPage.setTitle(title);
//        sliderPage.setDescription(description);
//        sliderPage.setImageDrawable(image);
//        sliderPage.setBgColor(backgroundColor);
//        addSlide(AppIntroFragment.newInstance(sliderPage));

        // OPTIONAL METHODS
        // Override bar/separator color.
        setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

        // Hide Skip/Done button.
//        showSkipButton(false);
//        isButton(false);

        // Turn vibration on and set intensity.
        // NOTE: you will probably need to ask VIBRATE permission in Manifest.
        setVibrate(true);
        setVibrateIntensity(30);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        // Do something when users tap on Skip button.
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        // Do something when users tap on Done button.
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        // Do something when the slide changes.
    }
}`

Custom Slider Class

`package com.github.appintro

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment

/**
 * Util class to be used when creating a slide with a custom layout.
 * [AppIntroCustomLayoutSlide.newInstance] passing the Layout ID of your custom layout.
 *
 * You can then use this Slide with the [AppIntroBase.addSlide] methods to add this slide
 * to your AppIntro.
 */
class AppIntroCustomLayoutSlide : Fragment() {

    private var layoutResId = 0

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        layoutResId = arguments?.getInt(ARG_LAYOUT_RES_ID) ?: 0
    }

    override fun onCreateView(
            inflater: LayoutInflater,
            container: ViewGroup?,
            savedInstanceState: Bundle?
    ): View? = inflater.inflate(layoutResId, container, false)

    companion object {
        private const val ARG_LAYOUT_RES_ID = "layoutResId"
        @JvmStatic
        fun newInstance(layoutResId: Int): AppIntroCustomLayoutSlide {
            val customSlide = AppIntroCustomLayoutSlide()
            val args = Bundle()
            args.putInt(ARG_LAYOUT_RES_ID, layoutResId)
            customSlide.arguments = args
            return customSlide
        }
    }
}`

**Stack trace / LogCat**:
error: package com.github.appintro does not exist

**Comment by cortinico** [comment]
Hi @Nimzr 
Thanks for reporting this

> **Stack trace / LogCat**:
> error: package com.github.appintro does not exist

I'm sorry you got this failure.
We're currently in the process of rewriting the whole README as well as releasing AppIntro 6.0.0.

Looks like you copied over some code from the README that it's currently on `master`. That would work for the upcoming version (6.0.0) but not for the latest stable `5.1.0`.

My advice is to copy from the README of the version 5.1.0 rather than the one on master: https://github.com/AppIntro/AppIntro/blob/v5.1.0/README.md
I hope this helps
