### ISSUE TITLE
I have to add manually a class 

### ISSUE THREAD

**Issue by elianbarci** [AppIntro/AppIntro#752]
In order to use an exisiting layout for my onBoarding slider i have to add "manually" the class **AppIntroCustomLayoutSlider**

AppIntro dependency:     implementation 'com.github.AppIntro:AppIntro:4.2.3'

If i can help with something let me know

**Comment by cortinico** [comment]
> In order to use an exisiting layout for my onBoarding slider i have to add "manually" the class AppIntroCustomLayoutSlider

We're aware of the issue. This class will be released in AppIntro `6.0.0`, it will be available once the library is released. Historically that was a "sample file" that developers had to copy over (so it's the intended behavior). Now we moved inside the library.

Thanks for reporting :)
