### ISSUE TITLE
Typing test

### ISSUE THREAD

**Issue by Eichhof** [AppIntro/AppIntro#754]
Hello

I use the Android library AppIntro for creating nice intros for my app. As part of the intro I would like to create a small keyboard typing test. That means at the upper part of the screen a text should be shown and at the lower part there should be a box where the user should type the text using the keyboard. In addition, the typed text should be checked for correctness (a small percentage of mistakes allowed.

Can this be done as part of this library?

**Comment by cortinico** [comment]
Hi @Eichhof 

> That means at the upper part of the screen a text should be shown and at the lower part there should be a box where the user should type the text using the keyboard

You can achieve this by using a custom layout

>  In addition, the typed text should be checked for correctness (a small percentage of mistakes allowed.

And you can achieve this letting your custom layout slide implement [ISlidePolicy](https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/java/com/github/appintro/ISlidePolicy.kt)

**Comment by Eichhof** [comment]
Hi @cortinico 

Thank you very much for your answer. May I ask you for a short example? That would make things clearer.

**Comment by cortinico** [comment]
You can use this commit as example: https://github.com/cortinico/AppIntro/commit/ff94ffa5beafb3dc0fafeff880b5ef69cf55dc4e

You will be able to slide forward only by inserting the password `1234`. Other text will show an error message.
