### ISSUE TITLE
Repeat slide in onSlideChanged

### ISSUE THREAD

**Issue by Eichhof** [AppIntro/AppIntro#757]
Hello

I have implemented the onSlideChanged() method in the following way:

```
    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        String permission = null;
        if (oldFragment instanceof SomeFragment) {
            // Check something and possible stay on slide
        }

    }
```

How can I stay on the fragment, that means not switching to newFragment but again show oldFragment?

**Comment by cortinico** [comment]
You're able to achieve this behavior using the `ISlidePolicy` interface:
https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/java/com/github/appintro/ISlidePolicy.kt

if you return `false` on the `isPolicyRespected` property, the user won't be able to slide next. You don't need to override the `onSlideChanged`.
