### ISSUE TITLE
ISlidePolicy not working for me

### ISSUE THREAD

**Issue by Supermiro19** [AppIntro/AppIntro#759]
The app is running without errors and everything is working except the policy respect part since the slide movement doesn't get disabled and regardless of anything the user is able to continue to the next page.

Here is my fragment code

```
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.Toast;

import com.github.appintro.ISlidePolicy;

public class privacy_policy extends Fragment implements ISlidePolicy {
    public privacy_policy() {
    // Removing or adding this part made no difference but I added it anyway since google added 
     it when I created a blank fragment.
    }
    private CheckBox checkBox;
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
// Tried getView both on Create and on Create View didn't work
        checkBox = getView().findViewById(R.id.agree);
    }
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        View test = inflater.inflate(R.layout.privacy_policy_layout, container, false);
// I also tried doing test.findViewById and it did not work
        checkBox = test.findViewById(R.id.agree);
        return test;
    }
    @Override
    public boolean isPolicyRespected() {
     return checkBox.isChecked();

    }
    @Override
    public void onUserIllegallyRequestedNextPage() {
        Toast.makeText(getContext(), "Please click on the checkbox to continue", Toast.LENGTH_SHORT).show();
    }
}
```

Here is my XML code 

I only added the part that makes it refer to the java class so I do not annoy you with big chunks of XML code

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context=".privacy_policy">
```

and to connect the slide to the intro I added this line to my AppIntro activity

`addSlide(AppIntroCustomLayoutSlide.newInstance(R.layout.privacy_policy_layout));`

So is this a bug or is there something I am doing wrong?

I am using the AppIntro GitHub repository version. I downloaded it and added it to my android project as a module and enabled kotlin for sure.
Since the 5.1.0 doesn't have the custom slide feature.

Thank you for your time and your awesome project. I really appreciate it.

**Comment by cortinico** [comment]
Hi @Supermiro19,
Looks like you're instantiating the new slide in the wrong way.
You should use the class you created and not the `AppIntroCustomLayoutSlide`:

```java
addSlide(privacy_policy());
```

That should work. Please let me know if this solved your issue.

On a side note: 
- I'd suggest you use a consistent naming for your classes. `privacy_policy` should probably be renamed to `PrivacyPolicyFragment` or something similar.
- I'd suggest you don't invoke the constructor directly but use a static `.newInstance()` method to construct a new `Fragment`.

**Comment by Supermiro19** [comment]
First of all thank you for your response using addslide(privacy_policy()); didn't work and produced an error. (Unkown method error)

Now after you told me its better to create a new instance I kept searching for a while and here is what finally made it work for me.

`addSlide(getSupportFragmentManager().getFragmentFactory().instantiate(getClassLoader(),your_class_name.class.getName()));`

**Comment by cortinico** [comment]
Happy to hear that this worked for you. On the other hand you should be able to just use a `.newInstance()` static method. You don't need to ask the `FragmentFactory` to create a new instance.

**Comment by Supermiro19** [comment]
I am sorry but both addSlide(privacy_policy());

and 

addSlide(privacy_policy.newInstance());

resulted in errors

**Comment by cortinico** [comment]
Please check the code I pushed in this branch: https://github.com/AppIntro/AppIntro/commit/15ae1970eab6956ca86e3d272302422764699e2a
It contains a sample fragment that implements the `ISlidePolicy`. It works just fine with the `newInstance()` method. I'm closing #760 because of this.
