### ISSUE TITLE
Custom font problem

### ISSUE THREAD

**Issue by xcesaralejandro** [AppIntro/AppIntro#761]
**Package:** com.github.AppIntro:AppIntro:5.1.0
**Phone:** Google Pixel XL and Emulator Nexus 4

**Problem:** 
`sliderPage.setDescTypefaceFontRes(R.font.prime);` Not work 
`sliderPage.setTitleTypefaceFontRes(R.font.octopus);` Set custom font in title and description

**Comment by cortinico** [comment]
Hi @xcesaralejandro Are you able to provide a screenshot?
Also can I ask you to try version `6.0.0-alpha3` and let me know if you still have problems?

**Comment by xcesaralejandro** [comment]
Screenshot:
[https://drive.google.com/file/d/1bsdJIccZKYngtR58kg5YDhb6xbZ5xnM7/view?usp=sharing](With semi bold) - [https://drive.google.com/file/d/19DEBnrOhCPV2YNhgPAsL-NOVsAlKjKAy/view?usp=sharing](With regular weight) .

All fonts are downloaded from google fonts.

When i use `6.0.0-alpha3` that functions work fine!!

**Comment by cortinico** [comment]
Great so I'm going to close this.
I had some troubles finishing the release of `6.0.0` but hopefully it will be out soon 👍
