### ISSUE TITLE
.appintrox package name for androix support

### ISSUE THREAD

**Issue by fanky10** [AppIntro/AppIntro#778]
**AppIntro Version**: 6.0.0

**Issue details / Repro steps / Use case background**: Just a suggestion on dividing support vs androidx

**Comment by cortinico** [comment]
Hi @fanky10 
Thanks for your report.

I don't fully understand your request. We migrated to AndroidX long time ago and we don't have dependencies on the support library anymore.

I'm closing this. Feel free to comment if I haven't answered your question
