### ISSUE TITLE
How can I change the text color, size, font ?

### ISSUE THREAD

**Issue by sakibraxa** [AppIntro/AppIntro#780]
Hi,
How can I change the following of a slide
text color
text size
font
and also i dont understand how can i change the dimention of the image used in the slide

Please guide me

right now i m using this code
`
addSlide(AppIntroFragment.newInstance("Welcome to F5", "F5is a Chief",
                R.drawable.ads_a, ContextCompat.getColor(getApplicationContext(),R.color.firstSlideColor)));`

**Comment by cortinico** [comment]
Hi @sakibraxa 
Which version of AppIntro are you using?

**Comment by sakibraxa** [comment]
implementation 'com.github.AppIntro:AppIntro:5.1.0'

**Comment by cortinico** [comment]
Here what you should do:

* text color/font

You can use this other overload of `AppIntroFragment.newInstance`:
https://github.com/AppIntro/AppIntro/blob/09d0dbe864b5b9bc431a71cc1d9421a555b29c53/appintro/src/main/java/com/github/paolorotolo/appintro/AppIntroFragment.java#L99-L133

That allows you to change Font be specifying another Font Resource.
Moreover you can change the `titleColor` and the `descriptionColor`. 

* text size

You can'd do this out of the box. You need to use a Slide with a custom layout.

**Comment by leCandas** [comment]
This is a really good library but not exposing text size is a really bad decision...
Simply override their style by adding your styles to change text sizes as you wish

`<style name="AppIntroDefaultText" parent="TextAppearance.AppCompat.Body1">
        <item name="android:textColor">@color/appintro_desc_color</item>
        <item name="android:textSize">15sp</item>
        <item name="android:padding">@dimen/appintro_desc_padding</item>
        <item name="android:gravity">center</item>
        <item name="autoSizeMaxTextSize">15sp</item>
        <item name="autoSizeMinTextSize">15sp</item>
        <item name="autoSizeStepGranularity">@dimen/appintro_text_granularity_size</item>
    </style>`
