### ISSUE TITLE
AppIntroCustomLayoutSlide not working

### ISSUE THREAD

**Issue by laz666** [AppIntro/AppIntro#781]
**AppIntro Version**:
com.github.AppIntro:AppIntro:5.1.0 

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

Hi, I am trying to use AppIntroCustomLayoutSlide for a custom layout. I have created the below IntroActivity, but the class AppIntroCustomLayoutSlide is not recognized? It looks like this class has been renamed to AppIntroCustomLayoutFragment, but I cannot access this either?

```
public class IntroActivity extends AppIntro {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

         addSlide(AppIntroCustomLayoutSlide.newInstance(R.layout.myFirstSlide));
}
```

Thanks.

**Comment by cortinico** [comment]
Hi @laz666
We just released AppIntro 6.0.0. Please consider migrating to it.

6.0.0 contains the class `AppIntroCustomLayoutFragment` you actually see on master.

Please let us know if you still have issues.

**Comment by cortinico** [comment]
I'm closing here as this is resolved on our end. Feel free to reopen if it's not

**Comment by djdance** [comment]
@cortinico please could you add this to the Java example. Just as a comment. It will help!
