### ISSUE TITLE
AppIntro activity is always started in immersive mode, setImmersive(false) has no effect

### ISSUE THREAD

**Issue by alexbakker** [AppIntro/AppIntro#782]
**AppIntro Version**: 6.0.0

**Device/Android Version**: Pixel 3a XL / Android 10

**Issue details / Repro steps / Use case background**: I'm in the process of migrating our app to AppIntro 6.0.0 and noticed that the intro starts in immersive mode by default. I tried to disable this behavior with ``setImmersive(false)``, but that appears to have no effect. Explicitly setting ``android:immersive="false"`` for the activity in AndroidManifest also doesn't help.

I have not had to touch this before, as immersive mode was not enabled by default in previous versions, so I don't know if this bug was introduced in 6.0.0 or earlier. 

**Your Code**: Here's a link to my WIP branch: https://github.com/alexbakker/Aegis/blob/d831f50b2ad5d9a56cbf0b5282cbe1bf88abebf3/app/src/main/java/com/beemdevelopment/aegis/ui/IntroActivity.java#L60.

**Stack trace / LogCat**: N/A

**Comment by cortinico** [comment]
Hi @alexbakker 

Thanks for reporting. The method `setImmersive(Boolean)` is not defined inside AppIntro but inside the `Activity` class.

AppIntro instead is by default just hiding the status bar:
https://github.com/AppIntro/AppIntro/blob/77ef9aa33c1dc217b875b48fa9129da1d5073b17/appintro/src/main/java/com/github/appintro/AppIntroBase.kt#L396-L397

You can override this behavior by calling: `showStatusBar(true);`
Side note: by default AppIntro is not starting in Immersive Mode, as immersive mode would hide the navigation bar also. To enable immersive mode you would have to call `setImmersiveMode();`.

Here a couple of screenshots to clarify:

| Status quo | `showStatusBar(true)` | `setImmersiveMode()` |
| -- | -- | -- |
| ![Screenshot_1588679047](https://user-images.githubusercontent.com/3001957/81062596-8ee8fa00-8ed6-11ea-8de1-42c854fdaa69.png) | ![Screenshot_1588679062](https://user-images.githubusercontent.com/3001957/81062614-99a38f00-8ed6-11ea-94ed-5cd472c79858.png) | ![Screenshot_1588679026](https://user-images.githubusercontent.com/3001957/81062624-9f997000-8ed6-11ea-94a4-3cf5ef046c61.png) |

**Comment by alexbakker** [comment]
Thanks for clarifying. That makes a lot more sense.
