### ISSUE TITLE
Using CustomLayoutFragment controls

### ISSUE THREAD

**Issue by jpsemery** [AppIntro/AppIntro#787]
I am using a custom layout fragment for my first intro page and am havin trouble retrieving a textview control (to display a version number). The fragment displays correctly but when I try to get the fragment view to extratc the resource, null is returned
I'm doing this in java.

```
        Fragment fragment = AppIntroCustomLayoutFragment.newInstance(R.layout.app_intro);
        TextView tv = fragment.getView().findViewById(R.id.textView_version); <== getView() returns null
        addSlide(fragment);
```

I tried subclasssing Fragment and using that but I get a cast error

```
IntroFragment fragment = AppIntroCustomLayoutFragment.newInstance(R.layout.app_intro);
error: incompatible types: AppIntroCustomLayoutFragment cannot be converted to IntroFragment
```

is it possible to post a code snippet that shows how to use a custom layout fragment and retrieve a control.

Thanks

jean-Pierre

**Comment by cortinico** [comment]
Hi @jpsemery 
If you need to access the View of a custom fragment, you can't use `AppIntroCustomLayoutFragment` as you're doing as the view is not yet inflated when you're trying to access it.

The advice is to create your custom `Fragment` and retain View references in the `onViewCreated` method:

```java
public class IntroFragment extends Fragment {

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.app_intro, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        TextView tv = view.findViewById(R.id.textView_version);
    }

    public static IntroFragment newInstance() {
        return new IntroFragment();
    }
}
```

**Comment by jpsemery** [comment]
Thanks Nicola, that makes sense now. Works perfectly. Nice addition too. I though the regular slided were a bit restrictive.

**Comment by wal0x** [comment]
It will be great if this example can go to the example fragment. Displaying a toast after clicking on the button already there for instance.

**Comment by cortinico** [comment]
> It will be great if this example can go to the example fragment. Displaying a toast after clicking on the button already there for instance.

Happy to receive a PR about it :)
