### ISSUE TITLE
how to use CustomLayout here ??

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [AppIntro/AppIntro#793]
i am using latest 6.0.0 verison but i am clearly not understand how to implement custom view i hv added one fragment here like this
Intro4 fragment4 = new Intro4();
addSlide (fragment4);

now after adding this fragemnt i want to add 

setTransformer(AppIntroPageTransformerType.Zoom); 

but its shows error why??

and one more thing i am not using kotlin here pls help some java code too here

**Comment by cortinico** [comment]
> setTransformer(AppIntroPageTransformerType.Zoom);

If you're using Java you need to use:

```java
setTransformer(AppIntroPageTransformerType.Zoom.INSTANCE);
```

to set a custom transformer.
