### ISSUE TITLE
Moving to next page programatically and private class members in AppIntroBase

### ISSUE THREAD

**Issue by idish** [AppIntro/AppIntro#795]
Hey guys,
I'm now migrating from AppIntro 5.X to 6. 
The usage of AppIntro in my app was more advanced than the naive supported functionalities in the library. 
One of my custom slides, could "decide" whether or not the user may move to the next slide. My specific use case was a PIN code slide and a confirm PIN code slide that comes afterwards, which in turn verified that it equals to the previously entered PIN. If it equals, it would move the slide forward "automatically" without any user interfere. 
The way I implemented it in AppIntro 5.X is subclassing AppIntro class and created a method that uses the "pager" variable and sets the current page to the next one.

However, AppIntro 6 has migrated most of the protected class variables to private, and now pager is also private. And so, that cannot be implemented without me breaking up the library's API.

I understand the idea behind moving to private, but I think that it prevents a lot of custom behaviour that developers may need in future and extend the intro functionality to their needs.  

My request would be either to be able to have a functionality of moving to the next page programatically, or migrate of the class variables back into protected, or both :)

I would love to hear what you guys think.
Thank you so much for this great library!
 

**AppIntro Version**: 6.0.0

**Comment by cortinico** [comment]
> However, AppIntro 6 has migrated most of the protected class variables to private, and now pager is also private. And so, that cannot be implemented without me breaking up the library's API.

True and I would still agree on having the AppIntroViewPager private for proper encapsulation.

Regarding your specific problem, you can use the `goToNextSlide()` method to achieve your requested behavior:

https://github.com/AppIntro/AppIntro/blob/969039e5aadafbc4fd0b1b33b86142a2dbfc2869/appintro/src/main/java/com/github/appintro/AppIntroBase.kt#L176-L177

**Comment by idish** [comment]
Thanks! Didn't notice the `goToNextSlide()` method.

**Comment by idish** [comment]
Hi @cortinico, Just noted that `goToPreviousSlide()` is a private function, which is needed for my use case, as if the confirm PIN is incorrect, I will programatically return the user to the previous slide.
Can this be fixed?

**Comment by cortinico** [comment]
> Can this be fixed?

Yes this makes sense to be fixed. I'm doing it in #796
