### ISSUE TITLE
Set a gradient background color on AppIntro 6.0

### ISSUE THREAD

**Issue by m-i-n-a-r** [AppIntro/AppIntro#798]
Just a sort of feature request / support question: i'm trying to use a gradient as background of a slide. The readme clearly shows some slides with gradient backgrounds, but doesn't explain how to obtain the same effect. 

I suppose there isn't a specific function to just pass 2 colors, so how should i do it? I could do it using a gradient drawable, but a quicker way would be cool!

side note: i'm using java since i'm working on an old project, but i'd also appreciate a Kotlin solution

**Comment by cortinico** [comment]
Hi @m-i-n-a-r 
Thanks for asking.

As you said, the sample app is using gradient background:
https://github.com/AppIntro/AppIntro/blob/969039e5aadafbc4fd0b1b33b86142a2dbfc2869/example/src/main/java/com/github/appintro/example/ui/mainTabs/intro/DefaultIntro2.kt#L15-L19

> I could do it using a gradient drawable, but a quicker way would be cool!

Adding a gradient drawable is 5 Lines of Code. I consider this quicker and flexible enough to accomodate all the use cases 👍 :

https://github.com/AppIntro/AppIntro/blob/969039e5aadafbc4fd0b1b33b86142a2dbfc2869/example/src/main/res/drawable/back_slide1.xml#L4-L8

**Comment by victor-mcast** [comment]
This does not work for Java (background drawable).

**Comment by cortinico** [comment]
> This does not work for Java (background drawable).

Can you specify in another issue please?

**Comment by victor-mcast** [comment]
```
addSlide(AppIntroFragment.newInstance(
   "Title", "Description", R.drawable.image_drawable_1,
   R.drawable.background_image, Color.WHITE, Color.WHITE, 
   R.font.raleway_medium, R.font.raleway_medium
));

```

Background image drawable above (`R.drawable.background_image`) does not get recognized as a drawable but a simple integer which can only be used as a color.

**Comment by victor-mcast** [comment]
> > This does not work for Java (background drawable).
> 
> Can you specify in another issue please?

Sure.
