### ISSUE TITLE
wrong default argument when RTL in goToNextSlide() method.   

### ISSUE THREAD

**Issue by idish** [AppIntro/AppIntro#800]
The default argument for isLastSlide on the `goToNextSlide()` method is wrong for RTL layouts.
A correct check for RTL layout's last slide would be checking if currentItem - 1 == 0 (double check me on this one please).

Method's signature: `protected fun goToNextSlide(isLastSlide: Boolean = pager.currentItem + 1 == slidesNumber)`

**AppIntro Version**: 6.0.0

**Comment by cortinico** [comment]
Thanks for reporting @idish You're right that's a bug.
The fix is in #802
