### ISSUE TITLE
Back swipe not permitted when slide policy is not respected

### ISSUE THREAD

**Issue by idish** [AppIntro/AppIntro#803]
For a given slide with a slide policy that is not respected, swiping back won't work. 
I would expect that only swiping forward won't be permitted.
Problem relies within the following method:
```kotlin
    private fun userIllegallyRequestNextPage(event: MotionEvent): Boolean {
        if (isASwipeGesture(event, currentTouchDownX, currentTouchDownY) &&
            System.currentTimeMillis() - illegallyRequestedNextPageLastCalled >=
            ON_ILLEGALLY_REQUESTED_NEXT_PAGE_MAX_INTERVAL
        ) {
            illegallyRequestedNextPageLastCalled = System.currentTimeMillis()
            return true
        }

        return false
    }
``` 
IMO that method should make use of the existing `isSwipeForward()` util method as used for permission slides as well.

**AppIntro Version**: 6.0.0

**Comment by cortinico** [comment]
IIRC this was kept for compatibility with the behavior that the `ISlidePolicy` interface was having in AppIntro 4.x

It probably makes sense to update it to allow back-swiping.

**Comment by idish** [comment]
@cortinico Yep, I'm aware that it was the same behaviour since then, But I see no reason to disable back swiping.

**Comment by idish** [comment]
IMHO that should be labeled more as a bug, than a feature request.
