### ISSUE TITLE
Disabling buttons doesn't work

### ISSUE THREAD

**Issue by WolandPL** [AppIntro/AppIntro#804]
**AppIntro Version**: 6.0.0

**Issue details / Repro steps / Use case background**: 
Using isButtonsEnabled = false doesn't seem to work. While debugging I found out that it hides the buttons for a moment, but then the value of isButtonsEnabled is set to true again and again (I think on every page switch). Is there a way to disable all the buttons (leaving only the indicator)?

**Comment by WolandPL** [comment]
More details:

retainIsButtonEnabled is set to true by default and it overwrites isButtonsEnabled in setSwipeLock(false) called from onPageSelected() -> setPermissionSlide()

**Comment by WolandPL** [comment]
> That's a bug. Thanks for reporting 🙏
> The fix is here #808

Great. When can we expect that change to be published?

**Comment by cortinico** [comment]
I think we can release a bugfix in the next weeks. In the meanwhile you can test a patched version as soon as #808 using `master-SNAPSHOT` as version.
