### ISSUE TITLE
Adding control to the offScreenPageLimit property of the viewpager

### ISSUE THREAD

**Issue by idish** [AppIntro/AppIntro#805]
Previously on AppIntro 5.X, the `setOffScreenPageLimit()` API had `protected` visibility level which in turn enabled me to set up the limit to the slides count. 
My use case of AppIntro requires me to dynamically replace fragments (slides), as the user continues paging through the slides.

That use case requires me to have the offScreenPageLimit set to the slides count, so that I'll be able to replace fragments that are loaded multiple steps ahead of the current shown page.

ATM, the `offscreenPageLimit` property is set to `fragments.size` only when the wizard mode is enabled (which is not my case). See:
```kotlin
    protected fun addSlide(fragment: Fragment) {
        if (isRtl) {
            fragments.add(0, fragment)
        } else {
            fragments.add(fragment)
        }
        if (isWizardMode) {
            pager.offscreenPageLimit = fragments.size
        }
        pagerAdapter.notifyDataSetChanged()
    }

```
I would like to be able to set the `offscreenPageLimit` property likewise when wizard mode is disabled.

**AppIntro Version**: 6.0.0

**Comment by cortinico** [comment]
> My use case of AppIntro requires me to dynamically replace fragments (slides), as the user continues paging through the slides.

This is currently not supported (see #709).
Therefore we intentionally hided the visibility of the ViewPager and the `offscreenPageLimit` method to restrict the library to focus on what we actually support.

If you need to dynamically change/replace slides, you probably need to either use another library or create your own introduction with a ViewPager or similar.

**Comment by idish** [comment]
@cortinico I understand that the main intent of the library is to use static slides, but I think that the library should at least be more "friendly" to those who try to make it a little more dynamic.

That would be frustrating that because of a lack of visibility of a single property, one will have to migrate to another library or implement their own.
I can still use the great capabilities of that library even though my use case is a bit different than what's intended to be, and still, I didn't break any API of the library. 
Also, I'm currently at the finish line of the migration of 5.X version to 6, and it's just my last milestone :)

**Comment by cortinico** [comment]
> @cortinico I understand that the main intent of the library is to use static slides, but I think that the library should at least be more "friendly" to those who try to make it a little more dynamic.

Agree on the general point. On the other hand, I don't think that exposing `offScreenPageLimit` will make the API more "friendly". It seems like this would solve your specific scenario.

Dynamic loading of slides is not supported at the moment. When we will support it, we will evaluate which property/features to expose.

> That would be frustrating that because of a lack of visibility of a single property, one will have to migrate to another library or implement their own.''
> I can still use the great capabilities of that library even though my use case is a bit different than what's intended to be, and still, I didn't break any API of the library.

If a visibility of a single property/method is preventing you from using this library at all, you should probably consider either forking it or using reflection to [change the visibility](https://docs.oracle.com/javase/10/docs/api/java/lang/reflect/AccessibleObject.html#setAccessible(boolean)).

**Comment by idish** [comment]
@cortinico Thanks, I totally understand that.

> If a visibility of a single property/method is preventing you from using this library at all, you should probably consider either forking it or using reflection to change the visibility.

Thank you for the suggestions.
