### ISSUE TITLE
expose isRtl property

### ISSUE THREAD

**Issue by idish** [AppIntro/AppIntro#806]
`askForPermissions()` API requires a slide number. 
The slide numbers differs when the layout is in RTL or not.
That means I have to check if the layout is RTL, and if it is, the slide number will differ when it isn't.
I'm aware of that the logic is fairly simple, but it would be nicer if it would just have `protected` visibility to prevent multiple implementations across the app :)

**AppIntro Version**: 6.0.0

**Comment by cortinico** [comment]
Make sense as a util function. I'm adding it 👍

**Comment by AnuthaDev** [comment]
If I may interject here, the slide numbers for askForPermissions() should stay the same, regardless of RTL status, it should be fixed if that's not the case right now

**Comment by cortinico** [comment]
> If I may interject here, the slide numbers for askForPermissions() should stay the same, regardless of RTL status, it should be fixed if that's not the case right now

Yup you're right my bad.

As @AnuthaDev suggested, you need to specify absolute slideNumber in the `askForPermissions` method. It will be properly converted based on RTL/LTR.
