### ISSUE TITLE
Solid color for unselected dots in the indicator

### ISSUE THREAD

**Issue by WolandPL** [AppIntro/AppIntro#811]
The unselected dots in the indicator are partially transparent. Is there a way to get them in solid color, other than implementing custom `IndicatorController `from scratch? I'd love to inherit from `DotIndicatorController` and just override `selectPosition()`, but that's not possible.

**Comment by cortinico** [comment]
> Is there a way to get them in solid color, other than implementing custom `IndicatorController `from scratch?

It's not officially supported, but you can provide a color resource called `appintro_default_unselected_color`. 

https://github.com/AppIntro/AppIntro/blob/0a2f73226e04a4cdb5ebb7929e7a3e23a2123422/appintro/src/main/res/values/colors.xml#L11

The default color has a transparency and is used as base for tinting. If you provide a color that has no transparency you can achieve the desired behavior without having to create another class.

**Comment by WolandPL** [comment]
@cortinico Thanks! Works perfectly!
