### ISSUE TITLE
setSwipeLock(true) won't work 

### ISSUE THREAD

**Issue by idish** [AppIntro/AppIntro#819]
Setting the swipe lock to true, won't be working as it would be overriden with a `false` value at `setPermissionSlide()` method if the current slide isn't a permission slide, originally called from `onPageSelected()` callback.

**AppIntro Version**: 6.0.0

**Comment by cortinico** [comment]
Yeah that's a bug, thanks for reporting it 👍 
It should be a really trivial fix.
