### ISSUE TITLE
Description text cut off on small screens

### ISSUE THREAD

**Issue by StainlessStlRat** [AppIntro/AppIntro#820]
Is it possible to have the default app intro be vertically scrollable? The biggest issue is I can't control the length of translated text.

![103455202_549542775740338_4888401875584714276_n](https://user-images.githubusercontent.com/16851186/84236938-54621680-aaad-11ea-986c-7332b6ce7731.png)

**Comment by cortinico** [comment]
Hey @StainlessStlRat 
It's already vertically scrollable. Have you tried to run the app and encountered problems?

**Comment by StainlessStlRat** [comment]
Oh it is? I don't have a small screen but I was getting reports from a friend that it wasn't. He is on an earlier API but he definitely tried. I'll test on API 22 with a small screen on the emulator

**Comment by StainlessStlRat** [comment]
Ya I just tried on emulator on API 22 with a small screen and was unable to scroll vertically unfortunately

**Comment by cortinico** [comment]
Sorry I miss-understood, I though your issue was related to the AppIntro sample app. To have a scrollable layout, the suggestion is to use https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/java/com/github/appintro/AppIntroCustomLayoutFragment.kt

**Comment by StainlessStlRat** [comment]
Ok thanks
