### ISSUE TITLE
How to apply Parallax() animation in customlayout

### ISSUE THREAD

**Issue by eggham0518** [AppIntro/AppIntro#823]
setTransformer(AppIntroPageTransformerType.Parallax()) not working
Other animations work.

**Comment by cortinico** [comment]
The `Parallax()` transformer works only for not custom layout.
The reason behind it is that it needs to access the views inside your layout to animate them:

https://github.com/AppIntro/AppIntro/blob/a2030fb5738c1e47046b1e69b5e3fbfedf0ee780/appintro/src/main/java/com/github/appintro/internal/viewpager/ViewPagerTransformer.kt#L54-L58

So if you happen to have:
- A `TextView` with id `title`
- A `TextView` with id `description`
- An `ImageView` with id `image`
Those will be animated. The rest of the layout won't.

**Comment by eggham0518** [comment]
That's great. Thank you for the nice library.
