### ISSUE TITLE
Backround Image Drawable does not work for Java

### ISSUE THREAD

**Issue by victor-mcast** [AppIntro/AppIntro#830]
```
addSlide(AppIntroFragment.newInstance(
   "Title", "Description", R.drawable.image_drawable_1,
   R.drawable.background_image, Color.WHITE, Color.WHITE, 
   R.font.raleway_medium, R.font.raleway_medium
));

```
Background image drawable above (R.drawable.background_image) does not get recognized as a drawable but a simple integer which can only be used as a color.

**Comment by cortinico** [comment]
Hi @victor-mcast 
If you're using Java, you can't use Kotlin named parameters. Therefore you have to respect the parameter ordering of the `newInstance` method and provide values for missing params. 

https://github.com/AppIntro/AppIntro/blob/068ccd2424e4c626c637ad1ca8dda662c4b3f1cd/appintro/src/main/java/com/github/appintro/AppIntroFragment.kt#L35-L45

In your case the code should become:

```java
addSlide(AppIntroFragment.newInstance(
   "Title", 
   "Description", 
   R.drawable.image_drawable_1,
   0, 
   Color.WHITE, 
   Color.WHITE, 
   R.font.raleway_medium, 
   R.font.raleway_medium,
   R.drawable.background_image
));
```

**Comment by victor-mcast** [comment]
> Hi @victor-mcast
> If you're using Java, you can't use Kotlin named parameters. Therefore you have to respect the parameter ordering of the `newInstance` method and provide values for missing params.
> 
> https://github.com/AppIntro/AppIntro/blob/068ccd2424e4c626c637ad1ca8dda662c4b3f1cd/appintro/src/main/java/com/github/appintro/AppIntroFragment.kt#L35-L45
> 
> In your case the code should become:
> 
> ```java
> addSlide(AppIntroFragment.newInstance(
>    "Title", 
>    "Description", 
>    R.drawable.image_drawable_1,
>    0, 
>    Color.WHITE, 
>    Color.WHITE, 
>    R.font.raleway_medium, 
>    R.font.raleway_medium,
>    R.drawable.background_image
> ));
> ```

That solved the problem. Thanks!

**Comment by victor-mcast** [comment]
Sorry, I followed your suggestion but its still not working. The background is now black! The code I'm using is the following:

```
addSlide(AppIntroFragment.newInstance(
                "Title", "Description", R.drawable.onboard_art_1,
                0, Color.WHITE, Color.WHITE, R.font.raleway_medium, R.font.raleway_medium,
                R.drawable.onboard_bg_1
        ));
```

**Comment by victor-mcast** [comment]
@cortinico Please take note.

**Comment by cortinico** [comment]
> @cortinico Please take note.

Please don't ping people and allow time to respond (min 24 hours). You posted one hour ago...

The code you posted is correct.
I've also checked the library code and it looks right on my end. My suspect is that there are some problem with your resources.

I'm not able to investigate further without a project that I can run locally.

**Comment by victor-mcast** [comment]
I'm using the gradient drawable you have suggested in the issue noted here: [Set a gradient background color on AppIntro 6.0 #798](https://github.com/AppIntro/AppIntro/issues/798)
```
 <gradient 
     android:startColor="#B06AB3" 
     android:endColor="#4568DC" 
     android:type="linear" 
     android:angle="315"/>
```

**Comment by cortinico** [comment]
Again, the code you posted here https://github.com/AppIntro/AppIntro/issues/830#issuecomment-648046706 is correct. I've just tested it in the same app and it works fine.

> I'm not able to investigate further without a project that I can run locally.

Please provide a project we can test locally.

**Comment by victor-mcast** [comment]
Well, I just figured out why the background drawable was not being applied. I was experimenting with the color backgrounds before I decided to change to background drawables. For the color backgrounds I had `setColorTransitionsEnabled(true)`. This was the culprit. Using this method will forcibly remove the background drawables. I suggest you update your documentation about this. Thanks.

**Comment by teekamsuthar** [comment]
> Well, I just figured out why the background drawable was not being applied. I was experimenting with the color backgrounds before I decided to change to background drawables. For the color backgrounds I had `setColorTransitionsEnabled(true)`. This was the culprit. Using this method will forcibly remove the background drawables. I suggest you update your documentation about this. Thanks.

Thanks, you saved my day!
