### ISSUE TITLE
Add option to change color of next and skip button

### ISSUE THREAD

**Issue by pradyum619** [AppIntro/AppIntro#837]
Please add the feature for changing the color or tint of next and skip button inside APPIntro2

**Comment by Nikoloutsos** [comment]
I guess a solution is to create your own fragments :/ 
I thought that I would do that in the constructor but apparently I cannot

**Comment by cortinico** [comment]
> I guess a solution is to create your own fragments :/

Nope that doesn't work as those buttons are outside of the Fragment.

The immediate workaround is to provide your own `R.layout.appintro_intro_layout2` (it should be named like this). Your resource will override the library resource and you can customize the whole layout.

Please note that this is not part of the API and it might break once we release a new version of AppIntro.

Propert setters for the colors of those buttons should be provided inside `AppIntro2`. A PR is more than welcome 👍

**Comment by cortinico** [comment]
Reopening as this is a good first-issue

**Comment by anesabml** [comment]
Hi @cortinico, Can I work on this?

**Comment by cortinico** [comment]
> Hi @cortinico, Can I work on this?

Seems like #869 was faster
