### ISSUE TITLE
Disabling buttons not working from Java

### ISSUE THREAD

**Issue by doneill** [AppIntro/AppIntro#838]
**AppIntro Version**:
6.0.0

**Device/Android Version**:
Fails on Samsung Galaxy s9, Pixel 3 Android 10

**Issue details / Repro steps / Use case background**: 
`setButtonsEnabled(false)` not working as expected as the buttons are not disabled. 

<img width="450" alt="buttons-not-disabled" src="https://user-images.githubusercontent.com/1308001/88865899-f9e85b00-d1bd-11ea-80e4-4aa3d5400379.png">

Setting `isButtonsEnabled = false` works in Kotlin, additionally `setSkipButtonEnabled(false)` is working from Java.  Source seems to step through `updateButtonVisibility()` correctly, but buttons visibility not changing.

**Your Code**: 

```java
public class SomeClass extends AppIntro2 {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    addSlide(Fragement.newInstance());
    addSlide(Fragement.newInstance());
    addSlide(Fragement.newInstance());

    setButtonsEnabled(false);
  }
}
```

**Comment by cortinico** [comment]
Hi @doneill 
Thanks for the report.

I'm unfortunately unable to reproduce. This is what your code produces:

<img width=60% src="https://user-images.githubusercontent.com/3001957/88891679-dbc53e00-d243-11ea-9b5c-f73c06001dfb.gif" />

Buttons are correctly hidden.

> Setting isButtonsEnabled = false works in Kotlin

As a rule of thumb, there are no behavior changes between Java and Kotlin.
Please verify again and let me know if the issue still persists.

**Comment by doneill** [comment]
Sure enough, creating a Java example in your example app works

```java
public class CustomJavaIntro extends AppIntro2 {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        addSlide(AppIntroCustomLayoutFragment.newInstance(R.layout.intro_custom_layout1));
        addSlide(AppIntroCustomLayoutFragment.newInstance(R.layout.intro_custom_layout2));
        addSlide(AppIntroCustomLayoutFragment.newInstance(R.layout.intro_custom_layout3));
        addSlide(AppIntroCustomLayoutFragment.newInstance(R.layout.intro_custom_layout4));

        setButtonsEnabled(false);
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        finish();
    }
}
```


Thanks for confirming, I'll keep trying to figure it out.

**Comment by adriamt** [comment]
Same here but in Kotlin.

I have this code 
```
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        addSlide(AppIntroCustomLayoutFragment.newInstance(R.layout.slide_1_fragment))
        addSlide(AppIntroCustomLayoutFragment.newInstance(R.layout.slide_2_fragment))
        addSlide(AppIntroCustomLayoutFragment.newInstance(R.layout.slide_3_fragment))

        isButtonsEnabled = false
   }
```
And my buttons keep showing.
And if I write 
```
    override fun onResume() {
        super.onResume()
        isButtonsEnabled = false
    }
```
Only the first fragments hides the buttons, but only the first time it's showing, If I go back from the second one, they show again.

**Comment by adriamt** [comment]
@cortinico I've been digging a little bit more.

With the code I've provided on the comment before, first of all is executed 
`isButtonsEnabled = false`
Wich triggers `updateButtonsVisibility()` and sets visibility to false.

Then `updateButtonsVisibility()` it's called again from the `onPageSelected` functions, but the visibility it's still false, so it's ok too at this points.

The problem comes, when `setPermissionSlide() ` it's called on the else branch, and sets `setSwipeLock(false)` this causes to execute `this.isButtonsEnabled = retainIsButtonEnabled` where the `retainIsButtonEnabled` it's true, so at this point, the `isButtonsEnabled` is true again and `updateButtonsVisibility()` it's called again

**Comment by adriamt** [comment]
I've I write this 
 ```
isButtonsEnabled = false
setSwipeLock(true)
isButtonsEnabled = false
```
I can bypass the error and the buttons are not shown

**Comment by cortinico** [comment]
Can I ask you to verify if this is still happening on the latest master? 

I believe this was fixed several weeks ago: https://github.com/AppIntro/AppIntro/pull/808
If this is the case, we should probably release a new version soon 👌

**Comment by adriamt** [comment]
I've used 
`implementation 'com.github.AppIntro:appintro:master-SNAPSHOT'` to use master from jitpack.
And now with only on `isButtonsEnabled = false` it worked like charm.

Now it hides the buttons !!

**Comment by cortinico** [comment]
Fantastic, it will be released in the upcoming fix.

**Comment by adriamt** [comment]
@cortinico any clue when will be up the new version?

**Comment by cortinico** [comment]
> @cortinico any clue when will be up the new version?

We don't have ETA, but definitely we want to wait for #878 #887 #863 to be merged.
