### ISSUE TITLE
isPolicyRespected() also prevents user from swiping back to the previous slide *JAVA*

### ISSUE THREAD

**Issue by LassassinX** [AppIntro/AppIntro#841]
**AppIntro Version**: 6.0.0

**Device/Android Version**: SAMSUNG SM-A20F

**Issue details / Repro steps / Use case background**: Hello, i wish to prevent my user from accessing the next slide unless they press a button. However, using the isPolicyRespected() also prevents the user from swiping to the previous slide as well. When in wizard mode, I can use the back button to go back to the slide, but I cannot swipe and go back to the slide. Anyway to fix this ? I am using java

EDIT: I have tried to use the setNextPageSlideLock(true), but it doesn't work. Putting setSwipeLock(true) in the onSlideChanged() method works, but that is not what I'm looking for, as it disables both forward and reverse swiping. I want my users to be able to swipe back, but not swipe forwards. The updated code is below 

**Your Code**:  
//MainActivity
        
       @Override
        protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        welcomeSlide = WelcomeSlide.newInstance(ColorEx.WHITE);
        loginSlide = LoginSlide.newInstance(ColorEx.WHITE);
        teacherOrStudentSlide = TeacherOrStudentSlide.newInstance(ColorEx.TUTOR_BEAR_DARK_BLUE);
        createMyAccountSlide = CreateMyAccountSlide.newInstance(ColorEx.TUTOR_BEAR_DARK_BLUE);

        addSlide(welcomeSlide);
        addSlide(loginSlide);
        addSlide(teacherOrStudentSlide);
        addSlide(createMyAccountSlide);

        setColorTransitionsEnabled(true);

        setWizardMode(true);

        setSkipButtonEnabled(false);

        setDoneText("");

        changeIndicatorColor("Dark Blue");

    }

    @Override
    protected void onSlideChanged(Fragment oldFragment, Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        if (newFragment == loginSlide) {
            changeIndicatorColor("Dark Blue");
        }

        if (newFragment == teacherOrStudentSlide) {
            setNextPageSwipeLock(true);
            changeIndicatorColor("White");
        }

    }

//TeacherOrStudent class

      private static final String ARG_COLOR_INT = "COLOR_INT";
    private int originalColor = 0;
    private ConstraintLayout background = null;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        originalColor = getArguments().getInt(ARG_COLOR_INT);
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.teacher_or_student_slide_layout, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @androidx.annotation.Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        background = view.findViewById(R.id.teacher_or_student_slide_constraint_layout);
    }

    public static TeacherOrStudentSlide newInstance(@ColorInt int originalColor) {
        TeacherOrStudentSlide newFragment = new TeacherOrStudentSlide();
        Bundle args = new Bundle();
        args.putInt(ARG_COLOR_INT, originalColor);
        newFragment.setArguments(args);
        return newFragment;
    }

    @Override
    public int getDefaultBackgroundColor() {
        return originalColor;
    }

    @Override
    public void setBackgroundColor(int backgroundColor) {
        background.setBackgroundColor(backgroundColor);
    }

    @Override
    public boolean isPolicyRespected() {

        return false;
    }

    @Override
    public void onUserIllegallyRequestedNextPage() {
        Toast.makeText(getContext(), "Please select if you are a Teacher of Student!", Toast.LENGTH_SHORT).show();
    }
//TeacherOrStudent xml

      <?xml version="1.0" encoding="utf-8"?>

      <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
       xmlns:app="http://schemas.android.com/apk/res-auto"
       xmlns:tools="http://schemas.android.com/tools"
       android:layout_width="match_parent"
       android:layout_height="match_parent"
       android:id="@+id/second_slider_constraint_layout">

    <ImageView
        android:id="@+id/imageView6"
        android:layout_width="@dimen/_271sdp"
        android:layout_height="@dimen/_146sdp"
        android:layout_marginStart="2dp"
        android:src="@drawable/slider_two_background"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.025" />

    <TextView
        android:id="@+id/textView4"
        android:layout_width="@dimen/_280sdp"
        android:layout_height="wrap_content"
        android:alpha=".9"
        android:fontFamily="@font/roboto_regular"
        android:text="Are you a teacher or a student ?"
        android:textAlignment="center"
        android:textColor="#ffffff"
        android:textSize="@dimen/_34sdp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/imageView6"
        app:layout_constraintVertical_bias="0.100000024" />

    <Button
        android:id="@+id/teacher_button"
        style="@style/Widget.AppCompat.Button.Borderless"
        android:layout_width="@dimen/_210sdp"
        android:layout_height="@dimen/_40sdp"
        android:background="@drawable/button_background_orange"
        android:fontFamily="@font/kiona_regular"
        android:text="I AM A TEACHER"
        android:onClick="iAmTeacher"
        android:textColor="#f68c1e"
        android:textSize="@dimen/_19sdp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView4"
        app:layout_constraintVertical_bias="0.26" />

    <Button
        android:id="@+id/student_button"
        style="@style/Widget.AppCompat.Button.Borderless"
        android:layout_width="@dimen/_210sdp"
        android:layout_height="@dimen/_40sdp"
        android:background="@drawable/button_background"

        android:fontFamily="@font/kiona_regular"
        android:text="I AM A STUDENT"
        android:textColor="#0784c3"
        android:textSize="@dimen/_19sdp"
        android:onClick="iAmStudent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/teacher_button"
        app:layout_constraintVertical_bias="0.26999998" />

      </androidx.constraintlayout.widget.ConstraintLayout>

**Stack trace / LogCat**: No error
```ruby
No error
```

**Comment by cortinico** [comment]
> Hello, i wish to prevent my user from accessing the next slide unless they press a button. However, using the isPolicyRespected() also prevents the user from swiping to the previous slide as well.

This assumption is not correct.

The `SlidePolicy` feature actually offers this behavior:
https://github.com/AppIntro/AppIntro/blob/a2dc94bf103c720ad5537f3636771489b0f6166b/appintro/src/main/java/com/github/appintro/internal/AppIntroViewPager.kt#L162-L171

Have you tried and it was not working, or it was a bug in the documentation?

As for the `setNextPageSlideLock`, I suggest we `@Deprecate` it from the library @paolorotolo. The behavior is not really consistent with the rest of the library and is just complicating the code imho.

**Comment by mase7569** [comment]
Same behaviour here, back swipe doesn't work when isPolicyRespected returns false. A bug right?

**Comment by cortinico** [comment]
> Same behaviour here, back swipe doesn't work when isPolicyRespected returns false. A bug right?

If you experience this, is probably a bug. However as previously mentioned, I was not able to reproduce.
Can I ask you to provide a reproducer and/or open a new issue?

**Comment by mase7569** [comment]
AppIntroViewPager.kt, java generated version looks like this in my project (using v 6.0.0):

```
                // If user can't request the page, we shortcircuit the ACTION_MOVE logic here.
                // We need to return false, and also call onIllegallyRequestedNextPage if the
                // threshold was too high (so the user can be informed).
                if (!canRequestNextPage) {
                    if (userIllegallyRequestNextPage(event)) {
                        onNextPageRequestedListener?.onIllegallyRequestedNextPage()
                    }

                    return false
                }
```
