### ISSUE TITLE
Wizard mode back button color 

### ISSUE THREAD

**Issue by LassassinX** [AppIntro/AppIntro#844]
**AppIntro Version**: 6.0.0.

**Device/Android Version**: Pixel 2 API 29

**Issue details / Repro steps / Use case background**: Is there any way to color the back button in wizard mode ? Like the setNextArrowColor(); sets the color of the next button. Is there any way to set the back arrow color during wizard mode ?

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by cortinico** [comment]
Have you tried to use the `setBackArrowColor` method?

**Comment by LassassinX** [comment]
any update on this issue ?

**Comment by cortinico** [comment]
The method actually exists on `master`. Was added by this PR: https://github.com/AppIntro/AppIntro/pull/825
Will be available in the upcoming version of AppIntro
