### ISSUE TITLE
setTransformer() not working in Java based code

### ISSUE THREAD

**Issue by JuzerTaher** [AppIntro/AppIntro#845]
**AppIntro Version**: 6.0.0

**Device/Android Version**: 4.0.1

**Issue details / Repro steps / Use case background**: The setTransformer() is not working in my Java code.

**Your Code**:  addSlide(AppIntroCustomLayoutFragment.newInstance(R.layout.app_intro_2));

        setTransformer(AppIntroPageTransformerType.Zoom);

**Stack trace / LogCat**:  error: cannot find symbol
        setTransformer(AppIntroPageTransformerType.Zoom);
                                                  ^
  symbol:   variable Zoom
  location: class AppIntroPageTransformerType

```ruby
paste stack trace and/or log here
```

**Comment by LassassinX** [comment]
Please use setTransformer(AppIntroPageTransformerType.Zoom.INSTANCE);
