### ISSUE TITLE
Drawable overlaps the title in case title is 3 lines or moe

### ISSUE THREAD

**Issue by peterhav** [AppIntro/AppIntro#849]
**AppIntro Version**: 6.0.0

fails on Galaxy S4/GT-I9500 4.4.2, works fine on Nexus 6P 5.1 and Genymotion Nexus 5 5.0.1 -->
SM-A510F

**Issue details / Repro steps / Use case background**: 
Title in the appintro_fragment_intro.xml does not show correct when it covers 3 lines (lowest line is only showing half)

**Your Code**: 
```
        p.backgroundColor = ContextCompat.getColor(this, R.color.colorInstance4)
        p.imageDrawable = R.drawable.ic_tutorial3
        p.description = getString(R.string.body_tutorial3)
        p.title = getString(R.string.title_tut3)
        addSlide(AppIntroFragment.newInstance(p))
```

**Stack trace / LogCat**:
N/A

Personal workaround fix is to use these constraintlayout values instead of the existing in the layout XML:

For the title view:
app:layout_constraintVertical_weight="3"

For the image view:
app:layout_constraintVertical_weight="4"

**Comment by cortinico** [comment]
Thanks for the report,

> For the title view:
> app:layout_constraintVertical_weight="3"
> 
> For the image view:
> app:layout_constraintVertical_weight="4"

This is anyway not solving the issue in the long run.
Ideally you should use a https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/java/com/github/appintro/AppIntroCustomLayoutFragment.kt and provide a layout that has enough spacing for your content.

**Comment by peterhav** [comment]
Great tip; I will use that and close this one. Thanks.
