### ISSUE TITLE
Add Java example to the sample app

### ISSUE THREAD

**Issue by cortinico** [AppIntro/AppIntro#850]
We should consider adding one intro example in Java inside the example App.
We keep on receiving several support questions that are Java related. Ideally having one sample in Java could provide an easier example that users can use.

**Comment by chetanmuliya** [comment]
I'll work on this issue

**Comment by cortinico** [comment]
> I'll work on this issue

I've assigned this issue to you @chetanmuliya Please let me know if you need some support 🙏

**Comment by chetanmuliya** [comment]
Ya Sure, thank you

**Comment by chetanmuliya** [comment]
@cortinico I added java example app please review it, thank you
