### ISSUE TITLE
setIndicatorColor does not change indicator color unless I override appintro_default_unselected_color

### ISSUE THREAD

**Issue by bmalex88** [AppIntro/AppIntro#855]
There's some strange behavior happening when using `setIndicatorColor`. It does not appear to change the dot indicators' colors. Only if I override `appintro_default_unselected_color` in my _colors.xml_ file it works. But if I override the color yet not use `setIndicatorColor`, it does not work either.

**AppIntro Version**: 6.0.0
**Device/Android Version**: Galaxy S8

**Issue details / Repro steps / Use case background**: 

Use `setIndicatorColor` without overriding `appintro_default_unselected_color` or override `appintro_default_unselected_color` without using `setIndicatorColor` and the color of the indicator dots does not change.

**Your Code**: 

    setIndicatorColor(
        ContextCompat.getColor(this, R.color.selectedIndicatorColor),
        ContextCompat.getColor(this, R.color.unselectedIndicatorColor)
    )

In _colors.xml_ I have to add

    <color name="appintro_default_unselected_color">#79cee4</color>

**Comment by cortinico** [comment]
> **Issue details / Repro steps / Use case background**:
> 
> Use `setIndicatorColor` without overriding `appintro_default_unselected_color` or override `appintro_default_unselected_color` without using `setIndicatorColor` and the color of the indicator dots does not change.

This actually works. The reality is that the provided colors are blended with the default colors (that have a alpha and are really dark).

Therefore, you need to override `appintro_default_unselected_color` to properly see the color you provide.

I'm fixing this behavior in #856

**Comment by bmalex88** [comment]
I see, thank you
