### ISSUE TITLE
improved sw600 builtin layout support

### ISSUE THREAD

**Issue by gyund** [AppIntro/AppIntro#859]
**AppIntro Version**: 6.0.0

**Device/Android Version**: N/A

**Issue details / Repro steps / Use case background**: 
This intro is great out of the box! The one thing I would suggest adding is layouts for tablets is larger area for the imageDrawable. It seems to be an imageView that works fine for phones but since the size is the same, it is small on a tablet (tempted to make it bigger right now though). There's a ton of real-estate :) 

I would also say font size as well but not sure if that would cause accessibility issues for people already using scaled fonts and it could be app specific (depending on the amount of text of people already using this). At that point, it's probably just better to sub in your own fragment maybe, but a bit of work for just a few size changes to an already nice setup.

**Your Code**: N/A

**Stack trace / LogCat**:
```ruby
N/A
```

**Comment by cortinico** [comment]
> This intro is great out of the box! The one thing I would suggest adding is layouts for tablets is larger area for the imageDrawable. It seems to be an imageView that works fine for phones but since the size is the same, it is small on a tablet (tempted to make it bigger right now though). There's a ton of real-estate :)

Do you have a screenshot to share?

> At that point, it's probably just better to sub in your own fragment maybe, but a bit of work for just a few size changes to an already nice setup.

Agree on this. We already have problems on people using big blocks of texts that gets truncated at the third line. Ideally a custom layout would do the job on that front.

**Comment by gyund** [comment]
Sure :) 
https://photos.app.goo.gl/B4owTEokmZ5xi1Ph7
