### ISSUE TITLE
How can hide skip and done button

### ISSUE THREAD

**Issue by khaledhnAbusair** [AppIntro/AppIntro#867]
How can hide skip and done button

**Comment by cortinico** [comment]
You can use the `isButtonEnabled` property on `AppIntroBase`

https://github.com/AppIntro/AppIntro/blob/3479f4f5916a8f11e7ec6c7d7efe25b0affe9d03/appintro/src/main/java/com/github/appintro/AppIntroBase.kt#L53-L58
