### ISSUE TITLE
Add button to slide

### ISSUE THREAD

**Issue by badoyg** [AppIntro/AppIntro#882]
I have this code:

addSlide(AppIntroFragment.newInstance(
                title = "Welcome...",
                description = "This is the first slide of the example"
        ))

Is there a way to add a simple button on the slide itself?

**Comment by cortinico** [comment]
> Is there a way to add a simple button on the slide itself?

The easiest way is to use `AppIntroCustomLayoutFragment` as described here:
https://github.com/AppIntro/AppIntro#appintrocustomlayoutfragment

**Comment by badoyg** [comment]
Thank you for your reply. And thank you for this library; it's great! 

But, can you please add a button feature in the next release? Your competitor (https://github.com/heinrichreimer/material-intro#screenshots) has this feature and it's the only advantage it has over your library. Many people said this.
It should only take a few minutes.

Having the option to add a button on a slide is more efficient compared to creating a custom layout from scratch.

**Comment by cortinico** [comment]
> Having the option to add a button on a slide is more efficient compared to creating a custom layout from scratch.

I'd argue that is not more efficient. We prefer to have a streamlined library (that is already quite big), so that you can customize it as you wish 👍

**Comment by badoyg** [comment]
I meant it's more efficient for people in my situation who need a button on their slides.

**Comment by badoyg** [comment]
If won't implement that feature, Is there a  Fork that already did?

**Comment by cortinico** [comment]
> If you won't implement that feature, Is there a Fork that already did?

Not that I'm aware of
