### ISSUE TITLE
Remove arrow on the left

### ISSUE THREAD

**Issue by badoyg** [AppIntro/AppIntro#889]
An arrow is pointing to the left even though There is no slide on the left, the slides are only on the right. How do I remove the left when there are no slides on the left ( basically when it's the 1st slide)??

**Comment by cortinico** [comment]
Can you please share more details? There are no arrows left by default (only if you enable wizard mode). Are you referring to the Skip button?

**Comment by badoyg** [comment]
I enabled wizard mode and there is arrow left on the first slide which shouldn't appear

**Comment by cortinico** [comment]
Yup you're right. That's a but. Fix is in #891
