### ISSUE TITLE
Orientation changes make views unreachable

### ISSUE THREAD

**Issue by cyb3rko** [AppIntro/AppIntro#893]
**AppIntro Version**:
6.0.0

**Device/Android Version**:
Samsung Galaxy S7/Android 8.0.0, Google Pixel 4 Emulator/Android 11

**Issue details / Repro steps / Use case background**:  
*UPDATE*:
As I just figured out also your example slide policy fragment does crash.

I didn't specify any orientation in the Manifest on my AppIntro actvity so orientation changes are allowed.
It works, it also changes the portrait layout to a landscape layout, but if the layout changes I can not get the binding/view of any fragment anymore. It always crashes when I want to access the view and e.g. check the state of checkboxes.

It seems like there`s something wrong in how the lifecycle is used to recreate the view.
Is there a workaround?

**Your Code / LogCat**: 
1. using single views
In my onCreateView method of my custom fragment I initialize my checkbox like so:
`checkBox1 = view.findViewById(R.id.terms_of_use_check)`
If I wanna get the state as the `isPolicyRespected` value, it crashes and says `NullPointerException at getBinding`.

2. using viewBinding (for source go [HERE](https://github.com/cyb3rko/AppIntroCrash))
In my onCreateView method of my custom fragment I initialize my binding like so:
`_binding = FragmentIntroBinding.inflate(layoutInflater, container, false)`
If I wanna get the state as the `isPolicyRespected` value, it crashes and says `NullPointerException at getBinding`.

**Example video**:
https://youtube.com/watch?v=i650NLLtR_8

**Comment by cortinico** [comment]
> It always crashes when I want to access the view and e.g. check the state of checkboxes.

Are you able to provide a reproducer project?
I've tried locally to construct a layout with a checkbox and it works fine on my end.
If you could share the code of your Fragment + the layout file, that would already be a starting point.

> In my onCreateView method of my custom fragment

You should consider moving your `findViewById` inside the `onViewCreated` method.

**Comment by cyb3rko** [comment]
Ok, I'll will make a simple example repo. Let`s see if it works there.

**Comment by cyb3rko** [comment]
@cortinico As findViewById will get deprecated I switched to viewBinding, but that also does not work.

I added description and the sample code in the issue description above.

**Comment by cyb3rko** [comment]
@cortinico  As I just figured out also your example slide policy fragment does crash.

**Comment by cortinico** [comment]
> You should consider moving your `findViewById` inside the `onViewCreated` method.

Have you tried this?

**Comment by cyb3rko** [comment]
Not yet, but you did it like that in your example:  https://github.com/AppIntro/AppIntro/blob/e9d9e33d98b91b7913cb57fb06623fa19e1ba009/example/src/main/java/com/github/appintro/example/ui/custom/fragments/CustomSlidePolicyFragment.kt#L25

**Comment by cyb3rko** [comment]
@cortinico Is it still incomplete or have I provided enough information (especially because your example is enough information)?

**Comment by cortinico** [comment]
> Is it still incomplete or have I provided enough information (especially because your example is enough information)?

Unfortunately I'm still unable to reproduce. The sample app works fine for me (even when trying to rotate multiple times). Can you provide:

- Precise steps to reproduce crash in the sample app
- A full stacktrace of the crash

**Comment by cyb3rko** [comment]
- Steps to reproduce a crash in the sample app
  - Installed latest appintro-sample-app-stable.apk from [HERE](https://github.com/AppIntro/AppIntro/actions/runs/339402765)
  - Opened it and clicked on Start button of "Slide Policy Intro"
  - Swiped to second slide
  - rotated phone from portrait to landscape
  - clicking anywhere --> CRASH

- A full stacktrace of the crash: https://gist.github.com/cyb3rko/0b299c4428427fc1af9329e54ceb3e75
(Used gist for better indentation and readability)

**Comment by cortinico** [comment]
Yup you're right. Thanks for your clarification.
This should be the fix: https://github.com/AppIntro/AppIntro/commit/a26a60307e15e151392b2337aee5892b0822d9cf

It seems like the instance of the `Fragment` returned by the call of `pagerAdapter.getItem()` is a stale one.

Can I ask you to test that it works fine on your end? Let me know if you need support creating a Debug APK (GH Actions runs only on PRs).

**Comment by cyb3rko** [comment]
Yep, fixed it now.

Thanks a lot!
