### ISSUE TITLE
ViewPagerTransformer crashes when no title

### ISSUE THREAD

**Issue by adriamt** [AppIntro/AppIntro#894]
Hi, 

I'm using `implementation 'com.github.AppIntro:appintro:master-SNAPSHOT'` for this #838 issue.

And I have and activity like this 

```
class WelcomeActivity : AppIntro() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        addSlide(Slide1Fragment())
        addSlide(Slide2Fragment())
        addSlide(Slide3Fragment())
        addSlide(Slide4Fragment())

        isButtonsEnabled = false

        setTransformer(AppIntroPageTransformerType.Parallax())
        showStatusBar(true)
        showSeparator(false)
    }
}
```

It was working fine lasts weeks since now that it crashes with this error

```
java.lang.NullPointerException: page.findViewById<TextView>(R.id.title) must not be null
        at com.github.appintro.internal.viewpager.ViewPagerTransformer.applyParallax(ViewPagerTransformer.kt:55)
        at com.github.appintro.internal.viewpager.ViewPagerTransformer.transformParallax(ViewPagerTransformer.kt:47)
        at com.github.appintro.internal.viewpager.ViewPagerTransformer.transformPage(ViewPagerTransformer.kt:39)

```

My custom fragments don't have any view with title, image or decription id, so when it does 
```
 private fun applyParallax(page: View, position: Float) {
        page.findViewById<TextView>(R.id.title).translationX = computeParallax(page, position, titlePF)
        page.findViewById<ImageView>(R.id.image).translationX = computeParallax(page, position, imagePF)
        page.findViewById<TextView>(R.id.description).translationX = computeParallax(page, position, descriptionPF)
    }
```

It crashed with a Null pointer exception. 

It was working fine since a few days ago. Any clue what it could be or what I can do? I don't wat to put these ID to my views (since it was working fine before).

Thanks.

**Comment by cortinico** [comment]
> It was working fine since a few days ago. Any clue what it could be or what I can do? I don't wat to put these ID to my views (since it was working fine before).

Can you please clarify?
I doubt it was working before as the Parallax relies on those 3 ids being set in order to animate them. Any other `AppIntroPageTransformerType` will work correctly without those IDs. Parallax is the only exception.

If you provide your own `Fragment` you should either:
- Add those IDs to 3 of your views
- Use a different `AppIntroPageTransformerType` other than `Fade`
- Provide your own `Transformer` with the method `setCustomTransformer` on AppIntro

**Comment by adriamt** [comment]
I don't know why, but I had it working like I showed since August.
I've just removed the Parallax transformer and now it doesn't crash.

**Comment by cortinico** [comment]
Great, thanks for the heads up 👍
