### ISSUE TITLE
Please provide a callback for the number of slides

### ISSUE THREAD

**Issue by OverLordAct** [AppIntro/AppIntro#899]
For a particular use case I want to know the number of pages currently in the viewpager. I wanted to modify the button behavior on say the last screen. Right now we have a callback onPageSelected() which would be really helpful for more custom behavior. For now, I am considering using a counter which is a nasty hack on the activity as it should be kept as dumb as possible. Thanks.

**Comment by cortinico** [comment]
> I wanted to modify the button behavior on say the last screen

Can you elaborate on this? Which button do you want to change?
You are responsible for providing the single slides, so you can easily provide the last slide with a custom button.

**Comment by OverLordAct** [comment]
So my current use case is: As soon as the user lands on the last page, all the buttons and the indicator will disappear. Now, I am hardcoding the number of pages in a const variable but it is not a good practice. Then I am overriding onPageSelected() as follows:

Here is 2 is hardcoded(assume total 3 pages)

` override fun onPageSelected(position: Int) {
        if (position == 2) {
            isButtonsEnabled = false
        }
        super.onPageSelected(position)
    }`

But as you can see it would be better if there was a way of knowing how many pages are there at runtime. An easy fix would be to provide another onPageSelected() method as: 

`protected open fun onPageSelected(position: Int, totalPages: Int) {}`

Why I am saying this: If in future I move to a backend driven UI, I will have no idea of how many pages are there and page addition will be done dynamically.

**Comment by cortinico** [comment]
> Now, I am hardcoding the number of pages in a const variable but it is not a good practice

For your specific use case you should probably consider doing something like:

```
override fun onPageSelected(position: Int) {
        if (position == slides.size) {
            isButtonsEnabled = false
        }
        super.onPageSelected(position)
    }
```

And have a property `slides` where you store your slides model (either a `SliderPage` or what else you're using to represent your pages).

> Why I am saying this: If in future I move to a backend driven UI, I will have no idea of how many pages are there and page addition will be done dynamically.

Seems like the underlying question is how to dynamically change the slides. Currently there is no support for that (#709).

**Comment by OverLordAct** [comment]
Got it. Thanks for the response.
