### ISSUE TITLE
Question : how do setButtonsEnabled / setNextPageSwipeLock work ?

### ISSUE THREAD

**Issue by RobbWatershed** [AppIntro/AppIntro#902]
I'm calling `setButtonsEnabled ` and `setNextPageSwipeLock` in the `onSlideChanged` method but it doesn't have any effect on navigation : buttons are still enabled and user can still swipe.

Is there something I'm doing wrong ?

**AppIntro Version**: 6.0.0

**Device/Android Version**: Huawei 8X

**Issue details / Repro steps / Use case background**: Using an activity extending `AppIntro2` with specialized fragments for certain slides

**Your Code**: 

```java

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addSlide(new WelcomeIntroFragment());
        addSlide(new ImportIntroFragment());
        addSlide(new ThemeIntroFragment());

        setWizardMode(true); // Replaces skip button with back button
        setSystemBackButtonLocked(true); // works
        setIndicatorEnabled(true);
        setSwipeLock(true); // <--- Doesn't work
    }

 @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        boolean isBlockProgress = (newFragment instanceof ImportIntroFragment);
        setButtonsEnabled(!isBlockProgress); // <-- doesn't have any effect
        setNextPageSwipeLock(isBlockProgress); // <-- doesn't have any effect
    }
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
No error message; none expected

**Comment by cortinico** [comment]
> I'm calling `setButtonsEnabled ` and `setNextPageSwipeLock` in the `onSlideChanged` method but it doesn't have any effect on navigation : buttons are still enabled and user can still swipe.

You're right, that's a bug.

The solution is to don't call `setNextPageSwipeLock` at all.

> `setSwipeLock(true); // <--- Doesn't work`

This actually works, it will block the swipe and enabled the navigation buttons.

> `setButtonsEnabled(false)`

This will disabled the navigation buttons.

I'm going to remove and deprecate the `setNextPageSwipeLock` method as it's causing more confusion than benefit.

**Comment by RobbWatershed** [comment]
Okay, thanks for the clarification. Deprecating it while inviting users to call `setSwipeLock` would be the right move indeed.

Talking about that one, I realized it works most of the time, except when I'm asking for a permission. When the slide asking for permission shows, when I accept the permission, swiping is enabled again, even though I explicitely call `setSwipeLock(true)` on every `onSlideChanged`.

Knowing that, I noticed that `AppIntroBase.onRequestPermissionsResult` makes a hard call to `setSwipeLock(false)`. Isn't that call interfering with my own ? Should I make my call in another override than `onSlideChanged` to avoid that ?

**Comment by cortinico** [comment]
> Talking about that one, I realized it works most of the time, except when I'm asking for a permission. When the slide asking for permission shows, when I accept the permission, swiping is enabled again, even though I explicitely call `setSwipeLock(true)` on every `onSlideChanged`.

You're right. Due to legacy reason, the code was written with the assumption that you would never mix explicit call to `setSwipeLock` and the Permission request system.

I believe we should cleanup the code around `requestPermission` to don't call explicitly `setSwipeLock(true)` and `setSwipeLock(false)` but instead operate on the `isFullPagingEnabled` and potentially retain the value set by the user.

> Knowing that, I noticed in your library's code that `AppIntroBase.onRequestPermissionsResult` makes a hard call to `setSwipeLock(false)`. Isn't that call interfering with my own ? Should I make my call in another override than `onSlideChanged` to avoid that ?

Yup, that's exactly the case. If you call `setSwipeLock(false)` inside the `onRequestPermissionsResult` (provided that you call also `super.onRequestPermissionsResult` before) it should work properly 👍

**Comment by RobbWatershed** [comment]
Thanks for the quick reply. Works for me now 😄
