### ISSUE TITLE
Getting this issue with 5% of my users

### ISSUE THREAD

**Issue by prorgammer** [AppIntro/AppIntro#906]
Getting this issue with 5% of my users. Please advise, thank you.
![firebase](https://user-images.githubusercontent.com/74988608/100145575-317fbf00-2ea1-11eb-8943-ca785aa6f7d3.PNG)

**Comment by cortinico** [comment]
- Which version of AppIntro are you using?
- Are you dynamically adding slides after you started the AppIntro?

**Comment by prorgammer** [comment]
- I use this: implementation 'com.github.AppIntro:appintro:master-SNAPSHOT'
- Yes.

**Comment by cortinico** [comment]
> Are you dynamically adding slides after you started the AppIntro?

This is currently not supported by AppIntro (see https://github.com/AppIntro/AppIntro/issues/709)

**Comment by prorgammer** [comment]
I'm sorry. I meant to say that no, I am not dynamically adding slides after having started the AppIntro.

**Comment by cortinico** [comment]
In order to better debug, could you please provide:
- The full stacktrace 
- The code of your AppIntro Activity (redacted if needed).

**Comment by cortinico** [comment]
Closing as it's impossible to reproduce as of today without further detail. Feel free to reopen if you can provide the requested information.
