### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [AppIntro/AppIntro#915]
**AppIntro Version**: 2.15.15

**Device/Android Version**: Google nexus 6，Android 8.0

**Issue details / Repro steps / Use case background**: 

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
App version is 2.15.15, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

<img width="444" alt="bug-beta_342" src="https://user-images.githubusercontent.com/18572115/103147382-5791cb00-478f-11eb-84d9-28078f22230b.png">

**Comment by cortinico** [comment]
> **AppIntro Version**: 2.15.15

This version of AppIntro is really old. Can you please update to `6.0` and update the issue description with the new outcome?

**Comment by cortinico** [comment]
My bad, I actually overlooked the issue. This is indeed something we can fix in the upcoming AppIntro version. See #922 for a fix.
