### ISSUE TITLE
Changing light/dark mode not works for color resources

### ISSUE THREAD

**Issue by Fabi755** [AppIntro/AppIntro#926]
**AppIntro Version**: current master (SNAPSHOT)

**Device/Android Version**: Emulator / Android 11 (API level 30)

**Issue details / Repro steps / Use case background**: 
If the intro is open and the dark mode configuration changes not all colors are changed.
1. Open intro in light mode
2. Change theme to dark mode by control center

The drawables (set by resource ID) will be changed like expected. All background & font colors (that set directly) does not change.

After the design mode changed the activity will recreated. The slides will added again with new (dark mode) parameters. The colors are set directly and I found that the onActivityCreated [AppIntroBaseFragment.kt#L73](https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/java/com/github/appintro/AppIntroBaseFragment.kt#L73) method is called while recreating with the "old" parameters and the explicit set colors will be reused.

The simplest solution is to give a color resource ID instead of the color itself. As more cleaner solution we should improve the instance saving flow to keep them per fragment itself instead to referencing to the activity lifecycle.

**Your Code**: 
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    // Have default + night variants
    // Works fine
    setIndicatorColor(
            selectedIndicatorColor = ContextCompat.getColor(this, R.color.intro_pagination_indicator),
            unselectedIndicatorColor = ContextCompat.getColor(this, R.color.meta_grey)
    )

    // Have default + night variants
    // Works fine
    setBackArrowColor(ContextCompat.getColor(this, R.color.accent))
    setNextArrowColor(ContextCompat.getColor(this, R.color.accent))
    setColorDoneText(ContextCompat.getColor(this, R.color.paper))

    addSlide(AppIntroFragment.newInstance(
            // ...

            // Has default + night variant
            // Works fine
            imageDrawable = R.drawable.ic_logo, 

            // Has default + night variant
            // Does NOT work
            titleColor = ContextCompat.getColor(this, R.color.text),

            // Has default + night variant
            // Does NOT work
            descriptionColor = ContextCompat.getColor(this, R.color.text),

            // Has default + night variant
            // Does NOT work
            backgroundColor = ContextCompat.getColor(this, R.color.paper),
            
            // ...
    ))
}
```

Working light:
<img src="https://home.fabiankeunecke.de/github/app-intro/screenshot-light-theme.png" height=250 />

Failed dark:
<img src="https://home.fabiankeunecke.de/github/app-intro/screenshot-dark-theme-fail.png" height=250 />

Expected result:
<img src="https://home.fabiankeunecke.de/github/app-intro/screenshot-dark-theme.png" height=250 />

I will playing around a little bit and make a PR next days.

**Comment by cortinico** [comment]
> The drawables (set by resource ID) will be changed like expected. All background & font colors (that set directly) does not change.

Yes I believe this is a potential bug, or at least an improvement we could offer.
I was however not able to verify this by myself.
Do you have a sample project or a reproducer I could look into? 

> I will playing around a little bit and make a PR next days.

Looking forward to that. Please let me know if you need some support.

**Comment by Fabi755** [comment]
> Do you have a sample project or a reproducer I could look into?

I now have created one:
https://github.com/Fabi755/appintro-example-dark

> I was however not able to verify this by myself.
Did I something wrong?

**Comment by cortinico** [comment]
Thanks for the reproducer 👍 That's definitely a bug/improvement for the future.

> The simplest solution is to give a color resource ID instead of the color itself. 

+1 for this. We should add 3 new parameters to the `SliderPage`:
```kotlin
    @ColorRes var backgroundColorRes: Int = 0,
    @ColorRes var titleColorRes: Int = 0,
    @ColorRes var descriptionColorRes: Int = 0,
```

And potentially start a deprecation cycle for the former `@ColorInt` parameters

> As more cleaner solution we should improve the instance saving flow to keep them per fragment itself nstead to referencing to the activity lifecycle.

That's also a plus but unrelated to this bug.

**Comment by tmcintosh** [comment]
Hi, is there a potential update on the fix?  Thanks!

**Comment by cortinico** [comment]
> Hi, is there a potential update on the fix? Thanks!

Not really, but @Fabi755 might have a fix incoming? 😁
