### ISSUE TITLE
isColorTransitionsEnabled  is not working with AppIntroCustomLayoutFragment

### ISSUE THREAD

**Issue by ratheeshcn** [AppIntro/AppIntro#928]
I have created slides using AppIntroCustomLayoutFragment layout and i was able to run the intro on default mode.

This code 
```
      addSlide(AppIntroCustomLayoutFragment.newInstance( R.layout.layout_intro_wizard1));
        addSlide(AppIntroCustomLayoutFragment.newInstance( R.layout.layout_intro_wizard2));
        addSlide(AppIntroCustomLayoutFragment.newInstance( R.layout.layout_intro_wizard3));
        ---------
         -----------

       setIndicatorColor(getResources().getColor(R.color.mdtp_white),getResources().getColor(R.color.dot));
```

**But** when I added the **isColorTransitionsEnabled**  on the slides I got the error ` error("Color transitions are only available if all slides implement SlideBackgroundColorHolder.")`

The problem here is I couldn't implement `SlideBackgroundColorHolder`  on a `AppIntroCustomLayoutFragment` so can somebody help me to solve this issue.

**AppIntro Version**: 6.1

**Device/Android Version**: Oneplus N10

**Comment by cortinico** [comment]
> The problem here is I couldn't implement `SlideBackgroundColorHolder` on a `AppIntroCustomLayoutFragment` so can somebody help me to solve this issue.

The error is pretty much self explanatory. `isColorTransitionsEnabled` works only if you provide fragments that are implementing the `SlideBackgroundColorHolder`.

So you need to pass your own `Fragment` that implements such interface.

As a suggestion you can use:

```kotlin
class MyCustomLayoutFragment : Fragment(), SlideBackgroundColorHolder {
    
    override val defaultBackgroundColor: Int
        get() = TODO("Not yet implemented")

    override fun setBackgroundColor(backgroundColor: Int) {
        TODO("Not yet implemented")
    }

    private var layoutResId = 0

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        layoutResId = arguments?.getInt(ARG_LAYOUT_RES_ID) ?: 0
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? = inflater.inflate(layoutResId, container, false)

    companion object {
        private const val ARG_LAYOUT_RES_ID = "layoutResId"
        @JvmStatic
        fun newInstance(layoutResId: Int): MyCustomLayoutFragment {
            val customSlide = MyCustomLayoutFragment()
            val args = Bundle()
            args.putInt(ARG_LAYOUT_RES_ID, layoutResId)
            customSlide.arguments = args
            return customSlide
        }
    }
}
```

As you can see, you need to implement those `TODO()` as you need to tell AppIntro where to get your colors and how to update them (it depends on your layout).

**Comment by cortinico** [comment]
I'm closing here, but if I haven't solved your issue feel free to reopen this issue
