### ISSUE TITLE
Background Location Permission on Android R

### ISSUE THREAD

**Issue by Wheedman** [AppIntro/AppIntro#929]
**AppIntro Version**: 6.1.0

**Device/Android Version**: Google Pixel 3 : Android R

**Issue details / Repro steps / Use case background**:  I do the askForPermissions on a slide but on Android R this does not work with Manifest.permission.ACCESS_BACKGROUND_LOCATION. It just skips to the next slide without asking any location related permission

**Your Code**:  ```askForPermissions(
                    permissions = arrayOf(
                        Manifest.permission.ACCESS_FINE_LOCATION,
                        Manifest.permission.ACCESS_BACKGROUND_LOCATION
                    ),
                    slideNumber = 4,
                    required = false
                )```

**Stack trace / LogCat**: None

**Comment by cortinico** [comment]
Thanks for raising this point. The "issue" is actually the intended behavior from Android SDK on API Level 30 and above.

Source: https://developer.android.com/training/location/permissions#request-location-access-runtime

> Even if several features in your app require location access, it's likely that only some of them require background location access. Therefore, it's recommended that your app performs incremental requests for location permissions, asking for foreground location access and then background location access. By performing incremental requests, you give users more control and transparency because they can better understand which features in your app need background location access.

> Caution: If your app targets Android 11 (API level 30) or higher, the system enforces this best practice. If you request a foreground location permission and the background location permission at the same time, the system ignores the request and doesn't grant your app either permission. 

So if you need to have both permissions, you need to access them in two distinct slides (and also provide a reason on why you need both foreground and background location access on separate slides).
