### ISSUE TITLE
How to lock back button

### ISSUE THREAD

**Issue by danielcerezodev** [AppIntro/AppIntro#933]
Hi everyone!

Just wondering if there is a way to lock the back button after a certain position has been reached. For example a user goes to position 2 and after the have moved to position 3 the back button is either locked or removed from the view.

**Comment by cortinico** [comment]
> Just wondering if there is a way to lock the back button after a certain position has been reached.

Not really. Also locking the back button won't prevent the user from just swiping left.
What's your use case? Have you considered using the `SlidePolicy` (that blocks only the forward swiping).

**Comment by danielcerezodev** [comment]
My use case is having one of the views to set a PIN. Once this PIN is set I would like to have the user not being able to go back into the previous fragment. I have used a SlidePolicy so the user cannot go forward unless they have set a PIN, but as you said they are still able to go back.

I think I might just need to have a PinActivity and if the user sets their PIN move them onto the welcome AppIntro

**Comment by cortinico** [comment]
> I have used a SlidePolicy so the user cannot go forward unless they have set a PIN, but as you said they are still able to go back.

I understand your use case. Historically we used to have something similar that got removed in one of the past version of AppIntro.

The rationale is that you always want to offer the user the possibility to read what was before in the carousel (that I believe is a legit assumption).

Probably having another activity that you can jump into from a custom button sounds like a good alternative.

**Comment by danielcerezodev** [comment]
Yeah I understand the reasoning. Thank you for the response and the help though, I appreciate it
