### ISSUE TITLE
Fragment Lifecycle events not triggered for Custom Fragments added to AppIntro

### ISSUE THREAD

**Issue by eliokhattar** [AppIntro/AppIntro#935]
**AppIntro Version**:6.1.0

**Device/Android Version**:Fails on Nokia 8, Android 9 - Fails on Android 10 Emulator.

**Issue details / Repro steps / Use case background**: 
- Trying to add a custom fragment to AppIntro, it gets displayed correctly, but all lifecycle events (onCreate, onCreateView ...) are not triggered
- So i am not able to modify the behavior of my button for example.

Reproduction Steps:
- Create a new Fragment (XML & JAVA class).
- In the Fragment java class override the onCreateView and add some logging.
- Attach the new fragment as a custom slide to App Intro.
- --> It gets displayed but the lifecycle events are not triggered
- Note: attaching the same fragment to another activity works fine and all events are executed.

**Your Code**: 

***FRAGMENT JAVA***

`public class IntroNotifPermissionFragment extends Fragment implements SlidePolicy {

    public IntroNotifPermissionFragment() {
        // Required empty public constructor
    }

    private Button permBtn = null;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        Log.d("PERM", "onCreate 01");
        super.onCreate(savedInstanceState);
        Log.d("PERM", "onCreate");
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View rootView = inflater.inflate(R.layout.fragment_intro_notif_permission, container, false);
        permBtn = (Button) rootView.findViewById(R.id.frag_perm_btm);
        permBtn.setText("Elio Khattar");

        Log.d("PERM", "onViewCrete+ set Button");

        permBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.d("PERM", "btnClicked");
                Intent intent = new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS");
                startActivity(intent);
                Toast.makeText(getActivity(), getString(R.string.permission_toast_text), Toast.LENGTH_LONG).show();
            }
        });

        return rootView;
    }

    @Override
    public boolean isPolicyRespected() {
        return true;
    }

    @Override
    public void onUserIllegallyRequestedNextPage() {
            ;
    }
}`

***FRAGMENT XML***

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/introBg3"
    android:orientation="vertical"
    tools:context=".fragments.IntroNotifPermissionFragment">

    <TextView
        android:id="@+id/frag_perm_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/intro3a"
        android:textColor="@color/colorWhite"
        android:textSize="30dp"
        android:textStyle="bold"
        android:paddingTop="60dp"
        android:paddingBottom="25dp"
        android:layout_gravity="center_horizontal"
        />

    <ImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_notiflistener" />

    <TextView
        android:id="@+id/frag_perm_desc"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/intro3b"
        android:textColor="@color/colorWhite"
        android:layout_gravity="center_horizontal"
        android:textAlignment="center"
        android:paddingTop="10dp"
        android:textSize="16dp"
        android:paddingEnd="20dp"
        android:paddingStart="20dp"/>

    
        <Button
            android:id="@+id/frag_perm_btm"
            android:layout_gravity="center_horizontal"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            android:textColor="@color/colorButtonBackground"
            android:backgroundTint="@color/colorWhite"
            android:text="@string/intro3c" />
    
</LinearLayout>`

***Intro Activity***

`public class IntroActivity extends AppIntro {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addSlide( AppIntroCustomLayoutFragment.newInstance(R.layout.fragment_intro_notif_permission));

    }

    @Override
    protected void onDonePressed(@org.jetbrains.annotations.Nullable Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        finish();
    }

    @Override
    protected void onSkipPressed(@org.jetbrains.annotations.Nullable Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        finish();
    }

}`

**Stack trace / LogCat**:
N/A: no errors.
paste stack trace and/or log here
N/A: no errors.

**Comment by cortinico** [comment]
> * Trying to add a custom fragment to AppIntro, it gets displayed correctly, but all lifecycle events (onCreate, onCreateView ...) are not triggered
> 
> * So i am not able to modify the behavior of my button for example.

That's the "intended" behavior. The `onCreate`, `onCreateView` methods are called but before the Fragment is actually displayed. That's how ViewPager and `FragmentPagerAdapter` works.

If you want to get a callback when the Fragment is actually displayed you should use instead something like `setUserVisibleHint` like https://stackoverflow.com/a/11075663
