### ISSUE TITLE
Feature Request: add permission request to the last added slide

### ISSUE THREAD

**Issue by binarynoise** [AppIntro/AppIntro#941]
**AppIntro Version**: 6.1.0

**Device/Android Version**: - 

**Issue details / Repro steps / Use case background**: 
I want to do dynamic permission requests on startup that is, adding slides with permission requests on demand like this:

```kotlin
addSlide(AppIntroFragment.newInstance(
	title = "Welcome...",
	description = "Thanks for using " + getString(R.string.app_name),
))
addSlide(AppIntroFragment.newInstance(
	title = "Permissions...",
	description = "We need some permissions.",
))
if (ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED ) {
	addSlide(AppIntroFragment.newInstance(
		title = "Storage Permission...",
	))
	askForPermissions(arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE), slideNumber = 3)
}
if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_CONTACTS) != PackageManager.PERMISSION_GRANTED){
	addSlide(AppIntroFragment.newInstance(
		title = "Contacts Permission...",
	))
	askForPermissions(arrayOf(Manifest.permission.READ_CONTACTS), slideNumber = <?>)
	// Problem here                                                              ↑
}
addSlide(AppIntroFragment.newInstance(
	title = "...Let's get started!",
	description = "This is the last slide, I won't annoy you more :)",
))
```

You can't specify the slide number well because it depends on the current position and on whether the storage permission request has been added.

I'D suggest to modify the askForPermissions function like this:
```kotlin
@JvmOverloads
protected fun askForPermissions(permissions: Array<String>, slideNumber: Int = -1, required: Boolean = true) {
    val slideNumber = if (slideNumber < 0) fragments.size + slideNumber else slideNumber

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        if (slideNumber <= 0) {
            error("Invalid Slide Number: $slideNumber")
        } else {
            permissionsMap[slideNumber] = PermissionWrapper(permissions, slideNumber, required)
        }
    }
}
```

What do you think of this?

**Comment by binarynoise** [comment]
Alternatively you could expose the current amount of slides.

**Comment by cortinico** [comment]
> Alternatively you could expose the current amount of slides.

Have you considering storing a counter of number of slides you added (i.e. the number of times you called `addSlide`) and using it instead?

**Comment by binarynoise** [comment]
Yes, I thought of that and I feared that I'd forget incrementing this counter sometimes. 
Also I thought that would be a feature that could also be handy for others. 
I could have built some replacement function for add slides that does that automatically but currently I just grab the slide count using reflection.

**Comment by cortinico** [comment]
>  Also I thought that would be a feature that could also be handy for others.

I believe the underlying issue is #709 (and linked issue).
The library currently doesn't support adding/removing slides dynamically.
What you're experiencing is a side effect of this architectural decision.

Given that there is an easy workaround to your specific scenario, I'm closing this.
If there is a need in the community to have the number of slides exposed, we could also consider to expose a field for it 👍
