### ISSUE TITLE
slidesNumber is private

### ISSUE THREAD

**Issue by hanibalsk** [AppIntro/AppIntro#954]
## ⚠️ Is your feature request related to a problem? Please describe

Too strict private properties

## 💡 Consider to add more protected methods

I understand many reasons to have some fields private, but for instance slidesNumber should consider be protected. Also there should be possibility to skip to last or specific slide

**Comment by cortinico** [comment]
Yup you're right. It makes sense to expose it. Here it is https://github.com/AppIntro/AppIntro/pull/960
