### ISSUE TITLE
Calling goToNextSlide() from Java

### ISSUE THREAD

**Issue by alecpetrosky** [AppIntro/AppIntro#955]
## ⚠️ Is your feature request related to a problem? Please describe

goToNextSlide() has default parameter values however it's impossible to use goToNextSlide from Java because it requires isLastSlide which relies on internal logic.

From Kotlin document:

> Normally, if you write a Kotlin method with default parameter values, it will be visible in Java only as a full signature, with all parameters present. If you wish to expose multiple overloads to Java callers, you can use the @JvmOverloads annotation.

## 💡 Describe the solution you'd like

Please add @JvmOverloads annotation for goToNextSlide so we can use this method from Java without the need to provide isLastSlide.

## 🤚 Do you want to develop this feature yourself?
- [ ] Yes
- [X] No

**Comment by alecpetrosky** [comment]
Currently, as workaround for this problem, I implemented Kotlin wrapper class with a single method goToNext, then I extend wrapper this class in my Java class and call goToNext instead of goToNextSlide.

```
abstract class BaseAppIntro : AppIntro() {
    protected fun goToNext() {
        goToNextSlide();
    }
}
```

**Comment by nicolabeghin** [comment]
Following - trying to [migrate from 5.x to 6.x](https://github.com/AppIntro/AppIntro/blob/master/docs/migrating-from-5.0.md) but missing `getPager().goToNextSlide();`

**Comment by cortinico** [comment]
> goToNextSlide() has default parameter values however it's impossible to use goToNextSlide from Java because it requires isLastSlide which relies on internal logic.

To chime in here, we can definitely add a `@JvmOverload` there.
I'm currently quite busy but I should be able to tackle this sometimes next week.

> Following - trying to migrate from 5.x to 6.x but missing getPager().goToNextSlide();

@nicolabeghin You should use `.goToNextSlide` on your `AppIntroBase` class, it's `protected` in Kotlin. If you class is also in Kotlin you should have no problem. If your class is in Java, you'll face the problem reported by @alecpetrosky.

**Comment by nicolabeghin** [comment]
thanks @cortinico I confirm I'm on Java so will wait for the `@JvmOverload` annotation.
