### ISSUE TITLE
Descriptions are blocked when using the largest font and display size

### ISSUE THREAD

**Issue by yuhuitech** [AppIntro/AppIntro#963]
## 🐛 Describe the bug
Hello! Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on those intro pages, **there are some texts that could not be seen fully, and they are not scrollable as well**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

## ⚠️ Current behavior
There are some texts that could not be seen fully when I set the display size and font to the largest, especially when the description is very long, which might overflow and there is no way for me to see them, unless I shrink the size. And as far as I have known, there are a lot of other apps that applied your package and also had this problem. I would appreciate it if you could review my issue. :)

## ✅ Expected behavior
I hope to see those descriptions fully.

## 💣 Steps to reproduce
1. use the largest font and display in the display setting
2. open this app(AppIntro Sample App), then click the start button on the Default Intro card.
3. this error could be seen when you scroll all the way down to the third page.

## 📷 Screenshots
The blocked part has been circled in red already.

<img src="https://user-images.githubusercontent.com/25502419/131211862-100bdb96-3e67-4970-81e2-148625ffa2b3.png" alt="copy" width="250"/>

## 📑 Your Code
I would like to solve this problem with a pull request! :)

## 📱 Tech info
 - AppIntro Version: 6.1.0
 - Device: Pixel 2
 - Android OS Version: 10

**Comment by cortinico** [comment]
Thanks for your report. I've followed up on #964
