### ISSUE TITLE
Violates Fragment StrictMode

### ISSUE THREAD

**Issue by h6ah4i** [AppIntro/AppIntro#965]
## 🐛 Describe the bug

**This is not a critical issue at present, but it should be fixed in a future release.**

The AndroidX Fragment v1.4.0 (NOTE: currently in alpha release) has introduced [Strict Mode](https://developer.android.com/jetpack/androidx/releases/fragment#version_140_2) that detects deprecated usages.

```kotlin
FragmentStrictMode.setDefaultPolicy(FragmentStrictMode.Policy.Builder()
    .detectFragmentReuse()
    .detectFragmentTagUsage()
    .detectRetainInstanceUsage()
    .detectSetUserVisibleHint()
    .detectTargetFragmentUsage()
    .detectWrongFragmentContainer()
    .apply {
        // !!! the followings are required for AppIntro !!!
        allowViolation(AppIntroFragment::class.java, RetainInstanceUsageViolation::class.java)
        allowViolation(AppIntroFragment::class.java, WrongFragmentContainerViolation::class.java)
    }
    .penaltyDeath()
    .build())
```

## ⚠️ Current behavior
Using some deprecated APIs/usages in Fragment v1.4.0.

## ✅ Expected behavior
Migrate AppIntro not to use deprecated Fragment APIs.

## 💣 Steps to reproduce

See the description of the issue.

## 📑 Your Code

See the description of the issue.

## 📱 Tech info
 - AppIntro Version: 6.1.0
 - AndroidX Fragment: 1.4.0-alpha07

**Comment by cortinico** [comment]
Thanks for the report. That's definitely something we need to look into.
Happy to review a Pull Request if anyone has some time to look into this 👍

**Comment by paolorotolo** [comment]
`WrongFragmentContainerViolation` has been fixed with ViewPager2 migration.
Closing this since we're tracking retainInstance deprecation on https://github.com/AppIntro/AppIntro/issues/1050 .

Thanks for your report.
