### ISSUE TITLE
Failed to resolve: com.github.AppIntro:AppIntro:6.1.0

### ISSUE THREAD

**Issue by anta40** [AppIntro/AppIntro#971]
I'm using Android Studio Arctic Fox 2020.3.1 Patch 2.

On the project build.gradle, I have this:
```
buildscript {

    repositories {
        google()
        mavenCentral()
        maven { url "https://www.jitpack.io" }
    }

```
and on the module build.gradle:
```
dependencies {
    implementation 'com.github.AppIntro:AppIntro:6.1.0'
    ...
}
```

I've used older AppIntros on some side projects succesfully. Ato-import always worked, e.g type `AppIntro`, hit Alt-Enter and Android Studio will automatically import that. But seems there's a problem on this version. On Sync output, there's this message:

> Failed to resolve: com.github.AppIntro:AppIntro:6.1.0
> <a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
> Affected Modules: <a href="openFile:C:/Users/anta40/AndroidStudioProjects/DigitalRemittanceTestApp/app/build.gradle">app</a>

**Comment by RobbWatershed** [comment]
On my project, the repo address isn't in the `buildscript` node but in the `allprojects` node

**Comment by cortinico** [comment]
> On my project, the jitpack repo address isn't in the `buildscript` node but in the `allprojects` node

That's the correct solution. Jitpack should be moved in the top level `repositories{}` block and not inside the `buildscript{}` on. More on this here https://jitpack.io/#AppIntro/AppIntro/6.1.0
