### ISSUE TITLE
Please can I change the skip and next background color?

### ISSUE THREAD

**Issue by SadraxKasCic** [AppIntro/AppIntro#994]
## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [ ] No

**Comment by cortinico** [comment]
Please do the extra effort to fill in the issue detail 🙏

**Comment by SadraxKasCic** [comment]
OKK thanks Boss.
Best regards

Le mar. 25 janv. 2022 à 13:47, Nicola Corti ***@***.***> a
écrit :
