### ISSUE TITLE
Load issue after rotate two times

### ISSUE THREAD

**Issue by rezazarchi** [AppIntro/AppIntro#995]
## 🐛 Describe the bug
Rotated two times and then swiped pages and went to the third page, but it didn't load immediately.
When I set transformer to AppIntroPageTransformerType.Fade, It didn't load anymore. I should go to the next slide and then back to that to load that page.

## ⚠️ Current behavior
Third fragment loads after a second with the default transformer
Third fragment doesn't load with the Fade transformer

## ✅ Expected behavior
It should load immediately like other fragments

## 💣 Steps to reproduce
1 - Go to Default Intro
2 - Rotate device to Landscape
3 - Rotate device to Portrait
4 - Swipe and go to the second page
5 - Swipe and go to the third page

## 📷 Screenshots
https://user-images.githubusercontent.com/8654398/150964255-b6d82547-20f0-48c7-a475-fac45710aad2.mp4

## 📑 Your Code
example code (default intro)

## 📱 Tech info
 - AppIntro Version: 6.2.0
 - Branch: master
 - Head commit: 65981e52426a21fb3fdf419e6bbcf86e5c8c685b
 - Device: Android Emulator
 - Android OS Version: 11

**Comment by rezazarchi** [comment]
I think that's because of offscreenPageLimit. I set ```java pager.offscreenPageLimit = fragments.size``` in AppIntroBase and the issue had fixed.
It's already handled when you enable wizard mode.

**Comment by cortinico** [comment]
> I think that's because of offscreenPageLimit. I set `pager.offscreenPageLimit = fragments.size` in **AppIntroBase** and the issue had fixed.

Don't you mind sending over a PR?

**Comment by rezazarchi** [comment]
Yes. sure.
