### ISSUE TITLE
AppIntro 6.2.0 Not able to build Please check 

### ISSUE THREAD

**Issue by heihitesh** [AppIntro/AppIntro#996]
https://jitpack.io/com/github/AppIntro/appintro/6.2.0/build.log

**Comment by paolorotolo** [comment]
Ok, I've triggered a new JitPack run and now it successfully built 6.2.0. Thanks, guys.

**Comment by heihitesh** [comment]
Its working Now :)

Thank You

**Comment by wal0x** [comment]
Still not working for me. I've added `maven { url 'https://jitpack.io' }` in `build.grqdle` and in `settings.gradle` too wthout any success.
