### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by soiavaq** [AppIntro/AppIntro#999]
Failed to resolve: com.github.AppIntro:AppIntro:6.2.0

> buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10'
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

**Comment by cortinico** [comment]
Duplicates #996 
The fix for this is in #998

**Comment by paolorotolo** [comment]
Should work now, thanks for reporting this!
